function apf = MTAAknnpfs_bs_20160919_001
% Analysis Parameter File 
%
% Target:  MTAAknpfs_bs
% Date:    20160919
% Author:  Justin Graboski
% 


apf = struct('overwrite',          true, ...
             'binDims',            [20,20],...
             'nNearestNeighbors',  60,...
             'ufrShufBlockSize',   1,...
             'distThreshold',      125,...
             'numIter',            1001,...
             'sampleRate',         10);
