
defargs = struct('fetSet',   'fet_mis',...
                 'mode',     'display',...
                 'tag_preprocessing',      '+seh+',...
                 'tag_postprocessing',      '',...
                 'rlist',    'training_hand_labeled',...
                 'slist',   {{'hand_labeled_jg';'hand_labeled_Ed'}},...
                 'sampleRate', 12,...
                 'nNeurons',   100,...
                 'nIter',      100,...
                 'states',   {{'walk','rear','turn','pause','groom','sit'}},...
                 'rndMethod', 'WSBNT',...
                 'norm',      true,...
                 'mref',      true,...
                 'prctTrain',   [] ...
);


[fetSet, mode, tag_preprocessing, tag_postprocessing,rlist, slist, sampleRate,...
 nNeurons, nIter, states, rndMethod, norm, mref,prctTrain] = DefaultArgs(varargin,defargs,'--struct');

rlist = get_session_list(rlist);

Trial = MTATrial.validate('Ed03-20140624');

rli = 1;
model = ['MTAC_BATCH-' tag_preprocessing fetSet ...
         '_SR_' num2str(sampleRate)             ...
         '_NORM_' num2str(norm)                 ...
         '_REF_' rlist(rli).sessionName,        ...
         '.' rlist(rli).mazeName        ...
         '.' rlist(rli).trialName       ...
         '_STC_' rlist(rli).stcMode             ...
         '_NN_' num2str(nNeurons)               ...
         '_NI_' num2str(nIter)                  ...
         '_NN_multiPN_RAND_' rndMethod];


            
stc = {}; d_state = {};p_state = {}; ls = {}; lsm = {};mdl = {};

Trial.load('stc','hand_labeled_rev1_Ed');
clear('mod');
mod.states     = states;
mod.stcMode    = 'hand_labeled_rev1_Ed';
mod.featureSet = fetSet;
mod.model      = model;
mod.sampleRate = sampleRate;
mod.nNeurons   = nNeurons;
mod.nIter      = nIter;
mod.map2reference = mref;
mod.normalize = norm;
argin = struct2varargin(mod);

[stc{end+1},d_state{end+1},     ls{end+1},...
 lsm{end+1},    mdl{end+1},p_state{end+1}] = ...
    bhv_nn_multi_patternnet(Trial,argin{:});
