
Trial = MTATrial.validate('er01-20110722.cof.all');
Trial = MTATrial.validate('er01-20110721.cof.all');
Trial = MTATrial.validate('er01-20110719.cof.all');

s = MTASession.validate('ER06-20130625.cof.all');
s.spk.create(s);
s.save();
Trial = MTATrial.validate('ER06-20130625.cof.all');
Trial = MTATrial.validate('jg05-20120312.cof.all');

Trial.load('lfp',[49,56]);
%Trial.load('lfp',[10,32]); %er01
%Trial.load('lfp',[9,16]);  %ER06 ?
lfp = Trial.lfp.copy();


rfp = copy(lfp);
rfp.data = diff(rfp.data, 1, 2);

% $$$ figure();
% $$$ subplot(211);
% $$$ hist2([rphz([Trial.stc{'w&t'}]),lphz([Trial.stc{'w&t'}],2)],32,32);
% $$$ subplot(212);
% $$$ hist2([rphz([Trial.stc{'s&t'}]),lphz([Trial.stc{'s&t'}],2)],32,32);


samplerate = 250;
xyz = preproc_xyz(Trial,[],samplerate);
units = get_unit_set(Trial.spk,Trial,'placecells');
pft = pfs_2d_theta(Trial);

ghz = compute_ghz( Trial, units, pft, 'sampleRate', samplerate);
ddz = compute_ddz( Trial, units, pft, 'sampleRate', samplerate);

lphz = load_theta_phase(Trial, samplerate, 49);
rphz = load_thetarc_phase(Trial, samplerate, [49,56]);
spk = Trial.load('spk',samplerate,'theta');

[P_HHG_r,   phzStats_HHG_r, Rmax_HHG_r, rho_HHG_r] =                        ...
    MjgER2016_phasePrecession(                                              ...
        Trial,                                                              ...
        ghz,                                                                ...
        ddz,                                                                ...
        rphz,                                                               ...
        spk,                                                                ...
        units,                                                              ...
        [],[],[],                                                           ...
        'placefield_ghz_theta',                                             ...
        'overwrite', true);


[P_HHG_l,   phzStats_HHG_l, Rmax_HHG_l, rho_HHG_l] =                        ...
    MjgER2016_phasePrecession(                                              ...
        Trial,                                                              ...
        ghz,                                                                ...
        ddz,                                                                ...
        lphz,                                                               ...
        spk,                                                                ...
        units,                                                              ...
        [],[],[],                                                           ...
        'placefield_ghz_theta',                                             ...
        'overwrite', true);



figure,
for unit = units'
    clf();
    
    subplot2(2,3,1,1);
    plot(pft,unit,[],'text');
    
    u = unit==units;
    mres = spk(unit);
    subplot2(2,3,1,2);
        hold('on');
        plot(                                                               ...
            ghz(mres,u),                                                    ...
            circ_rad2ang(lphz(mres)),                                       ...
            '.b'                                                            ...
            );
        plot(                                                               ...
            ghz(mres,u),                                                    ...
            circ_rad2ang(lphz(mres) - 2*pi),                                ...
            '.b'                                                            ...
            );
        tphz = circ_rad2ang(P_HHG_l(u,1,1)*[-1,1]+P_HHG_l(u,2,1));
        plot(                                                               ...
            [-1,1],                                                         ...
            tphz,                                                           ...
            '-m',                                                           ...
            'LineWidth',1);
        plot(                                                               ...
            [-1,1],                                                         ...
             tphz-360,                                                      ...
            '-m',                                                           ...
            'LineWidth',1)  
        title(['GHZ rho lfp: ',num2str(round(rho_HHG_l(u),2))]);
        ylim([-360,360]);
    
    subplot2(2,3,1,3);
        histcirc(lphz(spk(unit)));
        title(num2str(circ_r(lphz(spk(unit)))));
        
    subplot2(2,3,2,2);
        hold('on');
        plot(                                                               ...
            ghz(mres,u),                                                    ...
            circ_rad2ang(rphz(mres)),                                       ...
            '.b'                                                            ...
            );
        plot(                                                               ...
            ghz(mres,u),                                                    ...
            circ_rad2ang(rphz(mres)-2*pi),                                  ...
            '.b'                                                            ...
            );
        tphz = circ_rad2ang(P_HHG_r(u,1,1)*[-1,1]+P_HHG_r(u,2,1));
        plot(                                                               ...
            [-1,1],                                                         ...
            tphz,                                                           ...
            '-m',                                                           ...
            'LineWidth',1);
        plot(                                                               ...
            [-1,1],                                                         ...
            tphz-360,                                                       ...
            '-m',                                                           ...
            'LineWidth',1);
        title(['GHZ rho rfp: ',num2str(round(rho_HHG_r(u),2))]);
        ylim([-360,360]);
    subplot2(2,3,2,3);
        histcirc(rphz(spk(unit)));
        title(num2str(circ_r(rphz(spk(unit)))));
    
    waitforbuttonpress();
end        


