function sp = add_subplot_to_grid(hfig,figOpts,xind,yind)
%function sp = add_subplot_to_grid(hfig,figOpts,xind,yind)

sp = axes('Parent',           hfig,...
          'Units',            'centimeters',...
          'Position',         [figOpts.page.xpos(xind),...
                               figOpts.page.ypos(yind),...
                               figOpts.subplot.width,  ...
                               figOpts.subplot.height],...
          'FontSize', 8);