function sax = place_subplot(hfig,sax,Position,figOpts,varargin)

% DEFARGS ------------------------------------------------------------------------------------------
defargs = struct('scaleWidth',                       1,                                          ...
                 'scaleHeight',                      1                                           ...
);
[scaleWidth, scaleHeight] = DefaultArgs(varargin,defargs,'--struct');
%---------------------------------------------------------------------------------------------------       

Position = num2cell(Position);
[yind, yOffSet, xind, xOffSet] = deal(Position{:});
sax(end+1) = axes(  'Parent',hfig,                                  ...
                     'Units',figOpts.subplot.units,                 ...
                  'Position',[figOpts.page.xpos(xind)+xOffSet,      ...
                              figOpts.page.ypos(yind)+yOffSet,      ...
                              figOpts.subplot.width.*scaleWidth,    ...
                              figOpts.subplot.height.*scaleHeight], ...
                  'FontSize', 8,                                    ...
                 'LineWidth',1);

