function decoded = EgoProCode2D_u_init_decoded_struct()

decoded = struct('fwd', [],...
                 'lat', [],...
                 'tfwd',[],...
                 'tlat',[],...
                 'xyz', [],...
                 'dst', [],...
                 'hvf', [],...
                 'hvl', [],...
                 'bvl', [],...
                 'bvf', [],...                 
                 'hvlF',[],...
                 'hvlP',[],...                 
                 'hav', [],...
                 'hba', [],...
                 'phz', [],...
                 'clat',[],...
                 'ang', [],...
                 'rad', [],...
                 'trl', []);
