#!/bin/bash

# lrzc
#
# Type: utilitiy 
# Author: Justin Graboski
# Last Modified: 20160411
# Purpose: submits a job or a list of jobs
#          to the LMU LRZ center clusters.
#
# Version: 0.01 (alpha)
# 
# Dependencies:
#    matlab_sumbit_lrz.c (never again)
#    tart
#    MatSubmitLRZ

function print_help(){
    echo "LRZ Cluster Interface"
    echo "usage: lrzc [--version] [--help]"
    echo ""
    echo " Command List:"
    echo ""    
    echo "    sbatch        Submit matlab script to LRZ cluster"
    echo "    squeue        Query the LRZ SLURM for user related jobs on LRZ cluster"
    echo "    scancel       Cancel all or specific jobs on the LRZ cluster"
    echo "    matlab        Start an interactive matlab session on an LRZ cluster"
    echo "    sync          Synchronize a selection of folders to an LRZ partition"
    echo "    help          Display this message"
}



if [[ "$#" == 0 ]]
then    
   print_help
fi
   


key="$1"
case $key in
    sbatch)
	shift
	if [[ "$#" == 0 ]]
	then
	    MatSubmitLRZ --help
	else
       	    MatSubmitLRZ "$@"
	fi
	;;
    squeue)
	shift
	if [[ "$#" == 0 ]]
	then
           ssh "$USERNAME_LRZ@$HOST_LRZ" "squeue --user USERNAME_LRZ --clusters hugemem,mpp1,mpp2,serial"
	else
	   ssh "$USERNAME_LRZ@$HOST_LRZ" "squeue $@"
	fi
	;;

    scancel)
	shift
	if [[ "$#" == 0 ]]
	then
           ssh "$USERNAME_LRZ@$HOST_LRZ" "scancel --user USERNAME_LRZ --clusters hugemem,mpp1,mpp2,serial"
	else
	   ssh "$USERNAME_LRZ@$HOST_LRZ" "scancel --user USERNAME_LRZ $@"
	fi
	;;

    matlab)	
	;;
    sync)
	shift
	if [[ "$#" == 0 ]]
	then
           tart -d 1 -s data/
	else
           tart "$@"
	fi
	
	;;
    
    
    "help")
        print_help
	;;
    *)
	;;
esac
