#!/bin/bash

# lrzc
#
# Type: utilitiy 
# Author: Justin Graboski
# Last Modified: 20160411
# Purpose: submits a job or a list of jobs
#          to the LMU LRZ center clusters.
#
# Version: 0.01 (alpha)
# 
# Dependencies: matlab_sumbit_lrz.c
#

function print_help(){
    echo "help - I don't know what I do"
}



if [[ "$#" == 0 ]]
then    
   print_help
fi
   


key="$1"
case $key in
    sbatch)
	shift
	if [[ "$#" == 0 ]]
	then
	    MatSubmitLRZ --help
	else
       	    MatSubmitLRZ "$@"
	fi
	;;
    squeue)
	shift
	if [[ "$#" == 0 ]]
	then
           ssh "$USERNAME_LRZ@$HOST_LRZ" "squeue --user USERNAME_LRZ --clusters hugemem,mpp1,mpp2,serial"
	else
	   ssh "$USERNAME_LRZ@$HOST_LRZ" "squeue $@"
	fi
	;;

    scancel)
	shift
	if [[ "$#" == 0 ]]
	then
           ssh "$USERNAME_LRZ@$HOST_LRZ" "scancel --user USERNAME_LRZ --clusters hugemem,mpp1,mpp2,serial"
	else
	   ssh "$USERNAME_LRZ@$HOST_LRZ" "scancel --user USERNAME_LRZ $@"
	fi
	;;

    matlab)	
	;;
    sync)
	shift
	if [[ "$#" == 0 ]]
	then
           tart -d 1 -s data/
	else
           tart "$@"
	fi
	
	;;
    
    
    "help")
        print_help
	;;
    *)
	;;
esac
