matlab_submit_lrz: matlab_submit_lrz.o
	gcc $(CFLAGS) -o matlab_submit_lrz  matlab_submit_lrz.o

matlab_submit_lrz.0: matlab_submit_lrz.c
	gcc $(CFLAGS) -c matlab_submit_lrz.c

clean:
	rm -f *.o matlab_submit_lrz

