function paths = MTAConfiguration(root_dir)
%% still needs work
user = user(uind:end-1);
if ispc, 
    userdir= getenv('USERPROFILE'); 
else
    userdir= getenv('HOME');
end

sysroot

%paths to the data directories
data = fullfile(userdir,root_dir);
MTAPath = fullfile(userdir,root_dir,'Config','MTA');

%List of the accepted marker names
MTAMarkers ={'hip_right','pelvis_root','hip_left','spine_lower','knee_left','knee_right','tail_base','tail_end','spine_middle','spine_upper','head_back','head_left','head_front','head_right','shoulder_left','elbow_left','shoulder_right','elbow_right','head_top'};

%List of the accepted mazes
MTAMazes = {{'cof','circle',   [-500,500;-500,500;0,300],[-500,500;-500,500;0,360]},...
            {'sof','square'},...
            {'rof','rectangle',[-800,800;-500,500;0,300],[-800,800;-500,500;0,300]},...
            {'tm','circle',    [-500,500;-500,500;0,300],[-500,500;-500,500;0,360]}};

%List of the accepted connections between markers
MTAMarkerConnections = {{'head_front','head_left' },...
    {'head_front','head_right'},...
    {'head_right','head_left' },...
    {'head_left' ,'head_back' },...
    {'head_right','head_back' },...
    {'head_back' ,'spine_upper'},...
    {'spine_upper','shoulder_right'},...
    {'spine_upper','shoulder_left' },...
    {'spine_upper','spine_middle'  },...
    {'spine_middle','pelvis_root'  },...
    {'pelvis_root', 'hip_right'  },...
    {'pelvis_root', 'hip_left'   },...
    {'pelvis_root', 'spine_lower'},...
    {'spine_lower', 'hip_right'  },...
    {'spine_lower', 'hip_left'},...
    {'hip_left','hip_right'},...
    {'hip_left','knee_left'},...
    {'hip_right','knee_right'},...
    {'head_top','head_front'},...
    {'head_top','head_left'},...
    {'head_top','head_right'},...
    {'head_top','head_back'}, ...
    {'tail_proximal','spine_lower'}};

save([ '/tmp/MTAPaths.mat'],'MTAPath','data')
save([ '/tmp/MTAMarkers.mat'],'MTAMarkers')
save([ '/tmp/MTAMazes.mat'],'MTAMazes')
save([ '/tmp/MTAMarkerConnections.mat'],'MTAMarkerConnections')

end