function MTAConfiguration(projectPath,varargin)
% MTAConfiguration(projectPath,flag)
% Sets up the directories, and variable lists required for MTA
%
% Variables:
%   projectPath: string, Path to the data directory
%
%   flag:     string, Path options
%     values: absolute,  assumes the given path starts in the root dir
%             otherwise, assumes the given path starts in the home dir
%
% Example:
%   MTAConfiguration('/data/home/username/data_projectPath','absolute')
%
%   MTAConfiguration('C:\Users\username\data_root_dir','absolute')
%
%   MTAConfiguration('data_root_dir','absolute')
%
% Configuration Files:
%    MTAPaths.mat  
%       The paths where the data and config folders exist
%
%    MTAMarkers.mat
%       The marker list whith valid marker names (May remove in the future)
%
%    MTAMazes.mat 
%       Cell array containing all information over mazes (Will be replaced by a
%       database)
%
%    MTAMarkerConnections.mat
%       Defined connections between markers (Not required if vsk file is
%       present)
% 

global MTA_PATH
global MTA_DATA_PATH;
global MTA_PROJECT_PATH % use this in the future to set root dir
global MTA_FIGURES_PATH

MTA_FIGURES_PATH = getenv('MTA_FIGURES_PATH'); 

[flag,project_name,host_server,data_server,overwrite] = DefaultArgs(varargin,{'','','','',true});

if ispc, 
    userdir= getenv('USERPROFILE'); 
else
    userdir= getenv('HOME');
end

% SET path to MTA toolbox directory
if isempty(MTA_PATH),
    MTA_PATH = fileparts(mfilename('fullpath'));
end

if ~isempty(MTA_DATA_PATH),
    data = MTA_DATA_PATH;
else
    data = fileparts(projectPath);
    data = fileparts(data);
end


    

% SET paths to the data directory
switch flag
    case 'absolute'
        project = projectPath;
    otherwise
        project = fullfile(userdir,projectPath);
end

% SETUP paths
cfg             = fullfile(project,'config','MTA');
arm             = fullfile(cfg,'arm');
web             = fullfile(cfg,'web');
analysisDir     = fullfile(MTA_PROJECT_PATH,'analysis');
matlabDir       = fullfile(MTA_PROJECT_PATH,'matlab');
classifiersDir  = fullfile(MTA_PROJECT_PATH,'matlab','classifiers');
analysisModelDir = fullfile(analysisDir,'models');

create_directory(fullfile(project,'config'));
create_directory(cfg);
create_directory(analysisDir);
create_directory(matlabDir);
create_directory(classifiersDir);
create_directory(analysisModelDir);

if overwrite, copyfile(fullfile(MTA_PATH,'arm'),arm); end
if overwrite, copyfile(fullfile(MTA_PATH,'web'),web); end


% final path layout
%
% ../projectPath/config/
% ../projectPath/config/MTA
% ../projectPath/config/MTA/arm
% ../projectPath/config/MTA/web
%
% ../MTA_PROJECT_PATH/analysis
% ../MTA_PROJECT_PATH/analysis/models
% ../MTA_PROJECT_PATH/matlab
% ../MTA_PROJECT_PATH/matlab/classifiers



% LIST standard marker names
MTAMarkers ={'hip_right','pelvis_root','hip_left','spine_lower','knee_left',...
             'knee_right','tail_base','tail_end','spine_middle','spine_upper',...
             'head_back','head_left','head_front','head_right','shoulder_left',...
             'elbow_left','shoulder_right','elbow_right','head_top',...
             'Head','Body','Arena','Pelvis','Torso'};

% LIST standard mazes  
MTAMazes = {{'cof','circle',   [-500,500;-500,500;0,300],       ... visual volume
                               [-500,500;-500,500;0,360]},      ... computational volume
            {'chr','circle',   [-500,500;-500,500;0,300],       ... width,length,height
                               [-500,500;-500,500;0,360]},      ... width,length,height
            {'cpm','circle',   [-1000,1000;-1000,1000;-100,500],                          ...
                               [-1000,1000;-1000,1000;-100,500]},                         ...
            {'cpf','circle',   [-1000,1000;-1000,1000;-100,500],                          ...
                               [-1000,1000;-1000,1000;-100,500]},                         ...
            {'hcf','rectangle',[-500,500;-500,500;0,300],                                 ...
                               [-500,500;-500,500;0,360]},                                ...
            {'nor','circle',   [-500,500;-500,500;0,300],                                 ...
                               [-500,500;-500,500;0,360]},                                ...
            {'odr','W',        [-500,500;-500,500;0,300],                                 ...
                               [-500,500;-500,500;0,360]},                                ...
            {'cot','circle',   [-500,500;-500,500;0,300],                                 ...
                               [-500,500;-500,500;0,360]},                                ...
            {'ont','circle',   [-500,500;-500,500;0,300],                                 ...
                               [-500,500;-500,500;0,360]},                                ...
            {'sof','square',   [-700,700;-700,700;0,1000],                                ...
                               [-700,700;-700,700;0,1000]},                               ...
            {'sov','square',   [-700,700;-700,700;0,1000],                                ...
                               [-700,700;-700,700;0,1000]},                               ...
            {'spb','square',   [-700,700;-700,700;-100,500],                              ...
                               [-700,700;-700,700;-100,500]},                             ...
            {'vrr','rectangle',[-500,500;-1000,1000;-100,500],                              ...
                               [-500,500;-1000,1000;-100,500]},                             ...
            {'shr','rectangle',[-300,500;-300,300;0,300],                                 ...
                               [-300,300;-300,300;0,360]},                                ...
            ... %{'rof','rectangle',[-1100,1100;-600,600;0,400],[-1100,1100;-600,600;0,400]},...
            {'rov','rectangle',[-800,800;-500,500;0,300],                                 ...
                               [-600,600;-350,350;0,300]},                                ...
            {'vre','rectangle',[-800,800;-500,500;0,300],                                 ...
                               [-600,600;-350,350;0,300]},                                ...
            {'tfr','rectangle',[-800,800;-500,500;-100,300],                              ...
                               [-800,800;-500,500;-100,300]},                             ...
            {'frr','rectangle',[-700,700;-600,600;-100,300],                              ...
                               [-700,700;-600,600;-100,300]},                             ...
            {'ofr','rectangle',[-700,700;-600,600;-100,300],                              ...
                               [-700,700;-600,600;-100,300]},                             ...
            {'orr','rectangle',[-700,700;-600,600;-100,300],                              ...
                               [-700,700;-600,600;-100,300]},                             ...
            {'rof','rectangle',[-700,700;-600,600;-100,300],                              ...
                               [-700,700;-600,600;-100,300]},                             ...
            {'lin','line',     [-1400,1400;-300,300;-100,300],                              ...
                               [-1400,1400;-300,300;-100,300]},                             ...
            {'tm','circle',    [-500,500;-500,500;0,300],                                 ...
                               [-500,500;-500,500;0,360]}};

%% LIST standard connections between markers
MTAMarkerConnections = ...
          {{'head_front','head_left' },...
           {'head_front','head_right'},...
           {'head_right','head_left' },...
           {'head_left' ,'head_back' },...
           {'head_right','head_back' },...
           {'head_back' ,'spine_upper'},...
           {'spine_upper','shoulder_right'},...
           {'spine_upper','shoulder_left' },...
           {'spine_upper','spine_middle'  },...
           {'spine_middle','pelvis_root'  },...
           {'pelvis_root', 'hip_right'  },...
           {'pelvis_root', 'hip_left'   },...
           {'pelvis_root', 'spine_lower'},...
           {'spine_lower', 'hip_right'  },...
           {'spine_lower', 'hip_left'},...
           {'hip_left','hip_right'},...
           {'hip_left','knee_left'},...
           {'hip_right','knee_right'},...
           {'head_top','head_front'},...
           {'head_top','head_left'},...
           {'head_top','head_right'},...
           {'head_top','head_back'}, ...
           {'tail_proximal','spine_lower'}};

%% Save configuations

% conf is obsolete - remove in future version
if overwrite || ~exist(fullfile(cfg, 'MTAConf.mat'),'file'),
    save(fullfile(cfg, 'MTAConf.mat'  ),'project_name','host_server','data_server');end

if overwrite || ~exist(fullfile(cfg, 'MTAPaths.mat'),'file'),
    save(fullfile(cfg, 'MTAPaths.mat'),'data','cfg','project','arm','web');end

if overwrite || ~exist(fullfile(cfg, 'MTAMarkers.mat'),'file'),
    save(fullfile(cfg, 'MTAMarkers.mat'),'MTAMarkers');end

if overwrite || ~exist(fullfile(cfg, 'MTAMazes.mat'),'file'),
    save(fullfile(cfg, 'MTAMazes.mat'),'MTAMazes');
end

if overwrite || ~exist(fullfile(cfg, 'MTAMarkerConnections.mat'),'file'),
    save(fullfile(cfg, 'MTAMarkerConnections.mat'),'MTAMarkerConnections');
end
    

addpath(genpath(cfg));

