function Data = update_hash(Data,varargin)
% function Data = update_hash(Data,varargin)
% 
% 
%
% varargin:
%    modificationHash: String(hash)
%    

if isempty(varargin),
    modificationHash = [];
else
    modificationHash = varargin{1};
end

Data.hash = DataHash({Data.filename  ,...
                      Data.name      ,...
                      Data.label     ,...
                      Data.key       ,...
                      Data.ext       ,...
                      Data.sampleRate,...
                      Data.sync      ,...
                      Data.origin    ,...
                      modificationHash});