function parspec = def_spec_parm(fet,varargin)
%     parspec = struct('nFFT',[],...
%                      'Fs',  [],...
%                      'WinLength',[],...
%                      'nOverlap',[],...
%                      'NW',[],...
%                      'Detrend',[],...
%                      'nTapers',[],...
%                      'FreqRange',[]);


%[mode] = DefaultArgs(varargin,{'high'},true);

parspec = empty_spec;
if any(~cellfun(@isempty,regexp(fet.ext,{'ang','pos'})))

    
    parspec = struct('nFFT',2^9,...
                     'Fs',  fet.sampleRate,...
                     'WinLength',2^7,...
                     'nOverlap',2^7*.875,...
                     'NW',[],...
                     'Detrend',[],...
                     'nTapers',[],...
                     'FreqRange',[1,50]);


elseif strcmpi('lfp',fet.ext)

% $$$     switch mode
% $$$       case 'high'
% $$$         nfft = 2^9;
% $$$       case 'low'
% $$$         nfft = 2^8;
% $$$     end

    parspec = struct('nFFT',2^11,...
                     'Fs',  fet.sampleRate,...
                     'WinLength',2^10,...
                     'nOverlap',2^10*.875,...
                     'NW',[],...
                     'Detrend',[],...
                     'nTapers',[],...
                     'FreqRange',[1,50]);
    
end