function parspec = empty_spec

parspec = struct('nFFT',[],...
                   'Fs',  [],...
                   'WinLength',[],...
                   'nOverlap',[],...
                   'NW',[],...
                   'Detrend',[],...
                   'nTapers',[],...
                   'FreqRange',[]);
