function Sessions = get_session_list(varargin)
%function Sessions = get_session_list(varargin)
%[Seslist,my_xyz,my_nlx] = DefaultArgs(varargin,{'all_Sessions',...
%                          '/gpfs01/sirota/home/gravio/data/xyz/',...
%                          '/gpfs01/sirota/home/gravio/data/nlx/'});

if isstruct(varargin{1}),
    Sessions = varargin{1};
    return
end


prjPath_xyz = '';
prjPath_nlx = '';

datPath = getenv('PROJECT');
if ~isempty(datPath),
    prjPath_xyz = fullfile(datPath,'data','processed','xyz');
    prjPath_nlx = fullfile(datPath,'data','processed','nlx');
end


[Seslist,my_xyz,my_nlx] = DefaultArgs(varargin,{'all_Sessions',...
                          prjPath_xyz,...
                          prjPath_nlx});

path = load('MTAPaths.mat');

switch varargin{1}

  case 'er01'
    Sessions(1) = struct('sessionName',      'er01-20110719',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x4000'...
                         );
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'er01-20110721';
    
  case 'test_grp'
    Sessions(1)     = struct('sessionName',      'er01-20110721',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x4000'...
                         );
    Sessions(end+1) = struct('sessionName',      'jg04-20120129',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x4000'...
                         );
    Sessions(end+1) = struct('sessionName',      'jg04-20120130',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x4000'...
                         );
    Sessions(end+1) = struct('sessionName',      'jg05-20120309',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x0040'...
                         );
    Sessions(end+1) = struct('sessionName',      'jg05-20120310',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x0040'...
                         );
    Sessions(end+1) = struct('sessionName',      'jg05-20120317',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x0040'...
                         );

  case 'jg05-20120311'
    my_xyz = fullfile(my_xyz,'jg05');    
    Sessions(1) = struct('sessionName',   'jg05-20120311',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x0040'...
                         );

  case 'jg05-20120311.cof.all'
    my_xyz = fullfile(my_xyz,'jg05');    

    Sessions(1) = struct('sessionName',  'jg05-20120311', ...
                         'mazeName',     'cof',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 119.881035,     ...
                         'host',         'lmu',           ...
                         'project',      'general',       ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[],             ...
                         'offsets',       [15,0],         ...
                         'xOffSet',       0,              ...
                         'yOffSet',       0,              ...
                         'stcMode',      'default'        ...
    );
  case 'jg05-20120311.cof.spk'
    my_xyz = fullfile(my_xyz,'jg05');    

    Sessions(1) = struct('sessionName',  'jg05-20120311', ...
                         'mazeName',     'cof',           ...
                         'trialName',    'spk',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 119.881035,     ...
                         'host',         'lmu',           ...
                         'project',      'general',       ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[5:15],         ...
                         'offsets',       [15,0],         ...
                         'xOffSet',       0,              ...
                         'yOffSet',       0,              ...
                         'stcMode',      'default'        ...
    );
    

  case 'jg05'

    my_xyz = fullfile(my_xyz,'jg05');
    
    Sessions(1)     = struct('sessionName',      'jg05-20120309',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x0040'...
                         );
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg05-20120310';
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg05-20120311';
% $$$     Sessions(end+1) = Sessions(1);
% $$$     Sessions(end).sessionName = 'jg05-20120315';
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg05-20120317';


  case 'MjgEdER2016_bhv'
    tmy_nlx = my_nlx;
    tmy_xyz = my_xyz;
    
    % jg05 sessions
    my_xyz = fullfile(tmy_xyz,'jg05');    
    Sessions(1) = struct('sessionName',   'jg05-20120309',    ...
                         'mazeName',      'cof',              ...
                         'trialName',     'all',              ...
                         'xyz_host',      my_xyz,             ...
                         'nlx_host',      my_nlx,             ...
                         'xyzSampleRate', 119.881035,         ...
                         'host',          'lmu',              ...
                         'project',      'general',           ...
                         'TTLValue',      '0x0040',           ...
                         'includeSyncInd',[],                 ...
                         'offsets',       [15,-15],           ...
                         'xOffSet',       0,                  ...
                         'yOffSet',       0,                  ...
                         'stcMode',      'default'            ...
                         );
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg05-20120310';
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg05-20120311';
% $$$     Sessions(end+1) = Sessions(1);
% $$$     Sessions(end).sessionName = 'jg05-20120315';
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg05-20120317';

    
    % Ed10 sessions
    my_xyz = fullfile(tmy_xyz,'Ed10');
    my_nlx = '/storage/eduardo/data/processed/nlx/Ed10';

    Sessions(end+1) = struct('sessionName',  'Ed10-20140817', ...
                             'mazeName',     'cof',           ...
                             'trialName',    'gnd',           ...
                             'xyz_host',      my_xyz,         ...
                             'nlx_host',      my_nlx,         ...
                             'xyzSampleRate', 119.881035,     ...
                             'host',         'lmu',           ...
                             'project',      'general',       ...
                             'TTLValue',     '0x0002',        ...
                             'includeSyncInd',[1:7],          ...
                             'offsets',       [15,-15],       ...
                             'xOffSet',       0,              ...
                             'yOffSet',       0,              ...
                             'stcMode',      'default'        ...
                             );

    Sessions(end+1) = Sessions(end);
    Sessions(end).trialName = 'dark';
    Sessions(end).includeSyncInd = [1:3];

    Sessions(end+1) = Sessions(end);
    Sessions(end).trialName = 'light';
    Sessions(end).includeSyncInd = [4:6];

    Sessions(end+1) = Sessions(end);
    Sessions(end).trialName = 'nodor';
    Sessions(end).includeSyncInd = [7];

    
    % ER06 sessions
    my_xyz = fullfile(tmy_xyz,'ER06');
    my_nlx = '/storage/evgeny/data/processed/ER06';    
    Sessions(end+1) = struct('sessionName','ER06-20130613',   ...
                         'mazeName',     'cof',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',       ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[1,2,5,6,9,10], ...
                         'offsets',       [0,0],          ...
                         'xOffSet',       0,              ...
                         'yOffSet',       0,              ...
                         'stcMode',      'default'        ...
    );
      
    Sessions(end+1) = struct('sessionName', 'ER06-20130614',  ...
                         'mazeName',     'cof',           ...
                         'trialName',    'gnd',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',       ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[1:3,6:8,11,12],...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       0,              ...
                         'yOffSet',       0,              ...
                         'stcMode',      'default'        ...
     );
      

    
    
  
  case 'all_Sessions'     % SessionName      MazeName   TrialName   Host    TTLValue        
    Sessions = {...
                {'er01-20110719',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...  CA3
                {'er01-20110721',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...  CA3
                {'er06-20130612',     'cof',     'all',    'lmu',  'Vicon start', 199.997752},... CA1
                {'er06-20130613',     'cof', 'all-cof',    'lmu',  'Vicon start', 199.997752},... CA1
                {'er06-20130614',     'cof', 'all-cof',    'lmu',  'Vicon start', 199.997752},... CA1
                {'jg04-20120129',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...  CA1
                {'jg04-20120130',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...  CA1
                {'jg05-20120309',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                {'jg05-20120310',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                {'jg05-20120311',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                {'jg05-20120315',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                {'jg05-20120317',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA2???
                {'jg05-20120324',     'cof',     'all',   'lmu',  '0x0040',      119.881035}}; %  CA3

  case 'pfs'     % SessionName      MazeName   TrialName   Host    TTLValue        SampleRate
    Sessions = {...
                ... %{'er01-20110719',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...  CA3
                {'er06-20130612',     'cof',     'all',    'lmu',  'Vicon start', 199.997752},... CA1
                ... %{'er06-20130613',     'cof', 'all-cof',    'lmu',  'Vicon start', 199.997752},... CA1
                {'er06-20130614',     'cof', 'all-cof',    'lmu',  'Vicon start', 199.997752},... CA1
                ... %{'jg04-20120129',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...  CA1
                ... %{'jg04-20120130',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...  CA1
                {'jg05-20120309',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                {'jg05-20120310',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                ... %{'jg05-20120315',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                {'jg05-20120317',     'cof',     'all',   'lmu',  '0x0040',      119.881035}};...  CA2???
    %{'jg05-20120324',     'cof',     'all',   'lmu',  '0x0040',      119.881035}}; %  CA3

  case 'ncpH5B4'
    Sessions = {{'Ed01-20140707',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                {'Ed01-20140709',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                {'Ed01-20140717',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                                                                                             ...
                {'Ed03-20140623',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                {'Ed03-20140624',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...
                {'Ed03-20140625',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...
                                                                                             ... 
                {'Ed05-20140528',     'cof',     'all',   'lmu',  '0x0010',      119.881035},... 
                {'Ed05-20140529',     'ont',     'all',   'lmu',  '0x0010',      119.881035}}; % 
                                                                                               
% $$$   case 'hand_labeled'
% $$$     Sessions = {{'er01-20110719',     'cof',     'all',   'lmu',  '0x4000',      119.881035},...
% $$$                 {'jg05-20120317',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...
% $$$                 {'Ed01-20140707',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
% $$$                 {'Ed03-20140624',     'cof',     'all',   'lmu',  '0x0002',      119.881035}}; % 
                                                                                               
  case 'req20151009'
    Sessions = {{'jg05-20120317',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...  CA1
                {'Ed01-20140707',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                {'Ed01-20140709',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                {'Ed01-20140717',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                                                                                             ...
                {'Ed03-20140623',     'cof',     'all',   'lmu',  '0x0002',      119.881035},... 
                {'Ed03-20140624',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...
                {'Ed03-20140625',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...
                                                                                             ... 
                {'Ed05-20140528',     'cof',     'all',   'lmu',  '0x0010',      119.881035},... 
                {'Ed05-20140529',     'ont',     'all',   'lmu',  '0x0010',      119.881035}}; % 
                                                                                               
  case 'req20151203'
    Sessions = {{'jg05-20120309',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...
                {'jg05-20120310',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...
                {'jg05-20120311',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...
                {'jg05-20120324',     'cof',     'all',   'lmu',  '0x0040',      119.881035},...
                {'jg05-20120325',     'cof',     'all',   'lmu',  '0x0040',      119.881035}}; % 

  case 'Ed10'
    Sessions = {{'Ed10-20140812',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140813',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140814',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140815',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140816',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140817',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140818',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140819',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1 
                ...
                {'Ed10-20140820',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1              
                {'Ed10-20140820',     'shr',     'all',   'lmu',  '0x0002',      119.881035},...  CA1            
                {'Ed10-20140820',     'rov',     'all',   'lmu',  '0x0002',      149.9974321},... CA1
                ...
                {'Ed10-20140821',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1              
                {'Ed10-20140821',     'shr',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140821',     'shv',     'all',   'lmu',  '0x0002',      149.9974321},... CA1              
                {'Ed10-20140821',     'rov',     'all',   'lmu',  '0x0002',      149.9974321},... CA1              
                ...
                {'Ed10-20140822',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1             
                {'Ed10-20140822',     'shr',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140822',     'shv',     'all',   'lmu',  '0x0002',      149.9974321},... CA1              
                {'Ed10-20140822',     'rov',     'all',   'lmu',  '0x0002',      149.9974321},... CA1             
                ...
                {'Ed10-20140823',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1             
                {'Ed10-20140823',     'shr',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140823',     'rov',     'all',   'lmu',  '0x0002',      149.9974321},... CA1              
                ...
                {'Ed10-20140824',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1             
                {'Ed10-20140824',     'shr',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                ...
                {'Ed10-20140825',     'cof',     'all',   'lmu',  '0x0002',      119.881035},...  CA1              
                {'Ed10-20140825',     'mem',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140825',     'shr',     'all',   'lmu',  '0x0002',      119.881035},...  CA1
                {'Ed10-20140825',     'shv',     'all',   'lmu',  '0x0002',      149.9974321},... CA1              
                {'Ed10-20140825',     'rov',     'all',   'lmu',  '0x0002',      149.9974321}}%   CA1
    

    
    
  case 'ER06'

    my_xyz = fullfile(my_xyz,'ER06');
    my_nlx = '/storage/evgeny/data/processed/ER06';

    Sessions(1) = struct('sessionName',  'ER06-20130611', ...
                         'mazeName',     'cof',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',        ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[],             ...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -40,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName','ER06-20130612', ...
                         'mazeName',     'cof',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',        ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[],             ...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -40,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName','ER06-20130613', ...
                         'mazeName',     'cof',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',       ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[1,2,5,6,9,10], ...
                         'offsets',       [0,0],       ...
                         'xOffSet',       0,            ...
                         'yOffSet',       0,            ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName','ER06-20130614', ...
                         'mazeName',     'cof',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',        ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[],             ...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       0,            ...
                         'yOffSet',       0,           ...
                         'stcMode',      'default'        ...
    );

  case 'ER06_BHV'
    Sessions(1) = struct('sessionName','ER06-20130613',   ...
                         'mazeName',     'cof',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',       ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[1,2,5,6,9,10], ...
                         'offsets',       [0,0],          ...
                         'xOffSet',       0,              ...
                         'yOffSet',       0,              ...
                         'stcMode',      'default'        ...
    );
      
    Sessions(end+1) = struct('sessionName', 'ER06-20130614',  ...
                         'mazeName',     'cof',           ...
                         'trialName',    'gnd',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 199.997752,     ...
                         'host',         'lmu',           ...
                         'project',      'general',       ...
                         'TTLValue',     'Vicon start',   ...
                         'includeSyncInd',[1:3,6:8,11,12],...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       0,              ...
                         'yOffSet',       0,              ...
                         'stcMode',      'default'        ...
     );
      


  case 'exp_flight'
      Sessions(1) = struct('sessionName', 'ER06-20130614',  ...
      'mazeName',     'cof',           ...
      'trialName',    'gnd',           ...
      'xyz_host',      my_xyz,         ...
      'nlx_host',      my_nlx,         ...
      'xyzSampleRate', 199.997752,     ...
      'host',         'lmu',           ...
      'project',      'general',       ...
      'TTLValue',     'Vicon start',   ...
      'includeSyncInd',[1:3,6:8,11,12],...
      'offsets',       [15,-15],       ...
      'xOffSet',       0,              ...
      'yOffSet',       0,              ...
      'stcMode',      'default'        ...
      );
      
      Sessions(end+1) = struct('sessionName',  'ER06-20130614', ...
      'mazeName',     'cof',           ...
      'trialName',    'fly',           ...
      'xyz_host',      my_xyz,         ...
      'nlx_host',      my_nlx,         ...
      'xyzSampleRate', 199.997752,     ...
      'host',         'lmu',           ...
      'project',      'general',       ...
      'TTLValue',     'Vicon start',   ...
      'includeSyncInd',[15,16],        ...
      'offsets',       [15,-15],       ...
      'xOffSet',       0,              ...
      'yOffSet',       0,              ...
      'stcMode',      'default'        ...
      );

      
      
  case 'Ed10_cof'

    my_xyz = fullfile(my_xyz,'Ed10');
    my_nlx = '/storage/eduardo/data/processed/nlx/Ed10';

    Sessions(1) = struct('sessionName',  'Ed10-20140812', ...
        'mazeName',     'cof',           ...
        'trialName',    'all',           ...
        'xyz_host',      my_xyz,         ...
        'nlx_host',      my_nlx,         ...
        'xyzSampleRate', 119.881035,     ...
        'host',         'lmu',           ...
        'project',      'general',       ...
        'TTLValue',     '0x0002',        ...
        'includeSyncInd',[],             ...
        'offsets',       [15,-15],       ...
        'xOffSet',       0,              ...
        'yOffSet',       0,              ...
        'stcMode',      'default'        ...
        );

    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'Ed10-20140813';

    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'Ed10-20140814';

    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140815';

    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140816';

    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140817';
    
    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140819';

    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140820';

    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140821';
    
    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140822';
    
    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140823';
    
    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140824';
    
    Sessions(end+1) = Sessions(1);    
    Sessions(end).sessionName = 'Ed10-20140825';

  case 'Ed10_BHV'

    my_xyz = fullfile(my_xyz,'Ed10');
    my_nlx = '/storage/eduardo/data/processed/nlx/Ed10';

    Sessions(1) = struct('sessionName',  'Ed10-20140812', ...
        'mazeName',     'cof',           ...
        'trialName',    'all',           ...
        'xyz_host',      my_xyz,         ...
        'nlx_host',      my_nlx,         ...
        'xyzSampleRate', 119.881035,     ...
        'host',         'lmu',           ...
        'project',      'general',       ...
        'TTLValue',     '0x0002',        ...
        'includeSyncInd',[],             ...
        'offsets',       [15,-15],       ...
        'xOffSet',       0,              ...
        'yOffSet',       0,              ...
        'stcMode',      'default'        ...
        );

    
  case 'Ed10_darklight'

    my_xyz = fullfile(my_xyz,'Ed10');
    my_nlx = '/storage/eduardo/data/processed/nlx/Ed10';

    Sessions(1) = struct('sessionName',  'Ed10-20140817', ...
        'mazeName',     'cof',           ...
        'trialName',    'dark',           ...
        'xyz_host',      my_xyz,         ...
        'nlx_host',      my_nlx,         ...
        'xyzSampleRate', 119.881035,     ...
        'host',         'lmu',           ...
        'project',      'general',       ...
        'TTLValue',     '0x0002',        ...
        'includeSyncInd',[1:3],             ...
        'offsets',       [15,-15],       ...
        'xOffSet',       0,              ...
        'yOffSet',       0,              ...
        'stcMode',      'default'        ...
        );

    Sessions(end+1) = Sessions(1);
    Sessions(end).trialName = 'light';
    Sessions(end).includeSyncInd = [4:6];
    

  case 'Ed10VR_opticflow'
    Sessions(1) = struct('sessionName',   'Ed10-20140821',...
                         'mazeName',      'rov',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [],...
                         'offsets',       [7,-7]...
                         );
      
    Sessions(end+1) = struct('sessionName',   'Ed10-20140821',...
                             'mazeName',      'rov',...
                             'trialName',     'of1x1',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'project',       'vr_exp',...
                             'TTLValue',      '0x0002',...
                             'includeSyncInd', [1],...
                             'offsets',       [7,-7]...
                             );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140821',...
                             'mazeName',      'rov',...
                             'trialName',     'of2x2',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'project',       'vr_exp',...
                             'TTLValue',      '0x0002',...
                             'includeSyncInd', [2],...
                             'offsets',       [7,-7]...
                             );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140821',...
                             'mazeName',      'rov',...
                             'trialName',     'of1x3',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'project',       'vr_exp',...
                             'TTLValue',      '0x0002',...
                             'includeSyncInd',[3],...
                             'offsets',       [7,-7]...
                             );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140821',...
                             'mazeName',      'rov',...
                             'trialName',     'of12x4',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'project',       'vr_exp',...
                             'TTLValue',      '0x0002',...
                             'includeSyncInd',[4],...
                             'offsets',       [7,-7]...
                             );

  case 'Ed10VR_20160823'
    Sessions(1) = struct('sessionName',  'Ed10-20140823', ...
                         'mazeName',     'rov',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 149.9974321,    ...
                         'host',         'lmu',           ...
                         'project',      'vr_exp',        ...
                         'TTLValue',     '0x0002',        ...
                         'includeSyncInd',[],             ...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140823',...
                         'mazeName',      'rov',...
                         'trialName',     'tel_C1',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [1],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140823',...
                         'mazeName',      'rov',...
                         'trialName',     'tel_S1',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [2],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140823',...
                         'mazeName',      'rov',...
                         'trialName',     'stf',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [3],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );

  case 'Ed10_20140822.rov'
    Sessions(1) = struct('sessionName',  'Ed10-20140822', ...
                         'mazeName',     'rov',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 149.9974321,    ...
                         'host',         'lmu',           ...
                         'project',      'vr_exp',        ...
                         'TTLValue',     '0x0002',        ...
                         'includeSyncInd',[],             ...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140822',...
                         'mazeName',      'rov',...
                         'trialName',     'stf',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [1,2,5],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140822',...
                         'mazeName',      'rov',...
                         'trialName',     'vobj',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [3,4],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140822',...
                         'mazeName',      'rov',...
                         'trialName',     'blk',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [6],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140822',...
                         'mazeName',      'rov',...
                         'trialName',     'fly',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [7],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    
  case 'Ed10VR_teleport'
    Sessions(1) = struct('sessionName',  'Ed10-20140820', ...
                         'mazeName',     'rov',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 149.9974321,    ...
                         'host',         'lmu',           ...
                         'project',      'vr_exp',        ...
                         'TTLValue',     '0x0002',        ...
                         'includeSyncInd', [],            ...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'tel_C1',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [1],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'tel_S1',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [2],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
                         );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'tel_C2',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [3],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
                         );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'tel_S2',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [4],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
                         );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'tel_A1',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...    
                         'includeSyncInd', [5],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
                         );

  case 'Ed10VR_teleport_com'
    Sessions(1) = struct('sessionName',  'Ed10-20140820', ...
                         'mazeName',     'rov',           ...
                         'trialName',    'all',           ...
                         'xyz_host',      my_xyz,         ...
                         'nlx_host',      my_nlx,         ...
                         'xyzSampleRate', 149.9974321,    ...
                         'host',         'lmu',           ...
                         'project',      'vr_exp',        ...
                         'TTLValue',     '0x0002',        ...
                         'includeSyncInd', [],            ...
                         'offsets',       [15,-15],       ...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'Ctel_C',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [1,3],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    Sessions(end+1) = struct('sessionName',   'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'Ctel_S',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'project',       'vr_exp',...
                         'TTLValue',      '0x0002',...
                         'includeSyncInd', [2,4],...
                         'offsets',       [15,-15],...
                         'xOffSet',       -70,            ...
                         'yOffSet',       -325,           ...
                         'stcMode',      'default'        ...
    );
    
  case 'Ed10VR'
    Sessions(1) = struct('sessionName',          'Ed10-20140820',...
                         'mazeName',      'rov',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 149.9974321,...
                         'host',          'lmu',...
                         'TTLValue',      '0x0002'...
                         );
    Sessions(end+1) = struct('sessionName',          'Ed10-20140821',...
                             'mazeName',      'rov',...
                             'trialName',     'all',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'TTLValue',      '0x0002'...
                             );
    Sessions(end+1) = struct('sessionName',          'Ed10-20140822',...
                             'mazeName',      'rov',...
                             'trialName',     'all',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'TTLValue',      '0x0002'...
                             );
    Sessions(end+1) = struct('sessionName',          'Ed10-20140823',...
                             'mazeName',      'rov',...
                             'trialName',     'all',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'TTLValue',      '0x0002'...
                             );
    Sessions(end+1) = struct('sessionName',          'Ed10-20140825',...
                             'mazeName',      'rov',...
                             'trialName',     'all',...
                             'xyz_host',      my_xyz,...
                             'nlx_host',      my_nlx,...
                             'xyzSampleRate', 149.9974321,...
                             'host',          'lmu',...
                             'TTLValue',      '0x0002'...
                             );
    
  case 'mypc_test_grp'
      
    Sessions(1)     = struct('sessionName',      'Ed01-20140707',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          data_host,...
                         'TTLValue',      '0x0002'...
                         );

    Sessions(end+1) =    Sessions(1);
    Session(end).sessionName = 'Ed01-20140709';

    Sessions(end+1) =    Sessions(1);
    Session(end).sessionName = 'Ed03-20140624';

    Sessions(end+1) =    Sessions(1);
    Session(end).sessionName = 'Ed03-20140624';

    Sessions(end+1) =    Sessions(1);
    Session(end).sessionName = 'Ed03-20140625';

    Sessions(end+1) =    Sessions(1);
    Session(end).sessionName = 'Ed05-20140528'
    Session(end).TTLValue    = '0x0010';

    Sessions(end+1) =    Sessions(end);
    Session(end).sessionName = 'Ed05-20140529';
    Session(end).mazeName    = 'ont';

    Sessions(end+1) =    Sessions(1);
    Session(end).sessionName = 'jg05-20120309';
    Session(end).TTLValue    = '0x0040';

    Sessions(end+1) =    Sessions(end);
    Session(end).sessionName = 'jg05-20120310';

    Sessions(end+1) =    Sessions(end);
    Session(end).sessionName = 'jg05-20120317';

  case 'jg04'
    my_xyz = fullfile(my_xyz,'jg04');
    Sessions(1) = struct('sessionName',   'jg04-20120128',...
                         'mazeName',      'cof',...
                         'trialName',     'all',...
                         'xyz_host',      my_xyz,...
                         'nlx_host',      my_nlx,...
                         'xyzSampleRate', 119.881035,...
                         'host',          'lmu',...
                         'TTLValue',      '0x4000'...
                         );
    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg04-20120129';

    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg04-20120130';

    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg04-20120201';

    Sessions(end+1) = Sessions(1);
    Sessions(end).sessionName = 'jg04-20120203';


  case 'training_hand_labeled'
    data_host = 'lmu';
      
    Sessions(1) = ...
        struct('sessionName',   'jg05-20120317',...          
               'mazeName',      'cof',...                              
               'trialName',     'all',...                              
               'xyz_host',      my_xyz,...                             
               'nlx_host',      fullfile(my_nlx,'jg05'),...            
               'xyzSampleRate', 119.881035,...                         
               'host',          data_host,...                         
               'stcMode',       'hand_labeled_rev3_jg',...               
               'TTLValue',      '0x0040'...                           
    );
    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140625',...                            
               'mazeName',      'cof',...                                                    
               'trialName',     'all',...                                                    
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...                                               
               'host',          data_host,...                                                
               'stcMode',       'hand_labeled_rev1_Ed',...                                  
               'TTLValue',      '0x0002'...                                    
    );
    

    
    
  case 'hand_labeled'
    data_host = 'lmu';
      
    Sessions(1) = ...
        struct('sessionName',   'jg05-20120317',...          
               'mazeName',      'cof',...                              
               'trialName',     'all',...                              
               'xyz_host',      my_xyz,...                             
               'nlx_host',      fullfile(my_nlx,'jg05'),...            
               'xyzSampleRate', 119.881035,...                         
               'host',          data_host,...                         
               'stcMode',       'hand_labeled_rev3_jg',...               
               'TTLValue',      '0x0040'...                           
    );

    Sessions(end+1) = ...
        struct('sessionName',   'er01-20110719',...         
               'mazeName',      'cof',...                                 
               'trialName',     'all',...                                 
               'xyz_host',      my_xyz,...                                
               'nlx_host',      fullfile(my_nlx,'er01'),...               
               'xyzSampleRate', 119.881035,...                            
               'host',          data_host,...                             
               'stcMode',       'hand_labeled_rev2_jg', ...                   
               'TTLValue',      '0x4000'...                               
    );
    
    Sessions(end+1) = ...
        struct('sessionName',   'Ed01-20140707',...
               'mazeName',      'cof',...     
               'trialName',     'all',...               
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...          
               'host',          data_host,...           
               'stcMode',       'hand_labeled_rev2_jg',...                                  
               'TTLValue',      '0x0002'...             
    );

    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140624',...                            
               'mazeName',      'cof',...                                                    
               'trialName',     'all',...                                                    
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...                                               
               'host',          data_host,...                                                
               'stcMode',       'hand_labeled_rev1_jg',...                                  
               'TTLValue',      '0x0002'...                                    
    );
    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140625',...                             
               'mazeName',      'cof',...                                                     
               'trialName',     'all',...                                                     
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                     
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...                
               'xyzSampleRate', 119.881035,...                                                
               'host',          data_host,...                                                 
               'stcMode',       'hand_labeled_rev1_Ed',...                                       
               'TTLValue',      '0x0002'...                                                   
    );
    
    Sessions(end+1) = ...
        struct('sessionName',   'Ed05-20140529',...
               'mazeName',      'ont',...                                      
               'trialName',     'all',...                                      
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...      
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed05',... 
               'xyzSampleRate', 119.881035,...                                 
               'host',          data_host,...                                  
               'stcMode',       'hand_labeled_rev1_Ed',...                        
               'TTLValue',      '0x0010'...                                    
    );
    
    
  case 'hand_labeled_jg'
    data_host = 'lmu';
      
    Sessions(1) = ...
        struct('sessionName',   'jg05-20120317',...          
               'mazeName',      'cof',...                              
               'trialName',     'all',...                              
               'xyz_host',      my_xyz,...                             
               'nlx_host',      fullfile(my_nlx,'jg05'),...            
               'xyzSampleRate', 119.881035,...                         
               'host',          data_host,...                         
               'stcMode',       'hand_labeled_rev3_jg',...               
               'TTLValue',      '0x0040'...                           
    );

    Sessions(end+1) = ...
        struct('sessionName',   'er01-20110719',...         
               'mazeName',      'cof',...                                 
               'trialName',     'all',...                                 
               'xyz_host',      my_xyz,...                                
               'nlx_host',      fullfile(my_nlx,'er01'),...               
               'xyzSampleRate', 119.881035,...                            
               'host',          data_host,...                             
               'stcMode',       'hand_labeled_rev2_jg', ...                   
               'TTLValue',      '0x4000'...                               
    );
      
    Sessions(end+1) = ...
        struct('sessionName',      'Ed01-20140707',...
               'mazeName',      'cof',...     
               'trialName',     'all',...               
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...          
               'host',          data_host,...           
               'stcMode',       'hand_labeled_rev2_jg',...                                  
               'TTLValue',      '0x0002'...             
    );

    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140624',...                            
               'mazeName',      'cof',...                                                    
               'trialName',     'all',...                                                    
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...                                               
               'host',          data_host,...                                                
               'stcMode',       'hand_labeled_rev1_jg',...
               'TTLValue',      '0x0002'...                                    
    );
    
    
  case 'hand_labeled_Ed'
    data_host = 'lmu';
    Sessions(1) = ...
        struct('sessionName',   'Ed01-20140707',...
               'mazeName',      'cof',...     
               'trialName',     'all',...               
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...          
               'host',          data_host,...           
               'stcMode',       'hand_labeled_rev2_Ed',...                                  
               'TTLValue',      '0x0002'...             
    );

    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140624',...                            
               'mazeName',      'cof',...                                                    
               'trialName',     'all',...                                                    
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...                                               
               'host',          data_host,...                                                
               'stcMode',       'hand_labeled_rev1_Ed',...                                  
               'TTLValue',      '0x0002'...                                    
    );
    
    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140625',...                             
               'mazeName',      'cof',...                                                     
               'trialName',     'all',...                                                     
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                     
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...                
               'xyzSampleRate', 119.881035,...                                                
               'host',          data_host,...                                                 
               'stcMode',       'hand_labeled_rev1_Ed',...                                       
               'TTLValue',      '0x0002'...                                                   
    );
    
    Sessions(end+1) = ...
        struct('sessionName',   'Ed05-20140529',...
               'mazeName',      'ont',...                                      
               'trialName',     'all',...                                      
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...      
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed05',... 
               'xyzSampleRate', 119.881035,...                                 
               'host',          data_host,...                                  
               'stcMode',       'hand_labeled_rev1_Ed',...                        
               'TTLValue',      '0x0010'...                                    
    );

    
    
  case 'training_hand_labeled_reduced'
    data_host = 'lmu';
      
    Sessions(1) = ...
        struct('sessionName',   'jg05-20120317',...          
               'mazeName',      'cof',...                              
               'trialName',     'all',...                              
               'xyz_host',      my_xyz,...                             
               'nlx_host',      fullfile(my_nlx,'jg05'),...            
               'xyzSampleRate', 119.881035,...                         
               'host',          data_host,...                         
               'stcMode',       'hl_3_jg_r',...               
               'TTLValue',      '0x0040'...                           
    );
    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140625',...                            
               'mazeName',      'cof',...                                                    
               'trialName',     'all',...                                                    
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...                                               
               'host',          data_host,...                                                
               'stcMode',       'hl_1_Ed_r',...                                  
               'TTLValue',      '0x0002'...                                    
    );
  case 'hand_labeled_jg_reduced'
    data_host = 'lmu';
      
    Sessions(1) = ...
        struct('sessionName',   'jg05-20120317',...          
               'mazeName',      'cof',...                              
               'trialName',     'all',...                              
               'xyz_host',      my_xyz,...                             
               'nlx_host',      fullfile(my_nlx,'jg05'),...            
               'xyzSampleRate', 119.881035,...                         
               'host',          data_host,...                         
               'stcMode',       'hl_3_jg_r',...               
               'TTLValue',      '0x0040'...                           
    );

    Sessions(end+1) = ...
        struct('sessionName',   'er01-20110719',...         
               'mazeName',      'cof',...                                 
               'trialName',     'all',...                                 
               'xyz_host',      my_xyz,...                                
               'nlx_host',      fullfile(my_nlx,'er01'),...               
               'xyzSampleRate', 119.881035,...                            
               'host',          data_host,...                             
               'stcMode',       'hl_2_jg_r', ...                   
               'TTLValue',      '0x4000'...                               
    );
      
    Sessions(end+1) = ...
        struct('sessionName',      'Ed01-20140707',...
               'mazeName',      'cof',...     
               'trialName',     'all',...               
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...          
               'host',          data_host,...           
               'stcMode',       'hl_2_jg_r',...                                  
               'TTLValue',      '0x0002'...             
    );

    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140624',...                            
               'mazeName',      'cof',...                                                    
               'trialName',     'all',...                                                    
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...                                               
               'host',          data_host,...                                                
               'stcMode',       'hl_1_jg_r',...
               'TTLValue',      '0x0002'...                                    
    );
    
    
  case 'hand_labeled_Ed_reduced'
    data_host = 'lmu';
    Sessions(1) = ...
        struct('sessionName',   'Ed01-20140707',...
               'mazeName',      'cof',...     
               'trialName',     'all',...               
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...          
               'host',          data_host,...           
               'stcMode',       'hl_2_Ed_r',...                                  
               'TTLValue',      '0x0002'...             
    );

    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140624',...                            
               'mazeName',      'cof',...                                                    
               'trialName',     'all',...                                                    
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                    
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...               
               'xyzSampleRate', 119.881035,...                                               
               'host',          data_host,...                                                
               'stcMode',       'hl_1_Ed_r',...                                  
               'TTLValue',      '0x0002'...                                    
    );
    
    Sessions(end+1) = ...
        struct('sessionName',   'Ed03-20140625',...                             
               'mazeName',      'cof',...                                                     
               'trialName',     'all',...                                                     
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...                     
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed03',...                
               'xyzSampleRate', 119.881035,...                                                
               'host',          data_host,...                                                 
               'stcMode',       'hl_1_Ed_r',...
               'TTLValue',      '0x0002'...                                                   
    );
    
    Sessions(end+1) = ...
        struct('sessionName',   'Ed05-20140529',...
               'mazeName',      'ont',...                                      
               'trialName',     'all',...                                      
               'xyz_host',      '/storage/eduardo/data/processed/xyz',...      
               'nlx_host',      '/storage/eduardo/data/processed/nlx/Ed05',... 
               'xyzSampleRate', 119.881035,...                                 
               'host',          data_host,...                                  
               'stcMode',       'hl_1_Ed_r',...                        
               'TTLValue',      '0x0010'...                                    
    );

    
    
% $$$     case 'hand_labeled'
% $$$       data_host = 'lrz';
% $$$       
% $$$     Sessions(1) = ...
% $$$         struct('sessionName',   'jg05-20120317',...          
% $$$                'mazeName',      'cof',...                              
% $$$                'trialName',     'all',...                              
% $$$                'xyz_host',      fullfile(my_xyz,'jg05'),...                             
% $$$                'nlx_host',      fullfile(my_nlx),...            
% $$$                'xyzSampleRate', 119.881035,...                         
% $$$                'host',          data_host,...                         
% $$$                'stcMode',       'hand_labeled_rev3_jg',...               
% $$$                'TTLValue',      '0x0040'...                           
% $$$     );
% $$$ 
% $$$       
% $$$     Sessions(end+1) = ...
% $$$         struct('sessionName',   'Ed01-20140707',...
% $$$                'mazeName',      'cof',...     
% $$$                'trialName',     'all',...               
% $$$                'xyz_host',      fullfile(my_xyz,'Ed01'),...                             
% $$$                'nlx_host',      fullfile(my_nlx),...            
% $$$                'xyzSampleRate', 119.881035,...          
% $$$                'host',          data_host,...           
% $$$                'stcMode',       'hand_labeled_rev2_jg',...                                  
% $$$                'TTLValue',      '0x0002'...             
% $$$     );
% $$$ 
% $$$     Sessions(end+1) = ...
% $$$         struct('sessionName',   'Ed03-20140624',...                            
% $$$                'mazeName',      'cof',...                                                    
% $$$                'trialName',     'all',...                                                    
% $$$                'xyz_host',      fullfile(my_xyz,'Ed03'),...                             
% $$$                'nlx_host',      fullfile(my_nlx),...            
% $$$                'xyzSampleRate', 119.881035,...                                               
% $$$                'host',          data_host,...                                                
% $$$                'stcMode',       'hand_labeled_rev1_jg',...                                  
% $$$                'TTLValue',      '0x0002'...                                    
% $$$     );
% $$$     Sessions(end+1) = ...
% $$$         struct('sessionName',   'Ed03-20140625',...                             
% $$$                'mazeName',      'cof',...                                                     
% $$$                'trialName',     'all',...                                                     
% $$$                'xyz_host',      fullfile(my_xyz,'Ed03'),...                              
% $$$                'nlx_host',      fullfile(my_nlx),...            
% $$$                'xyzSampleRate', 119.881035,...                                                
% $$$                'host',          data_host,...                                                 
% $$$                'stcMode',       'hand_labeled_rev1_Ed',...                                       
% $$$                'TTLValue',      '0x0002'...                                                   
% $$$     );
% $$$     
% $$$     Sessions(end+1) = ...
% $$$         struct('sessionName',   'Ed05-20140529',...
% $$$                'mazeName',      'ont',...                                      
% $$$                'trialName',     'all',...                                      
% $$$                'xyz_host',      fullfile(my_xyz,'Ed05'),...                             
% $$$                'nlx_host',      fullfile(my_nlx),...            
% $$$                'xyzSampleRate', 119.881035,...                                 
% $$$                'host',          data_host,...                                  
% $$$                'stcMode',       'hand_labeled_rev1_Ed',...                        
% $$$                'TTLValue',      '0x0010'...                                    
% $$$     );

  case 'er02'
    data_host = 'lmu';
    Sessions(1) = ...
    struct('sessionName',   'er02-20110831',...
           'mazeName',      'cof',...     
           'trialName',     'all',...               
           'xyz_host',      '/storage/gravio/data/processed/xyz/er02',...                    
           'nlx_host',      '/storage/gravio/data/processed/nlx',...               
           'xyzSampleRate', 119.881035,...          
           'host',          data_host,...           
           'project',       'general',...        
           'stcMode',       'default',...
           'TTLValue',      '0x4000'...             
     );
    Sessions(end+1) = ...
    struct('sessionName',   'er02-20110902',...
           'mazeName',      'cof',...     
           'trialName',     'all',...               
           'xyz_host',      '/storage/gravio/data/processed/xyz/er02',...                    
           'nlx_host',      '/storage/gravio/data/processed/nlx',...               
           'xyzSampleRate', 119.881035,...          
           'host',          data_host,...    
           'project',       'general',...        
           'stcMode',       'default',...
           'TTLValue',      '0x4000'...             
     );
    Sessions(end+1) = ...
    struct('sessionName',   'er02-20110905',...
           'mazeName',      'cof',...     
           'trialName',     'all',...               
           'xyz_host',      '/storage/gravio/data/processed/xyz/er02',...                    
           'nlx_host',      '/storage/gravio/data/processed/nlx',...               
           'xyzSampleRate', 119.881035,...          
           'host',          data_host,...    
           'project',       'general',...        
           'stcMode',       'default',...
           'TTLValue',      '0x4000'...             
     );
    Sessions(end+1) = ...
    struct('sessionName',   'er02-20110906',...
           'mazeName',      'cof',...     
           'trialName',     'all',...               
           'xyz_host',      '/storage/gravio/data/processed/xyz/er02',...                    
           'nlx_host',      '/storage/gravio/data/processed/nlx',...               
           'xyzSampleRate', 119.881035,...          
           'host',          data_host,...    
           'project',       'general',...        
           'stcMode',       'default',...
           'TTLValue',      '0x4000'...             
     );
    Sessions(end+1) = ...
    struct('sessionName',   'er02-20110907',...
           'mazeName',      'cof',...     
           'trialName',     'all',...               
           'xyz_host',      '/storage/gravio/data/processed/xyz/er02',...                    
           'nlx_host',      '/storage/gravio/data/processed/nlx',...               
           'xyzSampleRate', 119.881035,...          
           'host',          data_host,...    
           'project',       'general',...        
           'stcMode',       'default',...
           'TTLValue',      '0x4000'...             
     );
    Sessions(end+1) = ...
    struct('sessionName',   'er02-20110908',...
           'mazeName',      'cof',...     
           'trialName',     'all',...               
           'xyz_host',      '/storage/gravio/data/processed/xyz/er02',...                    
           'nlx_host',      '/storage/gravio/data/processed/nlx',...               
           'xyzSampleRate', 119.881035,...          
           'host',          data_host,...    
           'project',       'general',...        
           'stcMode',       'default',...
           'TTLValue',      '0x4000'...             
     );
    Sessions(end+1) = ...
    struct('sessionName',   'er02-20110913',...
           'mazeName',      'cof',...     
           'trialName',     'all',...               
           'xyz_host',      '/storage/gravio/data/processed/xyz/er02',...                    
           'nlx_host',      '/storage/gravio/data/processed/nlx',...               
           'xyzSampleRate', 119.881035,...          
           'host',          data_host,...           
           'project',       'general',...    
           'stcMode',       'default',...
           'TTLValue',      '0x4000'...             
     );


  case 'lists'
    disp(['setup'    ,'  ',...
          'all'      ,'  ',...
          'ncpH5B4'  ,'  ',...
          'ncpCy'    ,'  ']);

 
  otherwise
    warning('get_session_list:ListName, the provided list name was not recognized')
    Sessions = Seslist;
end



% $$$   case 'ER09'
% $$$     my_xyz = fullfile(my_xyz,'ER09');
% $$$     my_nlx = '/storage/evgeny/data/processed/';
% $$$ 
% $$$     Sessions(1) = struct('sessionName',   'ER09-20131122',...
% $$$                          'mazeName',      'sof',...
% $$$                          'trialName',     'all',...
% $$$                          'xyz_host',      my_xyz,...
% $$$                          'nlx_host',      my_nlx,...
% $$$                          'xyzSampleRate', 199.965672,...
% $$$                          'host',          'lmu',...
% $$$                          'TTLValue',      '0x0001'...
% $$$                          );
% $$$     Sessions(1) = struct('sessionName',  'jg05-20120311', ...
% $$$                          'mazeName',     'cof',           ...
% $$$                          'trialName',    'all',           ...
% $$$                          'xyz_host',      my_xyz,         ...
% $$$                          'nlx_host',      my_nlx,         ...
% $$$                          'xyzSampleRate', 119.881035,     ...
% $$$                          'host',         'lmu',           ...
% $$$                          'project',      'general',       ...
% $$$                          'TTLValue',     'Vicon start',   ...
% $$$                          'includeSyncInd',[1,2,5,6,9,10], ...
% $$$                          'offsets',       [15,0],         ...
% $$$                          'xOffSet',       0,              ...
% $$$                          'yOffSet',       0,              ...
% $$$                          'stcMode',      'default'        ...
% $$$     );
% $$$     
% $$$ 
% $$$     Sessions(end+1) = Sessions(1);
% $$$     Sessions(end).sessionName = 'ER09-20131128';
% $$$     
% $$$     Sessions(end+1) = Sessions(1);
% $$$     Sessions(end).sessionName = 'ER09-20131203';
% $$$ 
% $$$     Sessions(end+1) = Sessions(1);
% $$$     Sessions(end).sessionName = 'ER09-20131203';
% $$$     Sessions(end).mazeName    = 'sof';
% $$$ 
% $$$     Sessions(end+1) = Sessions(1);
% $$$     Sessions(end).sessionName = 'ER09-20131204';
% $$$ 
% $$$     Sessions(end+1) = Sessions(1);
% $$$     Sessions(end).sessionName = 'ER09-20131204';
% $$$     Sessions(end).mazeName    = 'sof';
% $$$     
% $$$     
% $$$     Sessions(end+1) = struct('sessionName','ER09-20131203',...
% $$$                          'mazeName',      'cof',...
% $$$                          'trialName',     'all',...
% $$$                          'xyz_host',      my_xyz,...
% $$$                          'nlx_host',      '/gpfs01/sirota/home/evgeny/nlx/ER09/',...
% $$$                          'xyzSampleRate', 199.965672,...
% $$$                          'host',          'lmu',...
% $$$                          'TTLValue',      '0x0001'...
% $$$                          );
% $$$     Sessions(end+1) = struct('sessionName',      'ER09-20131203',...
% $$$                          'mazeName',      'sof',...
% $$$                          'trialName',     'all',...
% $$$                          'xyz_host',      my_xyz,...
% $$$                          'nlx_host',      '/gpfs01/sirota/home/evgeny/nlx/ER09/',...
% $$$                          'xyzSampleRate', 199.965672,...
% $$$                          'host',          'lmu',...
% $$$                          'TTLValue',      '0x0001'...
% $$$                          );
% $$$ 
% $$$     Sessions(end+1) = struct('sessionName',      'ER09-20131204',...
% $$$                          'mazeName',      'sof',...
% $$$                          'trialName',     'all',...
% $$$                          'xyz_host',      my_xyz,...
% $$$                          'nlx_host',      '/gpfs01/sirota/home/evgeny/nlx/ER09/',...
% $$$                          'xyzSampleRate', 199.965672,...
% $$$                          'host',          'lmu',...
% $$$                          'TTLValue',      '0x0001'...
% $$$                          );
