function Trial = labelBhvBasic(Trial,varargin)
[Stc] = DefaultArgs(varargin,{Trial.stc.copy},true);



xyz = Trial.load('xyz');
xyz.filter('ButFilter',3,2.4);

if isempty(Stc.gsi('v')),
    fvxy = xyz.vel(1,[1,2]);
    fvxy.data(fvxy.data<1e-3)=1e-3;
    fvxy.data = log10(fvxy.data);
    vper = ThreshCross(fvxy.data,0.5,round(.25*xyz.sampleRate));
    Stc.addState(Trial.spath,...
                       Trial.filebase,...
                       vper,...
                       xyz.sampleRate,...
                       Trial.sync.copy,...
                       Trial.sync.data(1),...
                       'velthresh','v');
end


if isempty(Stc.gsi('h')),
    fvxy = xyz.vel(6,[1,2]);
    fvxy.data(fvxy.data<1e-3)=1e-3;
    fvxy.data = log10(fvxy.data);
    vper = ThreshCross(fvxy.data,0.5,round(.25*xyz.sampleRate));
    Stc.addState(Trial.spath,...
                       Trial.filebase,...
                       vper,...
                       xyz.sampleRate,...
                       Trial.sync.copy,...
                       Trial.sync.data(1),...
                       'velHthresh','h');
end


if isempty(Stc.gsi('r')) & all(xyz.model.gmi({'spine_middle','spine_upper'}))
    rper = rear(Trial,'com',45);
    Stc.addState(Trial.spath,...
                 Trial.filebase,...
                 rper,...
                 xyz.sampleRate,...
                 Trial.sync.copy,...
                 Trial.sync.data(1),...
                 'rear','r');




    if isempty(Stc.gsi('n')),
        Stc.states{end+1} = Stc{'v'}-(Stc{'r',120}+[-.5,.5]);
        Stc.states{end}.key = 'n'; 
        Stc.states{end}.label = 'NRvel';    
        Stc.states{end}.updateFilename([Trial.filebase,'.sst.',...
                            Stc.states{end}.label,'.',...
                            Stc.states{end}.key,'.mat']);
    end
end


Trial.stc = Stc;
Trial.stc.save(1);
