function label_bhv_msnn(Trial,varargin)
%function label_bhv_msnn(Trial,varargin)
%
% Default Arguments 
%   varargin:
%     sessionList              (String,MTASession)           ''
%     stcMode                  (String,MTAStateCollection)   'msnnN0+hand_labeled'
%     featureSet               (String)                      'fet_bref_rev7'
%     states                   (CellStr)                     {'walk','rear','turn','pause','groom','sit'}
%     keys                     (CellStr)                     {'w',   'r',   'n',   'p',    'm',    's'  }
%     model                    (String)                      ''
%     sampleRate               (Numeric)                     10
%     nNeurons                 (Numeric)                     25
%     nIter                    (Numeric)                     10
%     randomizationMethod      (String)                      'WSBNT'
%     map2reference            (Logical)                     true
%     normalize                (Logical)                     true
%     referenceTrial           (String)                      'jg05-20120317.cof.all'
%     trainingSessionList      (String)                      'hand_labeled'
%     normalizationSessionList (String)                      'hand_labeled'
%     dropIndex                (NumericArray)                []
%     prctTrain                (Numeric)                     90
%     postprocessingTag        (String)                      '_ppsvd'
%

% DEFARGS -----------------------------------------------------------------------------------------
defArgs = struct('name',                        'MSNNHL-2',                                     ...
                 'sessionList',                 Trial,                                          ...
                 'featureSet',                  'fet_bref_rev7',                                ...
                 'states',                      {{'walk','rear','turn','pause','groom','sit'}}, ...
                 'keys',                        {{'w','r','n','p','m','s'}},                    ...
                 'model',                       [],                                             ...
                 'sampleRate',                  10,                                             ...
                 'nNeurons',                    25,                                             ...
                 'nIter',                       10,                                             ...
                 'randomizationMethod',         'WSBNT',                                        ...
                 'map2reference',               true,                                           ...
                 'normalize',                   true,                                           ...
                 'referenceTrial',              'jg05-20120317.cof.all',                        ...
                 'trainingSessionList',         'hand_labeled',                                 ...
                 'normalizationSessionList',    'hand_labeled',                                 ...
                 'dropIndex',                   2,                                              ...
                 'prctTrain',                   90                                              ...
);
[name,sessionList,featureSet,states,keys,model,sampleRate,nNeurons,nIter,randomizationMethod,   ...
 map2reference,normalize,referenceTrial,trainingSessionList,normalizationSessionList,           ...
 dropIndex,prctTrain] = DefaultArgs(varargin,defArgs,'--struct');
% -------------------------------------------------------------------------------------------------

% CONSTRUCT model name
dropIndexTag = '';
if ~isempty(dropIndex), 
    dropIndexTag = num2str(dropIndex);
    dropIndexTag(dropIndexTag==[' '])='_';
end
model = ['MTAC_BATCH+' trainingSessionList '+'            ...
         dropIndexTag '+'                                 ...
         featureSet                                       ...
         '+SR'   num2str(sampleRate)                      ...
         'NN'    num2str(nNeurons)                        ...
         'NI'    num2str(nIter)                           ...
         'M'     num2str(map2reference)                   ...
         'MREF+' referenceTrial                           ...                          
         '+N'    num2str(normalize)                       ...             
         'NREF+' normalizationSessionList                 ...
         '+RND'  randomizationMethod                      ...
         '+PRCT' num2str(prctTrain)                       ...
         '+STS+' strjoin(keys,'')                         ...
         '+'     'multiSesPatNet'];

% LABEL behavior 
[Stc,labelingStats,networkOutput] =                                              ...
    bhv_nn_multi_session_patternnet(                                             ...
        sessionList,            featureSet,   states,   keys,  model,            ...
        sampleRate,             nNeurons,     nIter,    randomizationMethod,     ...
        map2reference,          normalize,    referenceTrial,                    ...
        trainingSessionList,    normalizationSessionList,                        ...
        dropIndex,              prctTrain                                        ...
);

% SAVE state collection with new name
cf(@(s) s.updateMode(name),Stc);
cf(@(s) s.save(true),      Stc);