function h = plotcc3(x,y,z,c);

h = surface([x(:)';x(:)'],...
            [y(:)';y(:)'],...
            [z(:)';z(:)'],...        
            [c(:)';c(:)'],...
            'facecolor','no',...
            'edgecolor','interp',...
            'linewidth',2);
