function h = plotcc(x,y,c,varargin)
[colmap] = DefaultArgs(varargin,{'jet'},true);

h = surface([x(:)';x(:)'],...
            [y(:)';y(:)'],...
            [zeros([1,numel(x)]);zeros([1,numel(x)])],...
            [c(:)';c(:)'],...
            'facecolor','no',...
            'edgecolor','interp',...
            'linewidth',2);
colormap(colmap);