function [markers,sticks,markerConnections] = plotSkeleton(xyz,ind)


%% Markers
marker_options = {};
marker_options.style ='o' ;
marker_options.size =8 ;
marker_options.erase = 'normal'; %{none|xor|background}
markers = repmat({0},1,xyz.model.N);
for l=1:xyz.model.N,
    markers{l} =line('Parent',gca, ...
                     'Tag',xyz.model.Markers{l}.name,...
                     'XData',[xyz.data(ind(end),l,1),xyz.data(ind(end),l,1)],...
                     'YData',[xyz.data(ind(end),l,2),xyz.data(ind(end),l,2)],...
                     'ZData',[xyz.data(ind(end),l,3),xyz.data(ind(end),l,3)],...
                     'Marker'         , marker_options.style, ...
                     'MarkerEdgeColor', xyz.model.Markers{l}.color./255, ...
                     'MarkerSize'     , marker_options.size, ...
                     'MarkerFaceColor', xyz.model.Markers{l}.color./255, ...
                     'EraseMode'      , marker_options.erase,...
                     'Visible','on');
end

markerConnections=[];
for i = 1:length(xyz.model.Connections)
    markerConnections= cat(1,markerConnections,....
                           [xyz.model.gmi(xyz.model.Connections{i}.marker1),xyz.model.gmi(xyz.model.Connections{i}.marker2)]);
end

sticks = repmat({0},1,length(xyz.model.Connections));
for l=1:length(xyz.model.Connections), 
    sticks{l} =line('Parent',gca,...
        'Tag',[xyz.model.Connections{l}.marker1 ':' xyz.model.Connections{l}.marker2],...
        'XData',[xyz.data(ind(end),markerConnections(l,1),1),xyz.data(ind(end),markerConnections(l,2),1)],...
        'YData',[xyz.data(ind(end),markerConnections(l,1),2),xyz.data(ind(end),markerConnections(l,2),2)],...
        'ZData',[xyz.data(ind(end),markerConnections(l,1),3),xyz.data(ind(end),markerConnections(l,2),3)],...
        'LineWidth', 2, ... stick_options.width,
     ...%'Color'    , xyz.model.Connections{l}.color./255, ...
        'EraseMode', 'normal',...
        'Visible','on');
end

