

% ALL to REAR ---------------------------------------------------------------------------------
% STATUS : set

% dbstop in adjust_state_boundaries_svd at 218
%Stc = adjust_state_boundaries_svd([],'hand_labeled'  ,...[]...
adjust_state_boundaries_svd([],[],...
                            struct('sessionList',            'hand_labeled',                ...
                                   'referenceTrial',         'jg05-20120317.cof.all',       ...
                                   'featureSet',             'fet_bref',                    ...
                                   'sampleMode',             'trimmed',                     ...
                                   'svdState',               'rear',                        ...
                                   'antecedentState',        'gper-rear',                   ...
                                   'subsequentState',        'rear',                        ...
                                   'immutableStates',        {{}},                          ...
                                   'sampleRate',             119.881035,                    ...
                                   'eigenVectorFeaturesMask',{{[6:10,16:25],[1:10,16:25]}}, ...
                                   'eigenVectorTemporalMask',[1:15,46:64],                  ...
                                   'eigenVectorIndices',     [1,2],                         ...
                                   'sortTurnsIndex',         [false,false],                 ...
                                   'embeddingWindow',        64,                            ...
                                   'regressionWindow',       100:181,                       ...
                                   'regressionThreshold',    5e3,                           ...
                                   'residualSearchWindow',   0.5,                           ...
                                   'medianCorrectionOffset', 0.14),                         ...
                            [],                                                             ...
                            false,                                                          ...
                            false,                                                          ...
                            true                                                            ...
);

%----------------------------------------------------------------------------------------------
            


% REAR to ALL ---------------------------------------------------------------------------------
% STATUS : set

% dbstop in adjust_state_boundaries_svd at 218
%Stc = adjust_state_boundaries_svd(Stc,'hand_labeled'  ,...[]...
adjust_state_boundaries_svd([],[],...
                            struct('sessionList',            'hand_labeled',                ...
                                   'referenceTrial',         'jg05-20120317.cof.all',       ...
                                   'featureSet',             'fet_bref',                    ...
                                   'sampleMode',             'trimmed',                     ...
                                   'svdState',               'rear',                        ...
                                   'antecedentState',        'rear',                        ...
                                   'subsequentState',        'gper-rear',                   ...
                                   'immutableStates',        {{}},                          ...
                                   'sampleRate',             119.881035,                    ...
                                   'eigenVectorFeaturesMask',{{[6:10,16:25],[1:10,16:25]}}, ...
                                   'eigenVectorTemporalMask',[1:15,46:64],                  ...
                                   'eigenVectorIndices',     [1,2],                         ...
                                   'sortTurnsIndex',         [false,false],                 ...
                                   'embeddingWindow',        64,                            ...
                                   'regressionWindow',       50:150,                        ...
                                   'regressionThreshold',    5e3,                           ...
                                   'residualSearchWindow',   0.5,                           ...
                                   'medianCorrectionOffset', -0.14),                        ...
                            [],                                                             ...
                            false,                                                          ...
                            false,                                                          ...
                            true                                                            ...
);

%----------------------------------------------------------------------------------------------





% PAUSE to TURN -------------------------------------------------------------------------------
% STATUS : set

% dbstop in adjust_state_boundaries_svd at 218
%Stc = adjust_state_boundaries_svd(Stc,'hand_labeled'  ,...[]...
adjust_state_boundaries_svd([],[],...
                            struct('sessionList',            'hand_labeled',                ...
                                   'referenceTrial',         'jg05-20120317.cof.all',       ...
                                   'featureSet',             'fet_bref',                    ...
                                   'sampleMode',             'trimmed',                     ...
                                   'svdState',               'walk+turn',                   ...
                                   'antecedentState',        'pause',                       ...
                                   'subsequentState',        'turn',                        ...
                                   'immutableStates',        {{}},                          ...
                                   'sampleRate',             119.881035,                    ...
                                   'eigenVectorFeaturesMask',{{[1:16,18:24,26:30]}},        ...
                                   'eigenVectorTemporalMask',[1:15,46:64],                  ...
                                   'eigenVectorIndices',     [2],                           ...
                                   'sortTurnsIndex',         [true],                        ...
                                   'embeddingWindow',        64,                            ...
                                   'regressionWindow',       100:150,                       ...
                                   'regressionThreshold',    5,                             ...
                                   'residualSearchWindow',   0.25,                          ...
                                   'medianCorrectionOffset', 0),                            ...
                            [],                                                             ...
                            false,                                                          ...
                            false,                                                          ...
                            true                                                           ...
);

%----------------------------------------------------------------------------------------------




% PAUSE to walk -------------------------------------------------------------------------------
% STATUS : set

% dbstop in adjust_state_boundaries_svd at 218
% dbstop in adjust_state_boundaries_svd at 289
%Stc = adjust_state_boundaries_svd(Stc,'hand_labeled'  ,...[]...
adjust_state_boundaries_svd([],[],...
                            struct('sessionList',            'hand_labeled',                ...
                                   'referenceTrial',         'jg05-20120317.cof.all',       ...
                                   'featureSet',             'fet_bref',                    ...
                                   'sampleMode',             'trimmed',                     ...
                                   'svdState',               'walk+turn',                   ...
                                   'antecedentState',        'pause',                       ...
                                   'subsequentState',        'walk',                        ...
                                   'immutableStates',        {{}},                          ...
                                   'sampleRate',             119.881035,                    ...
                                   'eigenVectorFeaturesMask',{{[2:15,17:2:25,26:30]}},      ...
                                   'eigenVectorTemporalMask',[1:15,46:64],                  ...
                                   'eigenVectorIndices',     [1],                           ...
                                   'sortTurnsIndex',         [false],                       ...
                                   'embeddingWindow',        64,                            ...
                                   'regressionWindow',       110:150,                       ...
                                   'regressionThreshold',    1000,                          ...
                                   'residualSearchWindow',   0.25,                          ...
                                   'medianCorrectionOffset', 0.08),                         ...
                            [],                                                             ...
                            false,                                                          ...
                            false,                                                          ...
                            true                                                           ...
);


cf(@(s) s.updateMode([s.mode,'_SVDTRAJADJ']), Stc);
cf(@(s) s.save(1),                            Stc);
StcADJ = cf(@(s) s.copy(),Stc);


figure();
sp = [];
sp(end+1)=subplot2(6,1,1:2,1);
plotSTC(Stc{1},1);
sp(end+1)=subplot2(6,1,3:4,1);
plotSTC(StcADJ{1},1);
sp(end+1)=subplot2(6,1,5:6,1);
plotSTC(StcNN{1},1);
linkaxes(sp,'xy');






% TURN to walk -------------------------------------------------------------------------------
% STATUS : Do Not Adjust

% dbstop in adjust_state_boundaries_svd at 218
% dbstop in adjust_state_boundaries_svd at 289
% $$$ adjust_state_boundaries_svd([],[],                                                          ...
% $$$                             struct('sessionList',            'hand_labeled',                ...
% $$$                                    'referenceTrial',         'jg05-20120317.cof.all',       ...
% $$$                                    'featureSet',             'fet_bref',                    ...
% $$$                                    'sampleMode',             'trimmed',                     ...
% $$$                                    'svdState',               'walk+turn',                   ...
% $$$                                    'antecedentState',        'turn',                        ...
% $$$                                    'subsequentState',        'walk',                        ...
% $$$                                    'immutableStates',        {{}},                          ...
% $$$                                    'sampleRate',             119.881035,                    ...
% $$$                                    'eigenVectorFeaturesMask',{{[1:15,17:2:25,26:30]}},      ...
% $$$                                    'eigenVectorTemporalMask',[1:15,46:64],                  ...
% $$$                                    'eigenVectorIndices',     [1],                           ...
% $$$                                    'sortTurnsIndex',         [false],                       ...
% $$$                                    'embeddingWindow',        64,                            ...
% $$$                                    'regressionWindow',       70:150,                        ...
% $$$                                    'regressionThreshold',    5e3,                           ...
% $$$                                    'residualSearchWindow',   0.25,                          ...
% $$$                                    'medianCorrectionOffset', 0),                            ...
% $$$                             [],                                                             ...
% $$$                             false,                                                          ...
% $$$                             false,                                                          ...
% $$$                             true                                                            ...
% $$$ );
% $$$ 
% $$$ 
% $$$ wts = cf(@(e,s)  [1:e]./s,                        embeddingWindow,sampleRate);
% $$$ ts =  cf(@(x)    [1:size(x,1)]./x.sampleRate,     xyz);
% $$$ 
% $$$ % PLOT feature segments - used to adjust regressionWindow
% $$$ 
% $$$ figure();
% $$$ for i= 1:size(fetSegs,3);
% $$$     subplot(1,size(fetSegs,3),i);
% $$$     hold('on');
% $$$     plot(fetSegs(:,:,i),'b');
% $$$     plot(nanmean(fetSegs(:,:,i),2),'r');
% $$$ end
% $$$ 
% $$$ 
% $$$ % PLOT residules - used to adjust regressionThreshold
% $$$ sp = [];
% $$$ figure();
% $$$ sp(end+1)=subplot2(6,1,[1:4],1);
% $$$ hold('on');
% $$$ for i = 1:size(csw{1},3),
% $$$     plot(ts{1},nunity(csw{1}(2,:,i)')),
% $$$ end
% $$$ plot(ts{1},nunity(sum(csw{1}(2,:,:),3)')),
% $$$ Lines(mean(sts{1},2)./sampleRate{1},[],'g');
% $$$ sp(end+1)=subplot2(6,1,5:6,1);
% $$$ plotSTC(Stc{1},1);
% $$$ linkaxes(sp,'x');
% $$$ 
% $$$ 
% $$$ % PLOT CCG between bhv transition and residules minimas - used to determin medianCorrectionOffset
% $$$ [sccg,txx,pxx] = cf(@(s,n,sr) CCG([s;n],[ones(size(s));2*ones(size(n))],...
% $$$                                   2,40,sr,[1,2],'count'),...
% $$$                     ssmins,nsmins,sampleRate);
% $$$ accg = sum(cat(4,sccg{:}),4);
% $$$ medianCorrectionOffset = median(cat(1,nsmins{:})-cat(1,ssmins{:}))./sampleRate{1};
% $$$ figure();
% $$$ bar(txx{1},accg(:,1,2));
% $$$ Lines(medianCorrectionOffset.*1000,[],'r');
% $$$ title(['CCG between ' subsequentState ' onsets and local minima of onset regression'])
% $$$ xlabel('Time shift(ms) centered on local minima')
% $$$ ylabel('count')
% $$$ 
% $$$ 
% $$$ figure();
% $$$ sp = [];
% $$$ sp(end+1)=subplot2(6,1,1:3,1);
% $$$ plotSTC(Stc{1},1);
% $$$ sp(end+1)=subplot2(6,1,4:6,1);
% $$$ plotSTC(StcN{1},1);
% $$$ linkaxes(sp,'xy');

%----------------------------------------------------------------------------------------------