function [ys,varargout] = spec(funHandle,data,parspec,varargin);
[cross] = DefaultArgs(varargin,{true});
varargout = cell(1,nargout-1);
if cross,
[ys,varargout{:}] = feval(funHandle,...
                          data,...
                          parspec.nFFT,...
                          parspec.Fs,...
                          parspec.WinLength,...
                          parspec.nOverlap,...
                          parspec.NW,...
                          parspec.Detrend,...
                          parspec.nTapers,...
                          parspec.FreqRange);
else
    for c = 1:size(data,2),
        [ys(:,:,c),varargout{:}] = feval(funHandle,...
                                         data(:,c),...
                                         parspec.nFFT,...
                                         parspec.Fs,...
                                         parspec.WinLength,...
                                         parspec.nOverlap,...
                                         parspec.NW,...
                                         parspec.Detrend,...
                                         parspec.nTapers,...
                                         parspec.FreqRange);
    end

end