function [ys,varargout] = spec(funHandle,data,parspec);

varargout = cell(1,nargout-1);
[ys,varargout{:}] = feval(funHandle,...
                          data,...
                          parspec.nFFT,...
                          parspec.Fs,...
                          parspec.WinLength,...
                          parspec.nOverlap,...
                          parspec.NW,...
                          parspec.Detrend,...
                          parspec.nTapers,...
                          parspec.FreqRange);

end