
Trial = MTATrial('jg05-20120317');
xyz = Trial.load('xyz');


tsf = 1;

nframe = size(xyz,1); %nframe: number of frames (time)
nmar   = size(xyz,2);  %nmar: number markers 
ndim   = size(xyz,3); %ndim: number of spatial dimensions (xyz)
j =1:nmar;
diffMat = permute(...
    cat(4,...
        permute(reshape(repmat(xyz(:,:,1)',nmar,1)...
                        -circshift(xyz(:,j(ones(nmar,1),:),1),-tsf).',[nmar,nmar,nframe]),[3,1,2]),...
        permute(reshape(repmat(xyz(:,:,2)',nmar,1)...
                        -circshift(xyz(:,j(ones(nmar,1),:),2),-tsf).',[nmar,nmar,nframe]),[3,1,2]),...
        permute(reshape(repmat(xyz(:,:,3)',nmar,1)...
                        -circshift(xyz(:,j(ones(nmar,1),:),3),-tsf).',[nmar,nmar,nframe]),[3,1,2])),...
                  [1,3,2,4]);

dmat = sqrt(sum(diffMat.^2,4));

figure,
imagesc(sq(dmat(100,:,:)))
