function Pfs = update_filename(Pfs,varargin)
if ~isempty(varargin),
    Session = varargin{1};
    if numel(varargin)>1,    
        Pfs.tag  = varargin{2};
    end
end



if isempty(Pfs.tag)
    pfsState = Session.stc{Pfs.parameters.states,Session.xyz.sampleRate};    
    binDimTag = num2str(Pfs.parameters.binDims);
    binDimTag(isspace(binDimTag)&isspace(circshift(binDimTag',1)'))=[];
    binDimTag(isspace(binDimTag)) = '_';
    smwTag = num2str(Pfs.parameters.smoothingWeights*100);
    smwTag(isspace(smwTag)&isspace(circshift(smwTag',1)'))=[];
    smwTag(isspace(smwTag)) = '_';

    Pfs.filename = [Session.filebase                                    ...
                    '.pfs.' Pfs.parameters.type '.'                     ...
                    Pfs.adata.trackingMarker '.'                        ...
                    Session.stc.mode '.'                                ...
                    pfsState.label '.'                                  ...
                    'ss' num2str(Pfs.parameters.spkShuffle)             ...
                    'ps' num2str(Pfs.parameters.posShuffle)             ...
                    'ni' num2str(Pfs.parameters.numIter)                ...
                    'bs' num2str(Pfs.parameters.bootstrap) 'sm' smwTag  ...
                    'bd' binDimTag '.mat'];
else
    Pfs.filename = [Pfs.session.sessionName,'.',...
                    Pfs.session.mazeName,'.'   ,...
                    Pfs.session.trialName,'.'  ,...
                    'Pfs.' Pfs.tag '.mat'];
end




