% MjgER2016_figure6
%
% DECODING position and behavior based on spatio-behavioral ratemaps
% 
% 
% 

%global AP
global MTA_PROJECT_PATH

MjgER2016_load_data();
states = {'theta','rear','hloc','hpause','lloc','lpause','groom','sit'};
spikeWindow = 0.3;
sampleRate = 30;
sampleRateTPD = 250;
phzBins = -pi:pi/4:pi;
phzBinCenters = sum([phzBins(1:end-1);phzBins(2:end)])'./2
smoothingWeights = [250.^2,250.^2, 0.4.^2, 0.4.^2];
interpParPfs = struct('bins',{{linspace(-500,500,50),...
                               linspace(-500,500,50),...
                               linspace(  -2,  0.8,50),...
                               linspace(  -0.8,2,  50)}},...
                      'nanMaskThreshold', 0.1,...
                      'methodNanMap',     'linear',...
                      'methodRateMap',    'linear');



% SECTION 1 ----------------------------------------------------------------------------------------
%
%  Behavior rate maps
%
%      Generate the behavior rate maps which are computed from the data within the placefield during
%  theta periods
%
%  Joint physical-behavioral rate maps
%
%      Generate the spatial-behavioral rate maps which are computed from the data within the 
%  placefield during theta periods
%


% SET analysis args
MjgER2016_figure6_args('section 1');

% GET behavior field rate map
bfrm        = cf(@(t,u)   compute_bhv_ratemaps(t,u),                 Trials, units);
bfrmShuff   = cf(@(t,u)   compute_bhv_ratemaps_shuffled(t,u),        Trials, units);

% GET bhv ratemap erpPCA
[eigVecs, eigScrs, eigVars, unitSubsets, validDims, zrmMean, zrmStd] = ...
    compute_bhv_ratemaps_erpPCA(bfrm, units);

cluSessionMapSubset = cluSessionMap(unitSubsets,:);

% GET bhv ratemap erpPCA scores
[fsrcz,FSrC,rmaps,FSCFr,FSrM,FSrS,fsrsMean,fsrsStd,rmapsShuffledMean,rmapsShuffled] = ...
    compute_bhv_ratemaps_erpPCA_scores(Trials,units,bfrm,bfrmShuff,eigVecs,validDims,unitSubsets,false);

% MAKE bhv ratemap mask
maskbhv = false(bfrm{1}.adata.binSizes');
maskbhv(validDims) = true;


% SELECT trial subset
tind = [3:5,17:23];
Trials = Trials(tind);
units  = units(tind);

stc  = cf(@(t)                                                                    ...
          t.load('stc','msnn_ppsvd_raux'),                                        ...
          Trials);

% GET xyhb placefields
dc4.pfs  = cf(@(t,u)  compute_xyhb_ratemaps(t,u),  Trials, units);
% MAKE xy ratemap mask
maskcirc = create_tensor_mask(dc4.pfs{1}.adata.bins(1:2));



% MAKE xyhb ratemap mask
% $$$ mask = repmat(maskcirc,[1,1,size(maskbhv)]).*repmat(permute(maskbhv,[3,4,1,2]),[size(maskcirc),1,1]);
%save(fullfile(MTA_PROJECT_PATH,'analysis','pfsXYHB_mask.mat'),'mask','-v7.3');
% LOAD xyhb ratemap mask
load(fullfile(MTA_PROJECT_PATH,'analysis','pfsXYHB_mask.mat'));


%%%<<< DIAGNOSTIC FIGURE
% $$$ rmp = plot(pfsXYHB{1},61,1,[],[],false);
% $$$ % CHECK mask is correct
% $$$ nx = pfsXYHB{1}.adata.binSizes(1);
% $$$ ny = pfsXYHB{1}.adata.binSizes(2);
% $$$ figure,
% $$$ nx = size(mask,1);
% $$$ ny = size(mask,2);
% $$$ sp = reshape(tight_subplot(ny,nx,0,0)',[ny,nx])';
% $$$ for x = 1:nx,
% $$$     for y = 1:ny,
% $$$         axes(sp(x,y));
% $$$         imagescnan(sq(mask(x,y,:,:))'.*sq(rmp(x,y,:,:))'); 
% $$$         axis('xy')
% $$$     end
% $$$ end
%%%>>>



%%%<<< DECODE xy 300ms window
dc2.tag = 'xy_sr30_sw300_HighRes';
dc2.sampleRate = 30;
dc2.mask = maskcirc;
dc2.smoothingWeights = [250.^2,250.^2];

% GET subject position objects
dc2.xyz = cf(@(t)                                                               ...
              preproc_xyz( t, 'trb', sampleRate),                               ...
              Trials);

% GET spike time objects
dc2.spk = cf(@(t,x,u)                                                           ...
              create( copy(t.spk), t, x.sampleRate, '', u, 'deburst'),          ...
              Trials, dc2.xyz, units);

% GET unit firing rate objects
dc2.ufr = cf(@(t,x,u,s)                                                         ...
              t.load('ufr',x,s,u,spikeWindow,true,'gauss'),                     ...
              Trials, dc2.xyz, units, dc2.spk);

% GET placefield ratemap objects
dc2.pfs = cf(@(t,u)                                                             ...
              compute_ratemaps(t,u),                                            ...
              Trials, units);

% GET unit inclusion 
dc2.uinc =  cf(@(u)                                                             ...
                sum(u.data>0.2,2),                                              ...
                dc2.ufr);

% DECODE position from unit firing rate
[dc2.com, dc2.max, dc2.sax, dc2.post] =                                         ...
        cf(@(t,u,r,p)                                                           ...
           decode_ufr(t, u,                                                     ...
                      dc2.sampleRate,                                           ...
                      r, p, [],                                                 ...
                      dc2.mask,                                                 ...
                      dc2.smoothingWeights,                                     ...
                      'tag',dc2.tag),                                           ...
           Trials, units, dc2.ufr, dc2.pfs);

% GET state matrix synced with dc2.xyz objects
dc2.stcm = cf(@(s,x)                                                            ...
               stc2mat(s,x,states),                                             ...
               stc, dc2.xyz);
%%%>>>


%%%<<< DECODE xyhb 300ms window 
% LOAD decoded position based on low sampleRate and full theta phase
dc4.tag = 'xy_sr30_HighRes';
dc4.sampleRate = dc2.sampleRate;
dc4.mask = mask;
dc4.smoothingWeights = [250.^2,250.^2, 0.4.^2, 0.4.^2];
dc4.stcm = dc2.stcm;
[dc4.com, dc4.max, dc4.sax, dc4.post] =                                         ...
        cf(@(t,u,r,p)                                                           ...        
           decode_ufr(t, u,                                                     ...
                      sampleRate,                                               ...
                      r, p, [],                                                 ...
                      dc4.mask, dc4.smoothingWeights,                           ...
                      'tag',dc4.tag),                                           ...
           Trials,units,dc2.ufr,dc4.pfs);
%%%>>>

dc4.fet = cf(@(t)  fet_HB_pitchB(t,dc4.sampleRate),  Trials);

dc2.error.xy   = cf(@(c,x)                                                      ...
                     sqrt( sum(( c(:,[1,2])-sq( x(:,'nose',[1,2]))).^2,2)),     ...
                     dc2.com, dc2.xyz);
dc4.error.xy = cf(@(c,x)                                                        ...
                     sqrt( sum(( c(:,[1,2])-sq( x(:,'nose',[1,2]))).^2,2)),     ...
                     dc4.com, dc2.xyz);
dc4.error.hp = cf(@(c,f)                                                        ...
                     c(:,3)-sq(f(:,1)),                                         ...
                     dc4.com, dc4.fet);
dc4.error.bp = cf(@(c,f)                                                        ...
                     c(:,4)-sq(f(:,2)),                                         ...
                     dc4.com,dc4.fet);
dc4.error.hb = cf(@(c,f)                                                        ...
                  sqrt( sum((c(:,[3,4])-f(:,[1,2])).^2,2)),                     ...
                  dc4.com,dc4.fet);




%figure,
out = cf(@(e4,e2,i) ...
         hist2(mud([e4(i),e2(i)]),50,50),...
         dc4.error.xy,dc2.error.xy,ind);
figure();
    imagesc(sum(cat(3,out{:}),3)');
    axis('xy');
    caxis([0,1000])

figure();
    for s = 1:10,
        subplot(2,5,s),
        imagesc(out{s}');
        axis('xy');
        line([0,800],[0,800],'Color','r');    
    end




ind = cf(@(s,u,p,phb)                                            ...
         s(:,1)==1                                               ...
           & any(s(:,3:6),2)                                     ...
           & u>1                                                 ...
           & p>0.0005                                            ...
           & phb>0.0005,                                         ...
         dc2.stcm,dc2.uinc,dc2.post,dc4.post);


% $$$ ind = cf(@(s,u,p,phb)                                            ...
% $$$          s(:,1)==1                                               ...
% $$$            & any(s(:,3:6),2)                                     ...
% $$$            & u>1                                                 ...
% $$$            & p>0.0005                                            ...
% $$$            & phb>0.0005,                                         ...
% $$$          dc2.stcm,dc2.uinc,dc2.post,dc4.post);

% $$$ figure,
% $$$     subplot(211);
% $$$         histogram(dc2.error.xy(ind),...
% $$$                   0:10:500);
% $$$     subplot(212);
% $$$         histogram(dc4.error.xy(ind),...
% $$$                   0:10:500);
% $$$ 
% $$$         
% $$$ [median(dc2.error.xy(ind)),median(dc4.error.xy(ind))]
% $$$ [std(nonzeros(  dc2.error.xy(ind).*double(0.5 < rand([sum(ind),1])))),...
% $$$  std(nonzeros(dc4.error.xy(ind).*double(0.5 < rand([sum(ind),1]))))]
% $$$ 
% $$$ [p,h] = ranksum(  dc2.error.xy(ind),...
% $$$                 dc4.error.xy(ind))

uincBin = 0:26;
xyeBin = 0:2.5:300;
hpeBin = -1:0.05:1;
bpeBin = -1:0.05:1;
hbeBin = 0:0.01:1;
xyBin = -500:50:500;
hpBin = -2:0.1:0.5;
bpBin = -0.5:0.1:2;

ddz        = cf(@(t,u,p)                                        ...
                compute_ddz(t,u,p,'sampleRate',dc2.sampleRate), ...
                Trials, units, dc2.pfs);

% for each trial
    %for each time point:
    %    identify the units within 20cm radius
    %    compute unit composition
    

cFSrC = bsxfun(@plus,FSrC(:,[1:3]),[0.5,1.5,1.5]);
figure,
plot3(cFSrC(:,1),cFSrC(:,2),cFSrC(:,3),'.');
hold('on');
line([0,3],[0,3],[0,3],'Color','r')

rvec = [1/sqrt(numel(cvec)).*ones(size(cvec))]';

zang = repmat({[]},size(dc2.xyz));
for t = 1:numel(tind),
    ti = tind(t);
    for s = find(ind{t})',
        usub = units{t}(abs(ddz{t}(s,:))<200);
        zvec = cFSrC( ismember( cluSessionMapSubset,               ...
                                [repmat(ti,[numel(usub),1]),usub'],...
                                'rows'),                           ...
                      1:3);
        if size(zvec,1) < 3,
            zang{t}(end+1) = 0;
            continue;
        else,
            zvec = sum(bsxfun(@rdivide,zvec,sqrt(sum(zvec.^2,2))));
            zang{t}(end+1) = acos((zvec * rvec)./sqrt( sum( zvec.^2, 2)));            
        end
    end
end


%cf(@(d,u,ti) ismember(cluSessionMapSubset,[ti.*ones(sum(d<200,2),1),u(d<200) , mat2cell(tind,1,ones(size(tind)))

uincInd    = cf(@(u) discretize(u,uincBin),                    dc2.uinc);
xyInd      = cf(@(x) discretize(sq(x(:,'hcom',[1,2])), xyBin), dc2.xyz );
xyInd      = cf(@(x) discretize(sq(x(:,'hcom',[1,2])), xyBin), dc2.xyz );
hpInd      = cf(@(h) discretize(h(:,1), hpBin), dc4.fet);
bpInd      = cf(@(b) discretize(b(:,2), bpBin), dc4.fet);

% XY - xy error
dc2.xyEInd = cf(@(e)  discretize(e, xyeBin),  dc2.error.xy);
dc4.xyEInd = cf(@(e)  discretize(e, xyeBin),  dc4.error.xy);
% XYHB - hp and bp error
dc4.hpEInd = cf(@(e)  discretize(e, hpeBin),  dc4.error.hp);
dc4.bpEInd = cf(@(e)  discretize(e, bpeBin),  dc4.error.bp);
dc4.hbEInd = cf(@(e)  discretize(e, hbeBin),  dc4.error.hb);

ind = cf(@(ei1,ei2,hpi,bpi,hbi,u,s)                              ...
         s(:,1)==1 & any(s(:,3:6),2)                           ...
           & nniz(ei1) & nniz(ei2)                             ...
           & nniz(hpi) & nniz(bpi)                             ...
           & nniz(hbi) & nniz(u),                              ...
         dc2.xyEInd, dc4.xyEInd,                               ...
           dc4.hpEInd, dc4.bpEInd,                             ...
           dc4.hbEInd, uincInd, dc2.stcm);

JPDF_d2xyErr_Uinc =                                             ...
    cf(@(x,u,i)                                                 ...
       accumarray([x(i),u(i)],                                  ...
                  1,                                            ...
                  [numel(xyeBin)-1,numel(uincBin)-1],           ...
                  @sum,nan),                                        ...
       dc2.xyEInd, uincInd, ind);

JPDF_d4xyErr_Uinc =                                             ...
    cf(@(x,u,i)                                                 ...
       accumarray([x(i),u(i)],                                  ...
                  1,                                            ...
                  [numel(xyeBin)-1,numel(uincBin)-1],           ...
                  @sum,nan),                                        ...
       dc4.xyEInd, uincInd, ind);


JPDF_d4hpErr_Uinc =                                             ...
    cf(@(hp,u,i)                                                ...
       accumarray([hp(i),u(i)],                                 ...
               1,                                               ...
               [numel(hpeBin)-1,numel(uincBin)-1],              ...
               @sum,nan),                                           ...
       dc4.bpEInd, uincInd, ind);


JPDF_d4bpErr_Uinc =                                             ...
    cf(@(bp,u,i)                                                ...
       accumarray([bp(i),u(i)],                                 ...
               1,                                               ...
               [numel(bpeBin)-1,numel(uincBin)-1],              ...
               @sum,nan),...
       dc4.hpEInd, uincInd, ind);

JPDF_d4hbErr_Uinc =                                             ...
    cf(@(hb,u,i)                                                ...
       accumarray([hb(i),u(i)],                                 ...
               1,                                               ...
               [numel(hbeBin)-1,numel(uincBin)-1],              ...
               @sum,nan),...
       dc4.hbEInd, uincInd, ind);

% $$$ CONEXP_d4hbErr_Uinc_post =                                      ...
% $$$     cf(@(hb,u,i)                                                ...
% $$$        accumarray([hb(i),u(i)],                                 ...
% $$$                dc4.post,                                        ...
% $$$                [numel(bpeBin)-1,numel(uincBin)-1],              ...
% $$$                @sum,nan),...
% $$$        dc4.hbEInd, uincInd, nind,ind);



xyeBinCenters  = (xyeBin(1:end-1)+xyeBin(2:end))./2;
uincBinCenters = (uincBin(1:end-1)+uincBin(2:end))./2;
hpeBinCenters  = (hpeBin(1:end-1)+hpeBin(2:end))./2;
bpeBinCenters  = (bpeBin(1:end-1)+bpeBin(2:end))./2;
hbeBinCenters  = (hbeBin(1:end-1)+hbeBin(2:end))./2;

y = 1;
figure();
colormap('jet');
    subplot2(5,2,y,1);
        imagesc(xyeBinCenters./10,                              ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d2xyErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;
    subplot2(5,2,y,1);
        imagesc(xyeBinCenters./10,                              ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4xyErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;                
    subplot2(5,2,y,1);
        imagesc(hbeBinCenters,                                  ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4hbErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;        
    subplot2(5,2,y,1);
        imagesc(hpeBinCenters,                                  ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4hpErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;
    subplot2(5,2,y,1);
        imagesc(bpeBinCenters,                                  ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4bpErr_Uinc{:}),3,'omitnan')');
        axis('xy');

% $$$ t = 9;
% $$$ figure,subplot(211);plot(dc4.fet{t}(:,1)),hold on,plot(dc4.com{t}(:,3)); 
% $$$       subplot(212);plot(dc4.fet{t}(:,2)),hold on,plot(dc4.com{t}(:,4));
% $$$ linkaxes(findobj(gcf(),'Type','Axes'),'x');
       
CONEXP_xy_hbErr =                                               ...
    cf(@(xy,bp,u,i)                                             ...
       accumarray([xy(i,1),xy(i,2)],                            ...
                  hbeBin(bp(i)),                                ...
                  [numel(xyBin)-1,numel(xyBin)-1],              ...
                  @mean,                                        ...
                  NaN),                                         ...
       xyInd, dc4.hpEInd, uincInd, ind);

CONSTD_xy_hbErr =                                               ...
    cf(@(xy,bp,u,i)                                             ...
       accumarray([xy(i,1),xy(i,2)],                            ...
                  hbeBin(bp(i)),                                ...
                  [numel(xyBin)-1,numel(xyBin)-1],              ...
                   @std,                                        ...
                  NaN),                                         ...
       xyInd, dc4.hpEInd, uincInd, ind);
             
figure();
for s = 1:10,
    subplot2(2,10,1,s);
    imagescnan({linspace(-500,500,numel(xyBin)-1),              ...
                linspace(-500,500,numel(xyBin)-1),              ...
                CONEXP_xy_hbErr{s}'},                           ...
               [-0.75,0.75],                                    ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
    
    subplot2(2,10,2,s);
    imagescnan({linspace(-500,500,numel(xyBin)-1),              ...
                linspace(-500,500,numel(xyBin)-1),              ...
                CONSTD_xy_hbErr{s}'},                           ...
               [0,0.5],                                         ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
end




nind = cf(@(ei1,ei2,hpi,bpi,hbi,hp,bp,u,s)                              ...
         s(:,1)==1 & any(s(:,2:6),2)                           ...
           & nniz(ei1) & nniz(ei2)                             ...
           & nniz(hpi) & nniz(bpi)                             ...
           & nniz(hbi) & nniz(u)...
           & nniz(hp)  & nniz(bp),                              ...
         dc2.xyEInd, dc4.xyEInd,                               ...
           dc4.hpEInd, dc4.bpEInd,                             ...
           dc4.hbEInd, hpInd, bpInd, ...
           uincInd, dc2.stcm);

CONEXP_hb_xyErr =                                               ...
    cf(@(hp,bp,xye,u,i)                                         ...
       accumarray([hp(i), bp(i)],                               ...
                  xyeBin(xye(i)),                               ...
                  [numel(hpBin)-1,numel(bpBin)-1],              ...
                  @mean,                                        ...
                  NaN),                                         ...
       hpInd, bpInd, dc4.xyEInd, uincInd, nind);
CONSTD_hb_xyErr =                                               ...
    cf(@(hp,bp,xye,u,i)                                         ...
       accumarray([hp(i), bp(i)],                               ...
                  xyeBin(xye(i)),                               ...
                  [numel(hpBin)-1,numel(bpBin)-1],              ...
                  @std,                                         ...
                  NaN),                                         ...
       hpInd, bpInd, dc4.xyEInd, uincInd, nind);

figure();
for s = 1:10,
    subplot2(2,10,1,s);
    imagescnan({linspace([hpBin([1,end]),numel(hpBin)-1]),      ...
                linspace([bpBin([1,end]),numel(bpBin)-1]),      ...
                CONEXP_hb_xyErr{s}'},                           ...
               [0,200],                                         ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
    axis('xy');
    
    subplot2(2,10,2,s);
    imagescnan({linspace([hpBin([1,end]),numel(hpBin)-1]),      ...
                linspace([bpBin([1,end]),numel(bpBin)-1]),      ...
                CONSTD_hb_xyErr{s}'},                           ...
               [0,100],                                         ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
    axis('xy');
end










% LOAD decoded position based on high sampleRate and binned by theta phase
decEstComTPD     = cell([1,numel(tind)]);
decEstMaxTPD     = cell([1,numel(tind)]);
decEstSaxTPD     = cell([1,numel(tind)]);
posteriorMaxTPD  = cell([1,numel(tind)]);
unitInclusionTPD = cell([1,numel(tind)]);
xyz  = cf(@(t)     resample(preproc_xyz(t,'trb'),sampleRateTPD),      Trials(tind));
for t = tind;
    Trials{t}.lfp.filename = [Trials{t}.name,'.lfp'];    
    tn = find(t==tind);
    try,   lfp = load(Trials{t},'lfp',sessionList(t).thetaRefGeneral);
    catch, lfp = load(Trials{t},'lfp',sessionList(t).thetaRefGeneral);
    end
    % PHZ : LFP phase restricted to the theta band [6-12Hz]
    phz = lfp.phase([6,12]);
    phzBinInds = discretize(phz.data,phzBins);
    spk  = create(copy(Trials{t}.spk),Trials{t},lfp.sampleRate,'',units{t},'deburst');
    for p = 1:numel(phzBins)-1
        spkt = copy(spk);
        spkt.clu = spkt.clu(phzBinInds(spkt.res)==p);
        spkt.res = round(spkt.res(phzBinInds(spkt.res)==p)./lfp.sampleRate.*sampleRateTPD);    
        spkt.sampleRate = sampleRateTPD;
        ufr = Trials{t}.load('ufr',xyz{tn},spkt,units{t},spikeWindow,true,'gauss');
        ufr.data =  ufr.data.*6;
        unitInclusionTPD{tn}(:,p) = sum(ufr.data>0.2,2);
        tag = ['xyhb_thpD',num2str(sampleRateTPD),'_',num2str(p),'o',num2str(numel(phzBins)-1)];
        [decEstComTPD{tn}(:,:,p),decEstMaxTPD{tn}(:,:,p),...
         decEstSaxTPD{tn}(:,:,p),posteriorMaxTPD{tn}(:,p)] = ...
            decode_ufr(Trials{t},units{t},sampleRateTPD,ufr,pfsXYHB{tn},...
                       [],mask,smoothingWeights,'tag',tag,'overwrite',false);
    end
end




% COMPILE egocentric variables 
fet  = cf(@(t)    fet_HB_pitchB(t,sampleRateTPD),                                    Trials(tind));
hvec = cf(@(x)    x(:,'head_front',[1,2])-x(:,'head_back',[1,2]),                    xyz          );
hvec = cf(@(h)    sq(bsxfun(@rdivide,h,sqrt(sum(h.^2,3)))),                          hvec         );
hvec = cf(@(h)    cat(3,h,sq(h)*[0,-1;1,0]),                                         hvec         );
tvec = cf(@(x)    circshift(x(:,'hcom',[1,2]),-1)-circshift(x(:,'hcom',[1,2]),1),    xyz          );
tvec = cf(@(h)    sq(bsxfun(@rdivide,h,sqrt(sum(h.^2,3)))),                          tvec         );
tvec = cf(@(h)    cat(3,h,sq(h)*[0,-1;1,0]),                                         tvec         );
stc  = cf(@(t)    t.load('stc','msnn_ppsvd_raux'),                                   Trials(tind));
stcm = cf(@(s,x)  stc2mat(s,x,states),                                               stc,   xyz   );

% COMPUTE error
dErr = decEstComTPD;
%dErr = decEstSaxTPD;
%dErr = decEstMaxTPD;
dErr = cf(@(e,x,h,f)  cat(2,...
                          sq(multiprod(permute(bsxfun(@minus,...
                                                  e(:,[1,2],:),...
                                                  sq(x(:,'hcom',[1,2]))),...
                                           [1,2,4,3]),...
                                   h(:,:,:),2,[2,3])),...
                          [bsxfun(@minus,f(:,1),e(:,3,:)),bsxfun(@minus,f(:,2),e(:,4,:))]), ...
          dErr,xyz,hvec,fet);



%%%<<< LOAD example data
t = 20;
Trial = Trials{t};
unitSubset = units{t};
exyz = resample(Trial.load('xyz','trb'),30);
%efet = fet_HB_pitchB(Trial,sampleRate);
efet = resample(copy(fet{tind==t}),sampleRate);
ets = [1:size(exyz,1)]./sampleRate;
estcm = stc2mat(Trial.load('stc'),exyz,states);
eind =   posteriorMax{t==tind} > 0.001 ...
       & unitInclusion{t==tind} > 3     ...
       & estcm(:,1)==1;
enanmask = ones([size(exyz,1),1]);
enanmask(~eind)=nan;

%%%>>>

% STARTFIG -----------------------------------------------------------------------------------------


eTS = [290,345];
%eTS = [530,600];
%eTS = [1000,1045];
eInds = round(eTS.*sampleRate)+1;
eInds = [eInds(1):eInds(2)]';

[hfig,fig,fax,sax] = set_figure_layout(figure(666006),'A4','portrait',[],1.5,1.5,0,0.2);




%%%<<< PLOT trajectory example in xy space
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(1,-fig.subplot.height, 1, 0);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*2,                        ...
                              fig.subplot.height*2],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(exyz(eInds,5,1),...
     exyz(eInds,5,2),...
     '-k','LineWidth',1);
plot(sq(decEstCom{t==tind}(eInds,1)).*enanmask(eInds),...
     sq(decEstCom{t==tind}(eInds,2)).*enanmask(eInds),...
     '-r','LineWidth',1);
xlim([-500,500]);
ylim([-500,500]);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT trajectory example in bhv space
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(3, -fig.subplot.height, 1, 0);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*2,                        ...
                              fig.subplot.height*2],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(efet(eInds,1),...
     efet(eInds,2),...
     '-k','LineWidth',1);
plot(sq(decEstCom{t==tind}(eInds,3)).*enanmask(eInds),...
     sq(decEstCom{t==tind}(eInds,4)).*enanmask(eInds),...
     '-r','LineWidth',1);
xlim(sax(end),[-1.8,0.6]);
ylim(sax(end),[-0.6,1.8]);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT x vs EST x
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(1, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     exyz(eInds,5,1),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,1)).*enanmask(eInds),...
     '-r','LineWidth',1);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT y vs EST y
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(2, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     exyz(eInds,5,2),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,2)).*enanmask(eInds),...
     '-r','LineWidth',1);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT hp vs EST hp
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(3, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     efet(eInds,1),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,3)).*enanmask(eInds),...
     '-r','LineWidth',1);
sax(end).XTick = [];
sax(end).YTick = [];
ylim([-1.8,0.6]);
%%%>>>


%%%<<< PLOT bp vs EST bp
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(4, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     efet(eInds,2),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,4)).*enanmask(eInds),...
     '-r','LineWidth',1);
sax(end).YTick = [];
ylim([-0.6,1.8]);
%%%>>>


%%%<<< COMPUTE error for TDP decoding
stid = [2,3,4,5,6];
dcTDPfrontal = repmat({cell([1,10])},[1,5]);
dcTDPlateral = repmat({cell([1,10])},[1,5]);
indTDP = cell([1,5]);
for sts = 1:numel(stid),
    indTDP{sts}  = cf(@(p,u,s)                                           ...
                      all(p>0.0005,2)                                    ...
                      & sum(double(u>=1),2)>6                          ...
                      & s(:,1)==1                                      ...
                      & any(logical(s(:,stid(sts))),2),                     ...
                      posteriorMaxTPD,unitInclusionTPD,stcm);
    for tn = 1:10,
        for j = 1:8;
            dcTDPfrontal{sts}{tn} = ...
                cat(2,                                                              ...
                    dcTDPfrontal{sts}{tn},                                             ...
                    histc(sq(dErr{tn}(indTDP{sts}{tn},1,j)),linspace(-500,500,100)));
            dcTDPlateral{sts}{tn} = ...
                cat(2,                                                                ...
                    dcTDPlateral{sts}{tn},                                                 ...
                    histc(sq(dErr{tn}(indTDP{sts}{tn},2,j)),linspace(-500,500,100)));
        end
    end
end
%%%>>>


%%%<<< PLOT frontal error for TDP decoding
% ADJUST subplot coordinates

[yind, yOffSet, xind, xOffSet] = deal(5, -0.8, s, 0);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width,                        ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);

for s = 1:5
figure
hold('on');
imagesc(linspace(-500,500,250),                                 ...
        circ_rad2ang([phzBinCenters;phzBinCenters+2*pi]),       ...
        repmat(sum(cat(3,dcTDPfrontal{s}{:}),3),1,2)')
axis('xy');
xlim([-200,200]);
ylim([-60,420]);            
% MASK areas outside single cycle
patch([-300,-300,300,300],...
      [ 360, 420,420,360],...
      [0.2,0.2,0.2],...
      'EdgeAlpha',0,...
      'FaceAlpha',0.4);
patch([-300,-300,300,300],...
      [ -60,   0,  0,-60],...
      [0.2,0.2,0.2],...
      'EdgeAlpha',0,...
      'FaceAlpha',0.4);
sax(end).XTick = [-150,0,150];
sax(end).XTickLabels = [-15,0,15];
end

%%%>>>

%%%<<< PLOT lateral error as function of theta phase
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(5, -0.8, 2, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width,                        ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
imagesc(linspace(-500,500,250),                                 ...
        circ_rad2ang([phzBinCenters;phzBinCenters+2*pi]),       ...
        repmat(sum(cat(3,dcTDPlateral{:}),3),1,2)')
axis('xy');
xlim([-200,200]);
ylim([-60,420]);            
% MASK areas outside single cycle
patch([-300,-300,300,300],...
      [ 360, 420,420,360],...
      [0.2,0.2,0.2],...
      'EdgeAlpha',0,...
      'FaceAlpha',0.4);
patch([-300,-300,300,300],...
      [ -60,   0,  0,-60],...
      [0.2,0.2,0.2],...
      'EdgeAlpha',0,...
      'FaceAlpha',0.4);
sax(end).XTick = [-150,0,150];
sax(end).XTickLabels = [-15,0,15];
%%%>>>



%%%<<< supfig
figure();
for tn = 1:10
    subplot2(2,10,1,tn);
    imagesc(linspace(-500,500,250),                             ...
            [phzBinCenters;phzBinCenters+2*pi],                 ...
            repmat(dcTDPfrontal{tn},1,2)');
    axis('xy');
    xlim([-300,300]);    
    
    subplot2(2,10,2,tn);
    imagesc(linspace(-500,500,250),1:8,repmat(dcTDPlateral{tn},1,2)')
    axis('xy');
    xlim([-300,300]);
end
%%%>>>



% STOPFIG ------------------------------------------------------------------------------------------
    

ind  = cf(@(p,u,s) all(p>0.00005,2) & all(u>=2,2) & s(:,1)==1 & any(logical(s(:,stid)),2),...
          posteriorMaxTPD,unitInclusionTPD,stcm);


xD = linspace(-300,300,30);
yD = linspace(-300,300,30);
hD = linspace(-1.5,1.5,30);
bD = linspace(-1.5,1.5,30);

hCntXY = cf(@(e,i)  cat(3,...
                        hist2(e(i,[1,2],1),xD,yD),...
                        hist2(e(i,[1,2],2),xD,yD),...
                        hist2(e(i,[1,2],3),xD,yD),...
                        hist2(e(i,[1,2],4),xD,yD),...
                        hist2(e(i,[1,2],5),xD,yD),...
                        hist2(e(i,[1,2],6),xD,yD)),...
                        dErr,ind);
hCntXY = sum(cat(4,hCntXY{:}),4);

hCntHB = cf(@(e,i)  cat(3,...
                        hist2(e(i,[3,4],1),hD,bD),...
                        hist2(e(i,[3,4],2),hD,bD),...
                        hist2(e(i,[3,4],3),hD,bD),...
                        hist2(e(i,[3,4],4),hD,bD),...
                        hist2(e(i,[3,4],5),hD,bD),...
                        hist2(e(i,[3,4],6),hD,bD)),...
                        dErr,ind);
hCntHB = sum(cat(4,hCntHB{:}),4);

figure,
spp = gobjects([0,1]);
spb = gobjects([0,1]);
for p = 1:numel(phzBins)-1,
    spp(end+1) = subplot2(numel(phzBins)-1,2,p,1);    imagesc(xD,yD,hCntXY(:,:,p)');   axis('xy');
    spb(end+1) = subplot2(numel(phzBins)-1,2,p,2);    imagesc(hD,bD,hCntHB(:,:,p)');   axis('xy');
end
af(@(a) caxis(a,[0,120]),spp);
af(@(a) caxis(a,[0,400]),spb);



t = 3
ind{t} = ':';
figure,
subplot(4,1,1);plot([xyz{t}(ind{t},5,1),sq(dErr{t}(ind{t},1,:))]);    
subplot(4,1,2);plot([xyz{t}(ind{t},5,2),sq(dErr{t}(ind{t},2,:))]);        
subplot(4,1,3);plot([fet{t}(ind{t},1),  sq(dErr{t}(ind{t},3,:))]);
subplot(4,1,4);plot([fet{t}(ind{t},2),  sq(dErr{t}(ind{t},4,:))]);
linkaxes(findobj(gcf(),'Type','Axes'),'x');




tind = 20;
Trial = Trials{tind};
unitSubset = units{tind};
xyz = preproc_xyz(Trial,'trb');
xyz.resample(sampleRate);
fet = fet_HB_pitchB(Trial,sampleRate);
hvec = xyz(:,'head_front',[1,2])-xyz(:,'head_back',[1,2]);
hvec = sq(bsxfun(@rdivide,hvec,sqrt(sum(hvec.^2,3))));
hvec = cat(3,hvec,sq(hvec)*[0,-1;1,0]);
% CONVERT MTAStateCollection into a state matrix 
stc = Trial.load('stc','msnn_ppsvd_raux');
stcm = stc2mat(stc,xyz,states);



dfet = decEstComTPD{3};
%dfet = decEstSaxTPD{1};
decError = zeros([size(xyz{t},1),size(decEstSax{j},2),numel(phzBins)-1]);
for p = 1:numel(phzBins)-1,
    decError(:,[1,2],p) = [multiprod(dfet(:,[1,2],p)-sq(xyz{t}(:,'hcom',[1,2])),hvec{t}(:,:,:),2,[2,3])];
end            
decError(:,[3,4],:) = [bsxfun(@minus,fet{t}(:,1),dfet(:,3,:)),bsxfun(@minus,fet{t}(:,2),dfet(:,4,:))];


j = 3
ind =   all(posteriorMaxTPD{j}>0.0001,2)...
      & all(unitInclusionTPD{j}>=4,2) ...
      & stcm(:,1)==1 & any(logical(stcm(:,[3,4,5,6])),2);
figure,
spp = gobjects([0,1]);
spb = gobjects([0,1]);
for p = 1:numel(phzBins)-1,
    spp(end+1) = subplot2(numel(phzBins)-1,2,p,1);
    hist2(decError(ind,[1,2],p),linspace(-300,300,50),linspace(-400,400,50));
    spb(end+1) = subplot2(numel(phzBins)-1,2,p,2);
    hist2(decError(ind,[3,4],p),linspace(-1.5,1.5,50),linspace(-1.5,1.5,50));
end
af(@(a) caxis(a,[0,50]),spp);
af(@(a) caxis(a,[0,150]),spb);



figure,
ind = all(posteriorMaxTPD{j}>0.000001,2)      & all(unitInclusionTPD{t}>=4,2);
subplot(4,1,1);plot([xyz{t}(ind,5,1),sq(dfet(ind,1,:))]);    
subplot(4,1,2);plot([xyz{t}(ind,5,2),sq(dfet(ind,2,:))]);        
subplot(4,1,3);plot([fet{t}(ind,1),  sq(dfet(ind,3,:))]);
subplot(4,1,4);plot([fet{t}(ind,2),  sq(dfet(ind,4,:))]);
linkaxes(findobj(gcf(),'Type','Axes'),'x');



figure,
ind = posteriorMax{j}>0.0001;
subplot(5,1,1);plot([xyz(ind,5,1),sq(decEstCom{j}(ind,1))]);    
subplot(5,1,2);plot([xyz(ind,5,2),sq(decEstCom{j}(ind,2))]);        
subplot(5,1,3);plot([fet(ind,1),  sq(decEstCom{j}(ind,3))]);
subplot(5,1,4);plot([fet(ind,2),  sq(decEstCom{j}(ind,4))]);
subplot(5,1,5);plot([unitInclusion{j}(ind)]);
linkaxes(findobj(gcf(),'Type','Axes'),'x');
