% MjgER2016_analysis_setup
% Setup global variable AP to centralize the assignment function default arguments
%  
% Syntax AP.(mfilename).(varname) = golbalDefaultValue;
%
% Requires function MTA:utilities:DefaultArgs
%

global AP

% GENERAL ------------------------------------------------------------------------------------------
AP.fet_HB_pitchB.referenceTrial = 'Ed05-20140529.ont.all';
%---------------------------------------------------------------------------------------------------


% FIGURE6 Behavior space theta decomposition -------------------------------------------------------


sessionListName = 'MjgER2016';
tag             = 'hbpptbpFS1v3';

AP.req20181106.sessionListName = sessionListName;
AP.req20181106.tag             = tag;
AP.req20181106.pargs           = struct('units',              [],                                   ...
                                        'states',             'theta',                              ...
                                        'overwrite',          false,                                ...
                                        'tag',                '',                                   ...
                                        'binDims',            [0.1,pi/8,0.1],                       ...
                                        'SmoothingWeights',   [2,1.1,2],                            ...
                                        'type',               'xyz',                                ...
                                        'spkShuffle',         false,                                ...
                                        'posShuffle',         false,                                ...
                                        'numIter',            1,                                    ...
                                        'xyzp',               [],                                   ...
                                        'boundaryLimits',     [-1.8,1;-pi,pi;-0.8,2],               ...
                                        'bootstrap',          false,                                ...
                                        'halfsample',         false,                                ...
                                        'compute_pfs',        @PlotPFCirc,                          ...
                                        'autoSaveFlag',       false,                                ...
                                        'spk',                []                                    ...
                                        );

AP.req20181119.sessionListName = sessionListName;
AP.req20181119.tag             = tag;


req20181106(); % COMPUTE behavior rate map as a function of theta phase
req20181119(); % COMPUTE factors of behavior rate over theta phases



% LESS Smoothing of the placefields

sessionListName = 'MjgER2016';
tag             = 'hbpptbpFS1v4';

AP.req20181106.sessionListName = sessionListName;
AP.req20181106.tag             = tag;
AP.req20181106.pargs           = struct('units',              [],                                   ...
                                        'states',             'theta',                              ...
                                        'overwrite',          false,                                ...
                                        'tag',                '',                                   ...
                                        'binDims',            [0.1,pi/8,0.1],                       ...
                                        'SmoothingWeights',   [1.5,0.6,1.5],                        ...
                                        'type',               'xyz',                                ...
                                        'spkShuffle',         false,                                ...
                                        'posShuffle',         false,                                ...
                                        'numIter',            1,                                    ...
                                        'xyzp',               [],                                   ...
                                        'boundaryLimits',     [-1.8,1;-pi,pi;-0.8,2],               ...
                                        'bootstrap',          false,                                ...
                                        'halfsample',         false,                                ...
                                        'compute_pfs',        @PlotPFCirc,                          ...
                                        'autoSaveFlag',       false,                                ...
                                        'spk',                []                                    ...
                                        );

AP.req20181119.sessionListName = sessionListName;
AP.req20181119.tag             = tag;


sessionListName = 'MjgER2016';
tag             = 'hbpptbpFS1v5';

AP.req20181106.sessionListName = sessionListName;
AP.req20181106.tag             = tag;
AP.req20181106.pargs           = struct('units',              [],                                   ...
                                        'states',             'theta',                              ...
                                        'overwrite',          false,                                ...
                                        'tag',                '',                                   ...
                                        'binDims',            [0.1,pi/8,0.1],                       ...
                                        'SmoothingWeights',   [1.8,0.6,1.8],                        ...
                                        'type',               'xyz',                                ...
                                        'spkShuffle',         false,                                ...
                                        'posShuffle',         false,                                ...
                                        'numIter',            1,                                    ...
                                        'xyzp',               [],                                   ...
                                        'boundaryLimits',     [-1.8,1;-pi,pi;-0.8,2],               ...
                                        'bootstrap',          false,                                ...
                                        'halfsample',         false,                                ...
                                        'compute_pfs',        @PlotPFCirc,                          ...
                                        'autoSaveFlag',       false,                                ...
                                        'spk',                []                                    ...
                                        );

AP.req20181119.sessionListName = sessionListName;
AP.req20181119.tag             = tag;


req20181106(); % COMPUTE behavior rate map as a function of theta phase
req20181119(); % COMPUTE factors of behavior rate over theta phases

%---------------------------------------------------------------------------------------------------





