% MjgER2016_figure6
%
% DECODING position and behavior based on spatio-behavioral ratemaps
% 
% 
% 

%global AP
global MTA_PROJECT_PATH

MjgER2016_load_data();
states = {'theta','rear','hloc','hpause','lloc','lpause','groom','sit'};
spikeWindow = 0.3;
sampleRate = 30;
sampleRateTPD = 250;
phzBins = -pi:pi/4:pi;
phzBinCenters = sum([phzBins(1:end-1);phzBins(2:end)])'./2
smoothingWeights = [250.^2,250.^2, 0.4.^2, 0.4.^2];
interpParPfs = struct('bins',{{linspace(-500,500,50),...
                               linspace(-500,500,50),...
                               linspace(  -2,  0.8,50),...
                               linspace(  -0.8,2,  50)}},...
                      'nanMaskThreshold', 0.1,...
                      'methodNanMap',     'linear',...
                      'methodRateMap',    'linear');



% SECTION 1 ----------------------------------------------------------------------------------------
%
%  Behavior rate maps
%
%      Generate the behavior rate maps which are computed from the data within the placefield during
%  theta periods
%
%  Joint physical-behavioral rate maps
%
%      Generate the spatial-behavioral rate maps which are computed from the data within the 
%  placefield during theta periods
%


% SET analysis args
MjgER2016_figure6_args('section 1');

% GET behavior field rate map
bfrm        = cf(@(t,u)   compute_bhv_ratemaps(t,u),                 Trials, units);
bfrmShuff   = cf(@(t,u)   compute_bhv_ratemaps_shuffled(t,u),        Trials, units);

% GET bhv ratemap erpPCA
[eigVecs, eigScrs, eigVars, unitSubsets, validDims, zrmMean, zrmStd] = ...
    compute_bhv_ratemaps_erpPCA(bfrm, units);

cluSessionMapSubset = cluSessionMap(unitSubsets,:);

% GET bhv ratemap erpPCA scores
[fsrcz,FSrC,rmaps,FSCFr,FSrM,FSrS,fsrsMean,fsrsStd,rmapsShuffledMean,rmapsShuffled] = ...
    compute_bhv_ratemaps_erpPCA_scores(Trials,units,bfrm,bfrmShuff,eigVecs,validDims,unitSubsets,false);

% MAKE bhv ratemap mask
maskbhv = false(bfrm{1}.adata.binSizes');
maskbhv(validDims) = true;


% SELECT trial subset
tind = [3:5,17:23];
Trials = Trials(tind);
units  = units(tind);
numTrials = numel(Trials);

stc  = cf(@(t)                                                                    ...
          t.load('stc','msnn_ppsvd_raux'),                                        ...
          Trials);

% GET xyhb placefields
dc4.pfs  = cf(@(t,u)  compute_xyhb_ratemaps(t,u),  Trials, units);
% MAKE xy ratemap mask
maskcirc = create_tensor_mask(dc4.pfs{1}.adata.bins(1:2));



% MAKE xyhb ratemap mask
% $$$ mask = repmat(maskcirc,[1,1,size(maskbhv)]).*repmat(permute(maskbhv,[3,4,1,2]),[size(maskcirc),1,1]);
%save(fullfile(MTA_PROJECT_PATH,'analysis','pfsXYHB_mask.mat'),'mask','-v7.3');
% LOAD xyhb ratemap mask
load(fullfile(MTA_PROJECT_PATH,'analysis','pfsXYHB_mask.mat'));


%%%<<< DIAGNOSTIC FIGURE
% $$$ rmp = plot(pfsXYHB{1},61,1,[],[],false);
% $$$ % CHECK mask is correct
% $$$ nx = pfsXYHB{1}.adata.binSizes(1);
% $$$ ny = pfsXYHB{1}.adata.binSizes(2);
% $$$ figure,
% $$$ nx = size(mask,1);
% $$$ ny = size(mask,2);
% $$$ sp = reshape(tight_subplot(ny,nx,0,0)',[ny,nx])';
% $$$ for x = 1:nx,
% $$$     for y = 1:ny,
% $$$         axes(sp(x,y));
% $$$         imagescnan(sq(mask(x,y,:,:))'.*sq(rmp(x,y,:,:))'); 
% $$$         axis('xy')
% $$$     end
% $$$ end
%%%>>>



%%%<<< DECODE xy 300ms window
dc2.tag = 'xy_sr30_sw300_HighRes';
dc2.sampleRate = 30;
dc2.mask = maskcirc;
dc2.smoothingWeights = [250.^2,250.^2];

% GET subject position objects
dc2.xyz = cf(@(t)                                                               ...
              preproc_xyz( t, 'trb', sampleRate),                               ...
              Trials);

% GET spike time objects
dc2.spk = cf(@(t,x,u)                                                           ...
              create( copy(t.spk), t, x.sampleRate, '', u, 'deburst'),          ...
              Trials, dc2.xyz, units);

% GET unit firing rate objects
dc2.ufr = cf(@(t,x,u,s)                                                         ...
              t.load('ufr',x,s,u,spikeWindow,true,'gauss'),                     ...
              Trials, dc2.xyz, units, dc2.spk);

% GET placefield ratemap objects
dc2.pfs = cf(@(t,u)                                                             ...
              compute_ratemaps(t,u),                                            ...
              Trials, units);

% GET unit inclusion 
dc2.uinc =  cf(@(u)                                                             ...
                sum(u.data>0.2,2),                                              ...
                dc2.ufr);

% DECODE position from unit firing rate
[dc2.com, dc2.max, dc2.sax, dc2.post] =                                         ...
        cf(@(t,u,r,p)                                                           ...
           decode_ufr(t, u,                                                     ...
                      dc2.sampleRate,                                           ...
                      r, p, [],                                                 ...
                      dc2.mask,                                                 ...
                      dc2.smoothingWeights,                                     ...
                      'tag',dc2.tag),                                           ...
           Trials, units, dc2.ufr, dc2.pfs);

% GET state matrix synced with dc2.xyz objects
dc2.stcm = cf(@(s,x)                                                            ...
               stc2mat(s,x,states),                                             ...
               stc, dc2.xyz);
%%%>>>


%%%<<< DECODE xyhb 300ms window 
% LOAD decoded position based on low sampleRate and full theta phase
dc4.tag = 'xy_sr30_HighRes';
dc4.sampleRate = dc2.sampleRate;
dc4.mask = mask;
dc4.smoothingWeights = [250.^2,250.^2, 0.4.^2, 0.4.^2];
dc4.stcm = dc2.stcm;
[dc4.com, dc4.max, dc4.sax, dc4.post] =                                         ...
        cf(@(t,u,r,p)                                                           ...        
           decode_ufr(t, u,                                                     ...
                      sampleRate,                                               ...
                      r, p, [],                                                 ...
                      dc4.mask, dc4.smoothingWeights,                           ...
                      'tag',dc4.tag),                                           ...
           Trials,units,dc2.ufr,dc4.pfs);
%%%>>>

dc4.fet = cf(@(t)  fet_HB_pitchB(t,dc4.sampleRate),  Trials);

dc2.error.xy   = cf(@(c,x)                                                      ...
                     sqrt( sum(( c(:,[1,2])-sq( x(:,'nose',[1,2]))).^2,2)),     ...
                     dc2.com, dc2.xyz);
dc4.error.xy = cf(@(c,x)                                                        ...
                     sqrt( sum(( c(:,[1,2])-sq( x(:,'nose',[1,2]))).^2,2)),     ...
                     dc4.com, dc2.xyz);
dc4.error.hp = cf(@(c,f)                                                        ...
                     c(:,3)-sq(f(:,1)),                                         ...
                     dc4.com, dc4.fet);
dc4.error.bp = cf(@(c,f)                                                        ...
                     c(:,4)-sq(f(:,2)),                                         ...
                     dc4.com,dc4.fet);
dc4.error.hb = cf(@(c,f)                                                        ...
                  sqrt( sum((c(:,[3,4])-f(:,[1,2])).^2,2)),                     ...
                  dc4.com,dc4.fet);




%figure,
out = cf(@(e4,e2,i) ...
         hist2(mud([e4(i),e2(i)]),50,50),...
         dc4.error.xy,dc2.error.xy,ind);
figure();
    imagesc(sum(cat(3,out{:}),3)');
    axis('xy');
    caxis([0,1000])

figure();
    for s = 1:numTrials,
        subplot(2,5,s),
        imagesc(out{s}');
        axis('xy');
        line([0,800],[0,800],'Color','r');    
    end




ind = cf(@(s,u,p,phb)                                            ...
         s(:,1)==1                                               ...
           & any(s(:,3:6),2)                                     ...
           & u>1                                                 ...
           & p>0.0005                                            ...
           & phb>0.0005,                                         ...
         dc2.stcm,dc2.uinc,dc2.post,dc4.post);


% $$$ ind = cf(@(s,u,p,phb)                                            ...
% $$$          s(:,1)==1                                               ...
% $$$            & any(s(:,3:6),2)                                     ...
% $$$            & u>1                                                 ...
% $$$            & p>0.0005                                            ...
% $$$            & phb>0.0005,                                         ...
% $$$          dc2.stcm,dc2.uinc,dc2.post,dc4.post);

% $$$ figure,
% $$$     subplot(211);
% $$$         histogram(dc2.error.xy(ind),...
% $$$                   0:10:500);
% $$$     subplot(212);
% $$$         histogram(dc4.error.xy(ind),...
% $$$                   0:10:500);
% $$$ 
% $$$         
% $$$ [median(dc2.error.xy(ind)),median(dc4.error.xy(ind))]
% $$$ [std(nonzeros(  dc2.error.xy(ind).*double(0.5 < rand([sum(ind),1])))),...
% $$$  std(nonzeros(dc4.error.xy(ind).*double(0.5 < rand([sum(ind),1]))))]
% $$$ 
% $$$ [p,h] = ranksum(  dc2.error.xy(ind),...
% $$$                 dc4.error.xy(ind))

uincBin = 0:26;
xyeBin = 0:2.5:300;
hpeBin = -1:0.05:1;
bpeBin = -1:0.05:1;
hbeBin = 0:0.01:1;
xyBin = -500:50:500;
hpBin = -2:0.1:0.5;
bpBin = -0.5:0.1:2;

ddz        = cf(@(t,u,p)                                        ...
                compute_ddz(t,u,p,'sampleRate',dc2.sampleRate), ...
                Trials, units, dc2.pfs);

% for each trial
    %for each time point:
    %    identify the units within 20cm radius
    %    compute unit composition
    

cFSrC = bsxfun(@plus,FSrC(:,[1:3]),[0.5,1.5,1.5]);
figure,
plot3(cFSrC(:,1),cFSrC(:,2),cFSrC(:,3),'.');
hold('on');
line([0,3],[0,3],[0,3],'Color','r')

rvec = [1/sqrt(numel(cvec)).*ones(size(cvec))]';

zang = repmat({[]},size(dc2.xyz));
for t = 1:numel(tind),
    ti = tind(t);
    for s = find(ind{t})',
        usub = units{t}(abs(ddz{t}(s,:))<200);
        zvec = cFSrC( ismember( cluSessionMapSubset,               ...
                                [repmat(ti,[numel(usub),1]),usub'],...
                                'rows'),                           ...
                      1:3);
        if size(zvec,1) < 3,
            zang{t}(end+1) = 0;
            continue;
        else,
            zvec = sum(bsxfun(@rdivide,zvec,sqrt(sum(zvec.^2,2))));
            zang{t}(end+1) = acos((zvec * rvec)./sqrt( sum( zvec.^2, 2)));            
        end
    end
end


%cf(@(d,u,ti) ismember(cluSessionMapSubset,[ti.*ones(sum(d<200,2),1),u(d<200) , mat2cell(tind,1,ones(size(tind)))

uincInd    = cf(@(u) discretize(u,uincBin),                    dc2.uinc);
xyInd      = cf(@(x) discretize(sq(x(:,'hcom',[1,2])), xyBin), dc2.xyz );
xyInd      = cf(@(x) discretize(sq(x(:,'hcom',[1,2])), xyBin), dc2.xyz );
hpInd      = cf(@(h) discretize(h(:,1), hpBin), dc4.fet);
bpInd      = cf(@(b) discretize(b(:,2), bpBin), dc4.fet);

% XY - xy error
dc2.xyEInd = cf(@(e)  discretize(e, xyeBin),  dc2.error.xy);
dc4.xyEInd = cf(@(e)  discretize(e, xyeBin),  dc4.error.xy);
% XYHB - hp and bp error
dc4.hpEInd = cf(@(e)  discretize(e, hpeBin),  dc4.error.hp);
dc4.bpEInd = cf(@(e)  discretize(e, bpeBin),  dc4.error.bp);
dc4.hbEInd = cf(@(e)  discretize(e, hbeBin),  dc4.error.hb);

jind = cf(@(ei1,ei2,hpi,bpi,hbi,u,s)                              ...
         s(:,1)==1 & any(s(:,3:6),2)                           ...
           & nniz(ei1) & nniz(ei2)                             ...
           & nniz(hpi) & nniz(bpi)                             ...
           & nniz(hbi) & nniz(u),                              ...
         dc2.xyEInd, dc4.xyEInd,                               ...
           dc4.hpEInd, dc4.bpEInd,                             ...
           dc4.hbEInd, uincInd, dc2.stcm);

JPDF_d2xyErr_Uinc =                                             ...
    cf(@(x,u,i)                                                 ...
       accumarray([x(i),u(i)],                                  ...
                  1,                                            ...
                  [numel(xyeBin)-1,numel(uincBin)-1],           ...
                  @sum,nan),                                        ...
       dc2.xyEInd, uincInd, jind);

JPDF_d4xyErr_Uinc =                                             ...
    cf(@(x,u,i)                                                 ...
       accumarray([x(i),u(i)],                                  ...
                  1,                                            ...
                  [numel(xyeBin)-1,numel(uincBin)-1],           ...
                  @sum,nan),                                        ...
       dc4.xyEInd, uincInd, jind);



JPDF_d4hpErr_Uinc =                                             ...
    cf(@(hp,u,i)                                                ...
       accumarray([hp(i),u(i)],                                 ...
               1,                                               ...
               [numel(hpeBin)-1,numel(uincBin)-1],              ...
               @sum,nan),                                           ...
       dc4.bpEInd, uincInd, jind);


JPDF_d4bpErr_Uinc =                                             ...
    cf(@(bp,u,i)                                                ...
       accumarray([bp(i),u(i)],                                 ...
               1,                                               ...
               [numel(bpeBin)-1,numel(uincBin)-1],              ...
               @sum,nan),...
       dc4.hpEInd, uincInd, jind);

JPDF_d4hbErr_Uinc =                                             ...
    cf(@(hb,u,i)                                                ...
       accumarray([hb(i),u(i)],                                 ...
               1,                                               ...
               [numel(hbeBin)-1,numel(uincBin)-1],              ...
               @sum,nan),...
       dc4.hbEInd, uincInd, jind);

% $$$ CONEXP_d4hbErr_Uinc_post =                                      ...
% $$$     cf(@(hb,u,i)                                                ...
% $$$        accumarray([hb(i),u(i)],                                 ...
% $$$                dc4.post,                                        ...
% $$$                [numel(bpeBin)-1,numel(uincBin)-1],              ...
% $$$                @sum,nan),...
% $$$        dc4.hbEInd, uincInd, nind,ind);



JPDF_d4xyErr_d4hbErr =                                          ...
    cf(@(x,h,i)                                                 ...
       accumarray([x(i),h(i)],                                  ...
                  1,                                            ...
                  [numel(xyeBin)-1,numel(hbeBin)-1],           ...
                  @sum,nan),                                    ...
       dc4.xyEInd, dc4.hbEInd, jind);

y = 1;

JPDF_d4xyErr_d4hbErr_gfltr = imgaussfilt(sum(cat(3, JPDF_d4xyErr_d4hbErr{:}),3,'omitnan'),2);
JPDF_d4xyErr_d4hbErr_gfltr = JPDF_d4xyErr_d4hbErr_gfltr./sum(nonzeros())
figure();
    colormap('jet');
    imagesc(xyeBinCenters./10,                              ...
            hbeBinCenters,                                 ...
            );
        axis('xy');




xyeBinCenters  = (xyeBin(1:end-1)+xyeBin(2:end))./2;
uincBinCenters = (uincBin(1:end-1)+uincBin(2:end))./2;
hpeBinCenters  = (hpeBin(1:end-1)+hpeBin(2:end))./2;
bpeBinCenters  = (bpeBin(1:end-1)+bpeBin(2:end))./2;
hbeBinCenters  = (hbeBin(1:end-1)+hbeBin(2:end))./2;

y = 1;
figure();
colormap('jet');
    subplot2(5,2,y,1);
        imagesc(xyeBinCenters./10,                              ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d2xyErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;
    subplot2(5,2,y,1);
        imagesc(xyeBinCenters./10,                              ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4xyErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;                
    subplot2(5,2,y,1);
        imagesc(hbeBinCenters,                                  ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4hbErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;        
    subplot2(5,2,y,1);
        imagesc(hpeBinCenters,                                  ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4hpErr_Uinc{:}),3,'omitnan')');
        axis('xy');
        y = y+1;
    subplot2(5,2,y,1);
        imagesc(bpeBinCenters,                                  ...
                uincBinCenters,                                 ...
                sum(cat(3, JPDF_d4bpErr_Uinc{:}),3,'omitnan')');
        axis('xy');

% $$$ t = 9;
% $$$ figure,subplot(211);plot(dc4.fet{t}(:,1)),hold on,plot(dc4.com{t}(:,3)); 
% $$$       subplot(212);plot(dc4.fet{t}(:,2)),hold on,plot(dc4.com{t}(:,4));
% $$$ linkaxes(findobj(gcf(),'Type','Axes'),'x');
       
CONEXP_xy_hbErr =                                               ...
    cf(@(xy,bp,u,i)                                             ...
       accumarray([xy(i,1),xy(i,2)],                            ...
                  hbeBin(bp(i)),                                ...
                  [numel(xyBin)-1,numel(xyBin)-1],              ...
                  @mean,                                        ...
                  NaN),                                         ...
       xyInd, dc4.hpEInd, uincInd, ind);

CONSTD_xy_hbErr =                                               ...
    cf(@(xy,bp,u,i)                                             ...
       accumarray([xy(i,1),xy(i,2)],                            ...
                  hbeBin(bp(i)),                                ...
                  [numel(xyBin)-1,numel(xyBin)-1],              ...
                   @std,                                        ...
                  NaN),                                         ...
       xyInd, dc4.hpEInd, uincInd, ind);
             
figure();
for s = 1:numTrials,
    subplot2(2,numTrials,1,s);
    imagescnan({linspace(-500,500,numel(xyBin)-1),              ...
                linspace(-500,500,numel(xyBin)-1),              ...
                CONEXP_xy_hbErr{s}'},                           ...
               [-0.75,0.75],                                    ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
    
    subplot2(2,numTrials,2,s);
    imagescnan({linspace(-500,500,numel(xyBin)-1),              ...
                linspace(-500,500,numel(xyBin)-1),              ...
                CONSTD_xy_hbErr{s}'},                           ...
               [0,0.5],                                         ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
end




nind = cf(@(ei1,ei2,hpi,bpi,hbi,hp,bp,u,s)                              ...
         s(:,1)==1 & any(s(:,2:6),2)                           ...
           & nniz(ei1) & nniz(ei2)                             ...
           & nniz(hpi) & nniz(bpi)                             ...
           & nniz(hbi) & nniz(u)...
           & nniz(hp)  & nniz(bp),                              ...
         dc2.xyEInd, dc4.xyEInd,                               ...
           dc4.hpEInd, dc4.bpEInd,                             ...
           dc4.hbEInd, hpInd, bpInd, ...
           uincInd, dc2.stcm);

CONEXP_hb_xyErr =                                               ...
    cf(@(hp,bp,xye,u,i)                                         ...
       accumarray([hp(i), bp(i)],                               ...
                  xyeBin(xye(i)),                               ...
                  [numel(hpBin)-1,numel(bpBin)-1],              ...
                  @mean,                                        ...
                  NaN),                                         ...
       hpInd, bpInd, dc4.xyEInd, uincInd, nind);
CONSTD_hb_xyErr =                                               ...
    cf(@(hp,bp,xye,u,i)                                         ...
       accumarray([hp(i), bp(i)],                               ...
                  xyeBin(xye(i)),                               ...
                  [numel(hpBin)-1,numel(bpBin)-1],              ...
                  @std,                                         ...
                  NaN),                                         ...
       hpInd, bpInd, dc4.xyEInd, uincInd, nind);

figure();
for s = 1:numTrials,
    subplot2(2,numTrials,1,s);
    imagescnan({linspace([hpBin([1,end]),numel(hpBin)-1]),      ...
                linspace([bpBin([1,end]),numel(bpBin)-1]),      ...
                CONEXP_hb_xyErr{s}'},                           ...
               [0,200],                                         ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
    axis('xy');
    
    subplot2(2,numTrials,2,s);
    imagescnan({linspace([hpBin([1,end]),numel(hpBin)-1]),      ...
                linspace([bpBin([1,end]),numel(bpBin)-1]),      ...
                CONSTD_hb_xyErr{s}'},                           ...
               [0,100],                                         ...
               'linear',                                        ...
               true,                                            ...
               [0.2,0.2,0.2],                                   ...
               [],[],@jet);
    axis('xy');
end









% DCTPD 
% LOAD decoded position based on high sampleRate and binned by theta phase
decEstComTPD     = cell([1,numTrials]);
decEstMaxTPD     = cell([1,numTrials]);
decEstSaxTPD     = cell([1,numTrials]);
posteriorMaxTPD  = cell([1,numTrials]);
unitInclusionTPD = cell([1,numTrials]);
dc4.xyz  = cf(@(t)     resample(preproc_xyz(t,'trb'),sampleRateTPD),      Trials);
for t = 1:numTrials
    Trials{t}.lfp.filename = [Trials{t}.name,'.lfp'];    

    try,   lfp = load(Trials{t},'lfp',sessionList(t).thetaRefGeneral);
    catch, lfp = load(Trials{t},'lfp',sessionList(t).thetaRefGeneral);
    end
    % PHZ : LFP phase restricted to the theta band [6-12Hz]
    phz = lfp.phase([6,12]);
    phzBinInds = discretize(phz.data,phzBins);
    spk  = create(copy(Trials{t}.spk),Trials{t},lfp.sampleRate,'',units{t},'deburst');
    for p = 1:numel(phzBins)-1
        spkt = copy(spk);
        spkt.clu = spkt.clu(phzBinInds(spkt.res)==p);
        spkt.res = round(spkt.res(phzBinInds(spkt.res)==p)./lfp.sampleRate.*sampleRateTPD);    
        spkt.sampleRate = sampleRateTPD;
        ufr = Trials{t}.load('ufr',xyz{t},spkt,units{t},spikeWindow,true,'gauss');
        ufr.data =  ufr.data.*6;
        unitInclusionTPD{t}(:,p) = sum(ufr.data>0.2,2);
        tag = ['xyhb_thpD',num2str(sampleRateTPD),'_',num2str(p),'o',num2str(numel(phzBins)-1)];
        [decEstComTPD{t}(:,:,p),decEstMaxTPD{t}(:,:,p),...
         decEstSaxTPD{t}(:,:,p),posteriorMaxTPD{t}(:,p)] = ...
            decode_ufr(Trials{t},units{t},sampleRateTPD,ufr,pfsXYHB{t},...
                       [],mask,smoothingWeights,'tag',tag,'overwrite',false);
    end
end




% COMPILE egocentric variables 
fet  = cf(@(t)    fet_HB_pitchB(t,sampleRateTPD),                                    Trials(tind));
hvec = cf(@(x)    x(:,'head_front',[1,2])-x(:,'head_back',[1,2]),                    xyz          );
hvec = cf(@(h)    sq(bsxfun(@rdivide,h,sqrt(sum(h.^2,3)))),                          hvec         );
hvec = cf(@(h)    cat(3,h,sq(h)*[0,-1;1,0]),                                         hvec         );
tvec = cf(@(x)    circshift(x(:,'hcom',[1,2]),-1)-circshift(x(:,'hcom',[1,2]),1),    xyz          );
tvec = cf(@(h)    sq(bsxfun(@rdivide,h,sqrt(sum(h.^2,3)))),                          tvec         );
tvec = cf(@(h)    cat(3,h,sq(h)*[0,-1;1,0]),                                         tvec         );
stc  = cf(@(t)    t.load('stc','msnn_ppsvd_raux'),                                   Trials(tind));
stcm = cf(@(s,x)  stc2mat(s,x,states),                                               stc,   xyz   );

% COMPUTE error
dErr = decEstComTPD;
%dErr = decEstSaxTPD;
%dErr = decEstMaxTPD;
dErr = cf(@(e,x,h,f)  cat(2,...
                          sq(multiprod(permute(bsxfun(@minus,...
                                                  e(:,[1,2],:),...
                                                  sq(x(:,'hcom',[1,2]))),...
                                           [1,2,4,3]),...
                                   h(:,:,:),2,[2,3])),...
                          [bsxfun(@minus,f(:,1),e(:,3,:)),bsxfun(@minus,f(:,2),e(:,4,:))]), ...
          dErr,xyz,hvec,fet);




%%%<<< COMPUTE error for TDP decoding per state
stid = [1,2,3,4,5,6];
dcTDPfrontal = repmat({cell([1,numTrials])},[1,numel(stid)]);
dcTDPlateral = repmat({cell([1,numTrials])},[1,numel(stid)]);
indTDP = cell([1,numel(stid)]);
errorBinEdges = linspace(-500,500,100);      
errorBinCenters = mean(GetSegs(errorBinEdges,1:numel(errorBinEdges)-1,2));
for sts = 1:numel(stid),
    indTDP{sts}  = cf(@(p,u,s)                                           ...
                      all(p>0.0005,2)                                    ...
                      & sum(double(u>=1),2)>6                            ...
                      & s(:,1)==1                                        ...
                      & any(logical(s(:,stid(sts))),2)                   ...
                      & ~any(logical(s(:,[7,8])),2),                     ...
                      posteriorMaxTPD,unitInclusionTPD,stcm);
    for t = 1:numel(Trials),
        for j = 1:numel(phzBins)-1;
            dcTDPfrontal{sts}{t} =                                             ...
                cat(2,                                                          ...
                    dcTDPfrontal{sts}{t},                                      ...
                    histcounts(sq(dErr{t}(indTDP{sts}{t},1,j)),errorBinEdges)');
            dcTDPlateral{sts}{t} =                                             ...
                cat(2,                                                          ...
                    dcTDPlateral{sts}{t},                                      ...
                    histcounts(sq(dErr{t}(indTDP{sts}{t},2,j)),errorBinEdges)');
        end
    end
end
%%%>>>


%%%<<< COMPUTE error for TDP decoding per state
pbound =[-1.25,1.25];
stid = [1,2,3,4,5,6];
dcTDPfrontal = repmat({cell([1,numTrials])},[1,numel(stid)]);
dcTDPlateral = repmat({cell([1,numTrials])},[1,numel(stid)]);
dcTDPhp = repmat({cell([1,numTrials])},[1,numel(stid)]);
dcTDPbp = repmat({cell([1,numTrials])},[1,numel(stid)]);
indTDP = cell([1,numel(stid)]);
errorBinEdges = linspace(-500,500,100);      
errorBinCenters = mean(GetSegs(errorBinEdges,1:numel(errorBinEdges)-1,2));
perrorBinEdges = linspace([pbound,50]);      
perrorBinCenters = mean(GetSegs(perrorBinEdges,1:numel(perrorBinEdges)-1,2));

for sts = 1:numel(stid),
    indTDP{sts}  = cf(@(p,u,s)                                           ...
                      all(p>0.0007,2)                                    ...
                      & sum(double(u>=3),2)>6                            ...
                      & s(:,1)==1                                        ...
                      & any(logical(s(:,stid(sts))),2)                   ...
                      & ~any(logical(s(:,[7,8])),2),                     ...
                      posteriorMaxTPD,unitInclusionTPD,stcm);
    for t = 1:numel(Trials),
        for j = 1:numel(phzBins)-1;
            dcTDPfrontal{sts}{t} =                                               ...
                cat(2,                                                           ...
                    dcTDPfrontal{sts}{t},                                        ...
                    histcounts(sq(dErr{t}(indTDP{sts}{t},1,j)),errorBinEdges)');
            dcTDPlateral{sts}{t} =                                               ...
                cat(2,                                                           ...
                    dcTDPlateral{sts}{t},                                        ...
                    histcounts(sq(dErr{t}(indTDP{sts}{t},2,j)),errorBinEdges)');
            dcTDPhp{sts}{t} =                                               ...
                cat(2,                                                           ...
                    dcTDPhp{sts}{t},                                        ...
                    histcounts(sq(dErr{t}(indTDP{sts}{t},3,j)),perrorBinEdges)');
            dcTDPbp{sts}{t} =                                               ...
                cat(2,                                                           ...
                    dcTDPbp{sts}{t},                                        ...
                    histcounts(sq(dErr{t}(indTDP{sts}{t},4,j)),perrorBinEdges)');
        end
    end
end
%%%>>>

dErrlon = cf(@(e) reshape( sq(e(:,1,:))', [], 1), dErr);
dErrlat = cf(@(e) reshape( sq(e(:,2,:))', [], 1), dErr);
dErrhp  = cf(@(e) reshape( sq(e(:,3,:))', [], 1), dErr);
dErrbp  = cf(@(e) reshape( sq(e(:,4,:))', [], 1), dErr);
dstcm   = cf(@(s) reshape( permute( repmat( s, [1,1,8]),[2,3,1]),  8,[])', stcm);
dphz    = cf(@(e) reshape( repmat( phzBinCenters',[size(e,1),1])', [], 1), dErr);
duinc   = cf(@(u) reshape( u', [], 1), unitInclusionTPD);
dpost   = cf(@(p) reshape( p', [], 1), posteriorMaxTPD);
duincI  = cf(@(u) reshape( repmat( sum(double(u>=3),2)>6,[1,8])',[],1), unitInclusionTPD);
dpostI  = cf(@(p) reshape( repmat( all(p>0.00075,2),[1,8])',[],1), posteriorMaxTPD);

dtind  = cf(@(p,t)  repmat(t.*ones([size(p,1),1]),[8,1]), posteriorMaxTPD,num2cell(tind));

dErrlon = cat( 1, dErrlon{:} );
dErrlat = cat( 1, dErrlat{:} );
dErrhp  = cat( 1, dErrhp{:} );
dErrbp  = cat( 1, dErrbp{:} );
dstcm   = cat( 1, dstcm{:}  );
dphz    = cat( 1, dphz{:}   );
duinc   = cat( 1, duinc{:}  );
dpost   = cat( 1, dpost{:}  );
duincI  = cat( 1, duincI{:} );
dpostI  = cat( 1, dpostI{:} );
dtind   = cat( 1, dtind{:}  );


% permutation test of the mutual information of the joint distribution between longitudinal error 
% and theta phase. 

sum(logical(dstcm(:,1)) & ~any(logical(dstcm(:,[7,8])),2))



Ixy  = zeros([100,6,6]);
Ixyr = zeros([100,6,6]);
for i = 1:100,
    for sts = 1:6,
        ind =   logical(dstcm(:,1))                             ...
                & logical(dstcm(:,sts))                         ...
                & ~any(logical(dstcm(:,[7,8])),2)               ...
                & dpostI                                        ...
                & duincI;        
        ind(ind) = randn([sum(ind),1]) > 1;        
        si = sum(ind);
        for sto = 1:6,    
            tic
            indo =   logical(dstcm(:,1))                        ...
                     & logical(dstcm(:,sto))                    ...
                     & ~any(logical(dstcm(:,[7,8])),2)          ...
                     & dpostI                                   ...
                     & duincI;        
            indo(indo) = randn([sum(indo),1]) > 1;
            so = sum(indo);

            indb = find(ind | indo);
            indb = randsample(indb,sum([si,so].*double([sts>sto,sts<=sto])));
            
            px  = histcounts(dErrlon(indb),                     ...
                             errorBinEdges,                     ...
                             'Normalization','probability');
            py  = histcounts(dphz(indb),                        ...
                             phzBins,                           ...
                             'Normalization','probability');
            pxy = histcounts2(dErrlon(indb),                    ...
                              dphz(indb),                       ...
                              errorBinEdges,                    ...
                              phzBins,                          ...
                              'Normalization','probability');
            Ixy(i,sts) = sum(nonzeros(pxy.*log(pxy./bsxfun(@times,px',py))),'omitnan');
            
            rndPhz = dphz(indb)+randn([numel(indb),1])*2;
            rndPhz( rndPhz < -pi ) = rndPhz( rndPhz < -pi ) + 2.*pi;
            rndPhz( rndPhz >  pi ) = rndPhz( rndPhz >  pi ) - 2.*pi;
            py  = histcounts(rndPhz,                            ...
                             phzBins,                           ...
                             'Normalization','probability');
            pxy = histcounts2(dErrlon(indb),                    ...
                              rndPhz,                           ...
                              errorBinEdges,                    ...
                              phzBins,                          ...
                              'Normalization','probability');
            Ixyr(i,sts,sto) = sum(nonzeros(pxy.*log(pxy./bsxfun(@times,px',py))),'omitnan');
            toc
        end
    end
end


figure,hold('on');
histogram(log10(Ixyr(:,1)),linspace(-4,-1,100))
hist(log10(Ixy(:,1)),linspace(-4,-1,100))



% $$$ indTDP{sts}  = cf(@(p,u,s)                                           ...
% $$$                   all(p>0.0005,2)                                    ...
% $$$                   & sum(double(u>=3),2)>6                            ...
% $$$                   & s(:,1)==1                                        ...
% $$$                   & any(logical(s(:,stid(sts))),2)                   ...
% $$$                   & ~any(logical(s(:,[7,8])),2),                     ...
% $$$                   posteriorMaxTPD,unitInclusionTPD,stcm);





%%%<<< COMPUTATION : find ridge values for each state's dcTDPfrontal error as function of theta phz
dcTpdLongSum = {};
dcTpdhpSum = {};
dcTpdbpSum = {};
dcTpdInd = [];
dcTpdWmn = [];
dcTpdMax = [];
for sts = 1:numel(stid),
    dcTpdLongSum{sts} = RectFilter(sum(cat(3,dcTDPfrontal{sts}{:}),3),5,3);
    dcTpdLongSum{sts} = bsxfun(@rdivide,dcTpdLongSum{sts},sum(dcTpdLongSum{sts}));
    [~, dcTpdInd(end+1,:)] = max(dcTpdLongSum{sts});
    dcTpdMax(end+1,:) = errorBinCenters(dcTpdInd(end,:)');    
    dcTpdWmn(end+1,:) = sum(bsxfun(@times,dcTpdLongSum{sts},errorBinCenters'))';
    
    dcTpdhpSum{sts} = RectFilter(sum(cat(3,dcTDPhp{sts}{:}),3),5,3);
    dcTpdhpSum{sts} = bsxfun(@rdivide,dcTpdhpSum{sts},sum(dcTpdhpSum{sts}));
    
    dcTpdbpSum{sts} = RectFilter(sum(cat(3,dcTDPbp{sts}{:}),3),5,3);
    dcTpdbpSum{sts} = bsxfun(@rdivide,dcTpdbpSum{sts},sum(dcTpdhpSum{sts}));
end
%%%>>>



%%%<<< LOAD example data
t = 20;
Trial = Trials{t};
unitSubset = units{t};
exyz = resample(Trial.load('xyz','trb'),30);
%efet = fet_HB_pitchB(Trial,sampleRate);
efet = resample(copy(fet{tind==t}),sampleRate);
ets = [1:size(exyz,1)]./sampleRate;
estcm = stc2mat(Trial.load('stc'),exyz,states);
eind =   posteriorMax{t==tind} > 0.001 ...
       & unitInclusion{t==tind} > 3     ...
       & estcm(:,1)==1;
enanmask = ones([size(exyz,1),1]);
enanmask(~eind)=nan;


%%%>>>

% STARTFIG -----------------------------------------------------------------------------------------


eTS = [290,345];
%eTS = [530,600];
%eTS = [1000,1045];
eInds = round(eTS.*sampleRate)+1;
eInds = [eInds(1):eInds(2)]';
eIndsSub = eInds(1300:1600);


[hfig,fig,fax,sax] = set_figure_layout(figure(666006),'A4','portrait',[],1.5,1.5,0,0.2);


%%%<<< PLOT example trajectory within physical space
% ADJUST subplot coordinates
t = 20; 
[yind, yOffSet, xind, xOffSet] = deal(1,-fig.subplot.height, 1, 0);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*2,                        ...
                              fig.subplot.height*2],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold(sax(end),'on');
imagesc(pfsXYHB{1}.adata.bins{1:2},~maskcirc');
vcolormap(sax(end),'gray')
caxis(sax(end),[-2,1])

circle(0,0,480,'-k');
plot(exyz(eIndsSub,5,1),...
     exyz(eIndsSub,5,2),...
     '-k','LineWidth',1);
plot(sq(decEstCom{t==tind}(eIndsSub,1)).*enanmask(eIndsSub),...
     sq(decEstCom{t==tind}(eIndsSub,2)).*enanmask(eIndsSub),...
     '-c','LineWidth',1);
xlim([-500,500]);
ylim([-500,500]);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT example trajectory within behavior space
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(3, -fig.subplot.height, 1, 0);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*2,                        ...
                              fig.subplot.height*2],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold(sax(end),'on');
imagesc(pfsXYHB{1}.adata.bins{3:4},~maskbhv');
colormap(sax(end),'gray')
caxis(sax(end),[-2,1])

axis('xy');
plot(efet(eIndsSub,1),...
     efet(eIndsSub,2),...
     '-k','LineWidth',1);
plot(sq(decEstCom{t==tind}(eIndsSub,3)).*enanmask(eIndsSub),...
     sq(decEstCom{t==tind}(eIndsSub,4)).*enanmask(eIndsSub),...
     '-c','LineWidth',1);
xlim(sax(end),[-1.8,0.6]);
ylim(sax(end),[-0.6,1.8]);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT timeseries of xcoord vs decoded xcoord
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(1, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     exyz(eInds,5,1),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,1)).*enanmask(eInds),...
     '-r','LineWidth',1);
plot(ets(eIndsSub),...
     sq(decEstCom{t==tind}(eIndsSub,1)).*enanmask(eIndsSub),...
     '-c','LineWidth',1);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT timeseries of ycoord vs decoded ycoord
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(2, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     exyz(eInds,5,2),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,2)).*enanmask(eInds),...
     '-r','LineWidth',1);
plot(ets(eIndsSub),...
     sq(decEstCom{t==tind}(eIndsSub,2)).*enanmask(eIndsSub),...
     '-c','LineWidth',1);
sax(end).XTick = [];
sax(end).YTick = [];
%%%>>>


%%%<<< PLOT timeseries of head pitch vs decoded head pitch
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(3, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     efet(eInds,1),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,3)).*enanmask(eInds),...
     '-r','LineWidth',1);
plot(ets(eIndsSub),...
     sq(decEstCom{t==tind}(eIndsSub,3)).*enanmask(eIndsSub),...
     '-c','LineWidth',1);
sax(end).XTick = [];
sax(end).YTick = [];
ylim([-1.6,0.5]);
%%%>>>


%%%<<< PLOT timeseries of body pitch vs decoded body pitch
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(4, 0, 3, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width*5,                      ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
plot(ets(eInds),...
     efet(eInds,2),...
     '-k','LineWidth',1);
plot(ets(eInds),...
     sq(decEstCom{t==tind}(eInds,4)).*enanmask(eInds),...
     '-r','LineWidth',1);
plot(ets(eIndsSub),...
     sq(decEstCom{t==tind}(eIndsSub,4)).*enanmask(eIndsSub),...
     '-c','LineWidth',1);

sax(end).YTick = [];
ylim([-0.5,1.6]);
%%%>>>


%%%<<< PLOT spatial vs behaivoral error




%%%>>>




%%%<<< PLOT BLOCK : theta phase * decoding error
xs = 5;
%%%>>>

%%%<<< PLOT longitudinal error for TDP decoding
% SET constants
xcoords =linspace(-500,500,250);
ycoords = circ_rad2ang([phzBinCenters;phzBinCenters+2*pi]);
for sts = 1:numel(stid),
% ADJUST subplot coordinates    
    [yind, yOffSet, xind, xOffSet] = deal(4+sts, -0.8, xs, 0);

% CREATE subplot axes
    sax(end+1) = axes('Units','centimeters',                                ...
                      'Position',[fig.page.xpos(xind)+xOffSet,              ...
                                  fig.page.ypos(yind)+yOffSet,              ...
                                  fig.subplot.width,                        ...
                                  fig.subplot.height],                      ...
                      'FontSize', 8,                                        ...
                      'LineWidth',1);
    hold(sax(end),'on');
% PLOT JPDF of longitudinal error vs theta phase
    imagesc(xcoords,                                 ...
            ycoords,       ...
            repmat(RectFilter(dcTpdLongSum{sts},5,3),1,2)')
    axis('xy');
    xl = [-200,200];
    xlim(xl);
    ylim([-60,420]);            
% MASK areas outside single cycle
    patch([xl(1),xl(1),xl(2),xl(2)],...
          [ 360, 420,420,360],...
          [0.2,0.2,0.2],...
          'EdgeAlpha',0,...
          'FaceAlpha',0.4);
    patch([xl(1),xl(1),xl(2),xl(2)],...    
          [ -60,   0,  0,-60],...
          [0.2,0.2,0.2],...
          'EdgeAlpha',0,...
          'FaceAlpha',0.4);
    sax(end).XTick = [-100,0,100];
    sax(end).XTickLabels = [-15,0,15];
    sax(end).YTick = [];    
    sax(end).XTickLabels = [];    
    Lines(0,[],'w',[],'LineWidth',1);
    plot(repmat(dcTpdMax(sts,:),[1,2])', ycoords,'k','LineWidth',2);
    %plot(repmat(dcTpdMax(sts,:),[1,2])', ycoords,'k','LineWidth',2);
    %plot(repmat(dcTpdWmn(1,:),[1,2])', ycoords,'k','LineWidth',2);    
    %plot(repmat(dcTpdWmn(sts,:),[1,2])', ycoords,'m','LineWidth',2);

    colormap(sax(end),'jet');    
    ylabel(sax(end),states{sts});
    if sts == 1,
        title(sax(end),{'RCP Error'});
    end
end

% PLOT sptial scale bar 
axes(fax);
line([sax(end).Position(1)+sax(end).Position(3)./4,sax(end).Position(1)+sax(end).Position(3).*3./4],...
     [1,1].*(sax(end).Position([2])-0.2), 'Color', 'k', 'LineWidth', 1);
text(sax(end).Position(1)+sax(end).Position(3)/2,               ...
     sax(end).Position([2])-0.4,                                ...
     '20 cm',                                                   ...
     'HorizontalAlignment','center');


%%%>>>

%%%<<< PLOT head pitch error
% SET constants
xcoords =linspace([-1.25,1.25,50]);
ycoords = circ_rad2ang([phzBinCenters;phzBinCenters+2*pi]);
% ADJUST subplot coordinates
xOffSet = -0.2;
for sts = 1:numel(stid),
% ADJUST subplot coordinates    
    [yind, yOffSet, xind, xOffSet] = deal(4+sts, -0.8, xs+1, 0.2);
% CREATE subplot axes
    sax(end+1) = axes('Units','centimeters',                                ...
                      'Position',[fig.page.xpos(xind)+xOffSet,              ...
                                  fig.page.ypos(yind)+yOffSet,              ...
                                  fig.subplot.width,                        ...
                                  fig.subplot.height],                      ...
                      'FontSize', 8,                                        ...
                      'LineWidth',1);
    hold(sax(end),'on');
% PLOT JPDF of longitudinal error vs theta phase
    imagesc(xcoords,                                 ...
            ycoords,       ...
            repmat(RectFilter(dcTpdhpSum{sts},5,3),1,2)')
    axis('xy');
    xl = [-1.25,1.25];
    xlim(xl);
    ylim([-60,420]);            
% MASK areas outside single cycle
    patch([xl(1),xl(1),xl(2),xl(2)],...
          [ 360, 420,420,360],...
          [0.2,0.2,0.2],...
          'EdgeAlpha',0,...
          'FaceAlpha',0.4);
    patch([xl(1),xl(1),xl(2),xl(2)],...    
          [ -60,   0,  0,-60],...
          [0.2,0.2,0.2],...
          'EdgeAlpha',0,...
          'FaceAlpha',0.4);
    sax(end).XTick = [];
    sax(end).XTickLabels = [];
    sax(end).YTick = [];    
    sax(end).XTickLabels = [];    
    Lines(0,[],'w',[],'LineWidth',1);
    %plot(repmat(dcTpdMax(sts,:),[1,2])', ycoords,'k','LineWidth',2);
    %plot(repmat(dcTpdMax(sts,:),[1,2])', ycoords,'k','LineWidth',2);
    %plot(repmat(dcTpdWmn(1,:),[1,2])', ycoords,'k','LineWidth',2);    
    %plot(repmat(dcTpdWmn(sts,:),[1,2])', ycoords,'m','LineWidth',2);
    %title(states{sts});
    colormap(sax(end),'jet');    
    if sts == 1,
        %ylabel(sax(end),{'Head','Pitch'});
        title(sax(end),{'HP Error'});        
    end
    
end

% PLOT scale bar 
axes(fax);
line([sax(end).Position(1)+sax(end).Position(3).*1.5./5,        ...
      sax(end).Position(1)+sax(end).Position(3).*3.5./5],       ...
      [1,1].*(sax(end).Position([2])-0.2),                      ...
      'Color', 'k',                                             ...
      'LineWidth', 1);
text(sax(end).Position(1)+sax(end).Position(3)/2,               ...
     sax(end).Position([2])-0.5,                                ...
     '1 rad',                                                   ...
     'HorizontalAlignment','center');


%%%>>>



%%%<<< PLOT body pitch error
% SET constants

xcoords =linspace([pbound,50]);
ycoords = circ_rad2ang([phzBinCenters;phzBinCenters+2*pi]);
for sts = 1:numel(stid),
% ADJUST subplot coordinates    
    [yind, yOffSet, xind, xOffSet] = deal(4+sts, -0.8, xs+2, 0.4);
% CREATE subplot axes
    sax(end+1) = axes('Units','centimeters',                                ...
                      'Position',[fig.page.xpos(xind)+xOffSet,              ...
                                  fig.page.ypos(yind)+yOffSet,              ...
                                  fig.subplot.width,                        ...
                                  fig.subplot.height],                      ...
                      'FontSize', 8,                                        ...
                      'LineWidth',1);
    hold(sax(end),'on');
% PLOT JPDF of longitudinal error vs theta phase
    imagesc(xcoords,                                 ...
            ycoords,       ...
            repmat(RectFilter(dcTpdbpSum{sts},5,3),1,2)')
    axis('xy');
    xl = [pbound];
    xlim(xl);
    ylim([-60,420]);            
% MASK areas outside single cycle
    patch([xl(1),xl(1),xl(2),xl(2)],...
          [ 360, 420,420,360],...
          [0.2,0.2,0.2],...
          'EdgeAlpha',0,...
          'FaceAlpha',0.4);
    patch([xl(1),xl(1),xl(2),xl(2)],...    
          [ -60,   0,  0,-60],...
          [0.2,0.2,0.2],...
          'EdgeAlpha',0,...
          'FaceAlpha',0.4);
    sax(end).XTick = [];
    sax(end).XTickLabels = [];
    sax(end).YTick = [];    
    sax(end).XTickLabels = [];    
    Lines(0,[],'w',[],'LineWidth',1);
    %plot(repmat(dcTpdMax(sts,:),[1,2])', ycoords,'k','LineWidth',2);
    %plot(repmat(dcTpdMax(sts,:),[1,2])', ycoords,'k','LineWidth',2);
    %plot(repmat(dcTpdWmn(1,:),[1,2])', ycoords,'k','LineWidth',2);    
    %plot(repmat(dcTpdWmn(sts,:),[1,2])', ycoords,'m','LineWidth',2);
    %title(states{sts});
    colormap(sax(end),'jet');    
    
    if sts == 1,
        %ylabel(sax(end),{'Body','Pitch'});
        title(sax(end),{'BP Error'});        
% ADJUST subplot coordinates        
        [yind, yOffSet, xind, xOffSet] = deal(4+sts, -0.8, xs+3, 0.4);
% CREATE subplot axes
        sax(end+1) = axes('Units','centimeters',                        ...
                          'Position',[fig.page.xpos(xind)+xOffSet,      ...
                            fig.page.ypos(yind)+yOffSet,      ...
                            fig.subplot.width/1.5,              ...
                            fig.subplot.height],              ...
                          'FontSize', 8,                                ...
                          'LineWidth',1);
        hold(sax(end),'on');
% ADD phase "bar"
        plot(-cos(circ_ang2rad(-60:420)),-60:420,'-k','LineWidth',2);

        sax(end).YAxisLocation = 'right';
        sax(end).Visible = 'off';                                    
        sax(end).YTick = [];
        sax(end).YTickLabels = [];
        sax(end).XTick = [];
        ylim([-60,420]);
        xlim([-1.5,1.5]);


        text( 0.25, 360, '360', 'HorizontalAlignment','center',     ...
              'FontSize', 8, 'VerticalAlignment',  'middle');
        text(-0.25, 180, '180', 'HorizontalAlignment','center',     ...
             'FontSize', 8, 'VerticalAlignment',  'middle');                    
        text( 0.25,   0,   '0', 'HorizontalAlignment','center',     ...
              'FontSize', 8, 'VerticalAlignment',  'middle');                    
    else
% ADJUST subplot coordinates        
        [yind, yOffSet, xind, xOffSet] = deal(4+sts, -0.8, xs+3, 0.4);
% CREATE subplot axes
        sax(end+1) = axes('Units','centimeters',                        ...
                          'Position',[fig.page.xpos(xind)+xOffSet,      ...
                            fig.page.ypos(yind)+yOffSet,      ...
                            fig.subplot.width/3,              ...
                            fig.subplot.height],              ...
                          'FontSize', 8,                                ...
                          'LineWidth',1);
        hold(sax(end),'on');
% ADD phase "bar"
        plot(-cos(circ_ang2rad(-60:420)),-60:420,'-k','LineWidth',2);

        sax(end).YAxisLocation = 'right';
        sax(end).Visible = 'off';                                    
        sax(end).YTick = [];
        sax(end).YTickLabels = [];
        sax(end).XTick = [];
        ylim([-60,420]);
        xlim(pbound);
    end
    
end
% PLOT scale bar 
axes(fax);
line([sax(end-1).Position(1)+sax(end-1).Position(3).*1.5./5,        ...
      sax(end-1).Position(1)+sax(end-1).Position(3).*3.5./5],       ...
      [1,1].*(sax(end).Position(2)-0.2),                      ...
      'Color', 'k',                                             ...
      'LineWidth', 1);
text(sax(end-1).Position(1)+sax(end-1).Position(3)/2,               ...
     sax(end-1).Position(2)-0.5,                                ...
     '1 rad',                                                   ...
     'HorizontalAlignment','center');



%%%>>>

% STOPFIG ------------------------------------------------------------------------------------------


%%%<<< PLOT lateral error as function of theta phase
% ADJUST subplot coordinates
[yind, yOffSet, xind, xOffSet] = deal(5, -0.8, 2, 0.4);
% CREATE subplot axes
sax(end+1) = axes('Units','centimeters',                                ...
                  'Position',[fig.page.xpos(xind)+xOffSet,              ...
                              fig.page.ypos(yind)+yOffSet,              ...
                              fig.subplot.width,                        ...
                              fig.subplot.height],                      ...
                  'FontSize', 8,                                        ...
                  'LineWidth',1);
hold('on');
imagesc(linspace(-500,500,250),                                 ...
        circ_rad2ang([phzBinCenters;phzBinCenters+2*pi]),       ...
        repmat(sum(cat(3,dcTDPlateral{:}),3),1,2)')
axis('xy');
xlim([-200,200]);
ylim([-60,420]);            
% MASK areas outside single cycle
patch([-300,-300,300,300],...
      [ 360, 420,420,360],...
      [0.2,0.2,0.2],...
      'EdgeAlpha',0,...
      'FaceAlpha',0.4);
patch([-300,-300,300,300],...
      [ -60,   0,  0,-60],...
      [0.2,0.2,0.2],...
      'EdgeAlpha',0,...
      'FaceAlpha',0.4);
sax(end).XTick = [-150,0,150];
sax(end).XTickLabels = [-15,0,15];
%%%>>>



%%%<<< supfig
figure();
for t = 1:numTrials
    subplot2(2,numTrials,1,t);
    imagesc(linspace(-500,500,250),                             ...
            [phzBinCenters;phzBinCenters+2*pi],                 ...
            repmat(dcTDPfrontal{t},1,2)');
    axis('xy');
    xlim([-300,300]);    
    
    subplot2(2,10,2,t);
    imagesc(linspace(-500,500,250),1:8,repmat(dcTDPlateral{t},1,2)')
    axis('xy');
    xlim([-300,300]);
end
%%%>>>




    

ind  = cf(@(p,u,s) all(p>0.00005,2) & all(u>=2,2) & s(:,1)==1 & any(logical(s(:,stid)),2),...
          posteriorMaxTPD,unitInclusionTPD,stcm);


xD = linspace(-300,300,30);
yD = linspace(-300,300,30);
hD = linspace(-1.5,1.5,30);
bD = linspace(-1.5,1.5,30);

hCntXY = cf(@(e,i)  cat(3,...
                        hist2(e(i,[1,2],1),xD,yD),...
                        hist2(e(i,[1,2],2),xD,yD),...
                        hist2(e(i,[1,2],3),xD,yD),...
                        hist2(e(i,[1,2],4),xD,yD),...
                        hist2(e(i,[1,2],5),xD,yD),...
                        hist2(e(i,[1,2],6),xD,yD)),...
                        dErr,ind);
hCntXY = sum(cat(4,hCntXY{:}),4);

hCntHB = cf(@(e,i)  cat(3,...
                        hist2(e(i,[3,4],1),hD,bD),...
                        hist2(e(i,[3,4],2),hD,bD),...
                        hist2(e(i,[3,4],3),hD,bD),...
                        hist2(e(i,[3,4],4),hD,bD),...
                        hist2(e(i,[3,4],5),hD,bD),...
                        hist2(e(i,[3,4],6),hD,bD)),...
                        dErr,ind);
hCntHB = sum(cat(4,hCntHB{:}),4);

figure,
spp = gobjects([0,1]);
spb = gobjects([0,1]);
for p = 1:numel(phzBins)-1,
    spp(end+1) = subplot2(numel(phzBins)-1,2,p,1);    imagesc(xD,yD,hCntXY(:,:,p)');   axis('xy');
    spb(end+1) = subplot2(numel(phzBins)-1,2,p,2);    imagesc(hD,bD,hCntHB(:,:,p)');   axis('xy');
end
af(@(a) caxis(a,[0,120]),spp);
af(@(a) caxis(a,[0,400]),spb);



t = 3
ind{t} = ':';
figure,
subplot(4,1,1);plot([xyz{t}(ind{t},5,1),sq(dErr{t}(ind{t},1,:))]);    
subplot(4,1,2);plot([xyz{t}(ind{t},5,2),sq(dErr{t}(ind{t},2,:))]);        
subplot(4,1,3);plot([fet{t}(ind{t},1),  sq(dErr{t}(ind{t},3,:))]);
subplot(4,1,4);plot([fet{t}(ind{t},2),  sq(dErr{t}(ind{t},4,:))]);
linkaxes(findobj(gcf(),'Type','Axes'),'x');




tind = 20;
Trial = Trials{tind};
unitSubset = units{tind};
xyz = preproc_xyz(Trial,'trb');
xyz.resample(sampleRate);
fet = fet_HB_pitchB(Trial,sampleRate);
hvec = xyz(:,'head_front',[1,2])-xyz(:,'head_back',[1,2]);
hvec = sq(bsxfun(@rdivide,hvec,sqrt(sum(hvec.^2,3))));
hvec = cat(3,hvec,sq(hvec)*[0,-1;1,0]);
% CONVERT MTAStateCollection into a state matrix 
stc = Trial.load('stc','msnn_ppsvd_raux');
stcm = stc2mat(stc,xyz,states);



dfet = decEstComTPD{3};
%dfet = decEstSaxTPD{1};
decError = zeros([size(xyz{t},1),size(decEstSax{j},2),numel(phzBins)-1]);
for p = 1:numel(phzBins)-1,
    decError(:,[1,2],p) = [multiprod(dfet(:,[1,2],p)-sq(xyz{t}(:,'hcom',[1,2])),hvec{t}(:,:,:),2,[2,3])];
end            
decError(:,[3,4],:) = [bsxfun(@minus,fet{t}(:,1),dfet(:,3,:)),bsxfun(@minus,fet{t}(:,2),dfet(:,4,:))];


j = 3
ind =   all(posteriorMaxTPD{j}>0.0001,2)...
      & all(unitInclusionTPD{j}>=4,2) ...
      & stcm(:,1)==1 & any(logical(stcm(:,[3,4,5,6])),2);
figure,
spp = gobjects([0,1]);
spb = gobjects([0,1]);
for p = 1:numel(phzBins)-1,
    spp(end+1) = subplot2(numel(phzBins)-1,2,p,1);
    hist2(decError(ind,[1,2],p),linspace(-300,300,50),linspace(-400,400,50));
    spb(end+1) = subplot2(numel(phzBins)-1,2,p,2);
    hist2(decError(ind,[3,4],p),linspace(-1.5,1.5,50),linspace(-1.5,1.5,50));
end
af(@(a) caxis(a,[0,50]),spp);
af(@(a) caxis(a,[0,150]),spb);



figure,
ind = all(posteriorMaxTPD{j}>0.000001,2)      & all(unitInclusionTPD{t}>=4,2);
subplot(4,1,1);plot([xyz{t}(ind,5,1),sq(dfet(ind,1,:))]);    
subplot(4,1,2);plot([xyz{t}(ind,5,2),sq(dfet(ind,2,:))]);        
subplot(4,1,3);plot([fet{t}(ind,1),  sq(dfet(ind,3,:))]);
subplot(4,1,4);plot([fet{t}(ind,2),  sq(dfet(ind,4,:))]);
linkaxes(findobj(gcf(),'Type','Axes'),'x');



figure,
ind = posteriorMax{j}>0.0001;
subplot(5,1,1);plot([xyz(ind,5,1),sq(decEstCom{j}(ind,1))]);    
subplot(5,1,2);plot([xyz(ind,5,2),sq(decEstCom{j}(ind,2))]);        
subplot(5,1,3);plot([fet(ind,1),  sq(decEstCom{j}(ind,3))]);
subplot(5,1,4);plot([fet(ind,2),  sq(decEstCom{j}(ind,4))]);
subplot(5,1,5);plot([unitInclusion{j}(ind)]);
linkaxes(findobj(gcf(),'Type','Axes'),'x');
