
* Glossary
under the condition that : sub conditione, quod : SCQ -> given.
RF: reference frame. (head coordinates / room coordinates)
* Motivation
** Phenomenon
The spikes of a place cell contain information regarding the spatial position of the rat's head.
The network orchestrates sequences of place cells as oscilatory bursts in the theta frequency range (5-12Hz).
The temporal order of the place cells reflects a spatial representation that sweeps from behind to in front of the animal.

The spikes of the place cells within each sequence are ordered where early-late corresponds to behind-ahead. 
In a phenomenon referred to as phase precession, a sigle place cell's spikes will apear earlier in each 
sequence as the rat moves towards, through, and away from its place field center. 


Theta sequences
    Local sequences were observed during foraging and navigation ( Skaggs and McNaughton 1996 )

    Non-local sequences observed during immobility ( Lee and Wilson 2002) 
    
    Stationary sequences observed during inter-trial wheel runnig ( Pastalkova and Buzsaki 2008 )


Index Theory

What is the source of spatial information? ( Where )
    - MEC, medial entorhinal cortex ( grid cells, border cells ) 

What is the source of orienting information? ( Where -- anterior thalamic nucleus)
    - PS, postsubiculum ( head direction cells )

what is the sounce of contextual information? ( What )
    - LEC, lateral entorhinal cortex ( )
    What aspects of context are captured by the LEC?
        - CELLTYPE



The single-cell prospective-coding of allocentric spatial information can be examined by focal


F1 
F2 HBA 
F3 Loc Pause HBA HVF
F4 Decoded



** place cell
*** spikes 




A change in a rat's position in time and space is mediated through behavior.

A rat's behavior drives changes in its position and orientation over an epoch of time.


*** Place Fields
    Local Field Potential (LFP)



*** Phase Precession

Previously explained terms:
    Local Field Potential (LFP)
    Place Cell            (PC)
    Place Field           (PF)
    
    

Phase precession is the phenomenon where a neuron fires at progressively 
earlier phases of theta. The neuron's change in phase is correlated with 
the rat's progression through the neuron's place field.

It was first recognized in the firing patterns of place cells 
as rats ran through the cells' place-fields. 

A place cell firing toward the ascending theta phases is associated with 
an approach to a place field; the trough: the center; 
The place cell will fire on the descending phase before the departure from 
the place field. 


The initial discovery was demonstrated on a linear track which constrained 
the rat's movement to shuttling from end to end of a straight track. The 
linear track afforded several nadvantages over a two dimensional arean. First
However, in open
field arenas with unconstrained two dimensional movement place field have a
gaussian profile.

The entrance to the place field evokes spiking at the peak of theta. Spiking 
generally terminates at the exit from the place field at around 90 degrees.

** Research
*** Linear track (o'keefe probably)
The clearest circular-linear relationship is observed on a linear track, As the
rat shuttles between ends, encouraged by water rewards at the terminals, the 
running speed is uniform and the behavior regular. 

*** Open field (skaggs,huxter)
Phase precession is also observed in 2d environments, although to observe a 
circular linear relationship between space and spike theta phase a place field
centric transformation is performed to reduce the spatial dimension from 2 
dimensions to 1. Spike distance was mapped from the placefield edges onto a
domain between -1 and 1. The transform distance's sign was assigned based the
head movement direction relative to the place field center. Negative values 
represent the movements towards the place field center, and positive 
values represent the movements away from the place field center. 

*** Circular shuttle (zugaro)
Phase precession is observed on a circular track where 

*** Novelty and theta phase preference (O'keefe 2010)
Theta phase preference of place cell are shifted twoards the ascending phase of the in novel situations 

* STAR
** Story
*** The Hippocampus is Necessary for Episodic Memory

- hippocampus
- internal map
The hippocampus is a conserved structure of the mammalian brain,
theorized to provide a neural basis of a mammal's internal map
of its environment and to distinguish between epochs of similar
sensory experiences, based on their unique spatio-temporal
histories. 

In rats, its network of interneurons and pyramidal
cells change activity with behavioral state. Rhythmic patterns
of 5-12Hz known as theta activity are observed within the
hippocampus when a rat assumes a state of vigilance or
exploration.

*** Cognitive Map
Cognitive map theory is teleologically derived, where the union of cartographic function
with navigation through an environment, imagined or real, augments a subjects homeostatic 
maintenance, through the modification of behavioral output by an internal model of the environment,
generated by previous experiences, within which
*** Tolman maze
environmental polarization by the half circular configuration of test paths.

The examples cited demonstrate recollection, contemplation, and navigation

The trajectory of a point in the environment within the rat's frame of reference. 

*** Spatial Representation is Encoded by Place Cell Activity
Spatial represantation within the hippocampus is theorized to be
a two dimensional surface where the neurons encoding each
location is a unique subset of place cells. Under the simplest
condition, a single place cell has a single place field, and the
animal traverses straight through the place field center. The
firing rate, computed as the the number of observed action potentials per
second, increases, reaches a maximum, and descends during each
traversal of the local field. The tuning curve is the firing rate as a
function of position within an environtment and generally conforms to a
gaussian centered on the place field center. The resulting spatial code
includes both an neuron identity as well as its firing rate,
which is more accurate than place cell identity alone.

**** Simulation of decoding by spike set 
**** Simulation of decoding by spike set and rate

*** Place Cells Generate Spatial Information
Pyramidal cells are the primary output of the hippocampus.
During theta activity, pyramidal cells emit action potentials
(APs) at specific locations within the environment and are
therefor named Place Cells (PCs). Place cells have one or more
place fields, where their firing rate is related to the rat's
proximity to a place field center. They fire maximally at the
centers and quickly reduce to zero at all other locations.
Within and between place cells, the spatial distribution of
place fields is random. These properties allow a continuous
representation of the entire environment where every point
activates a unique sets of place cells.


An anditional, temporal code results from the hippocampal network
dynamics, where the spatial order of the active place cells,
with respect to each cell's local place field, are compressed
and ordered within each theta cylce along the current
orientation and trajectory of the rat.


When a rat enters or occupies a state of vigilance or exploration the hippocampal
network 





Action potential autocorrelations contain lobes at 120ms neuron action potentials and extracellular potentials 
between interneurons and pyramidal cells generate network 


The active set of place cells is directly related to the
location and orientation of the head.



Theta phase 
firing rate
distance to a point

*** Movement -> new neural assembly 
**** How is movement measured ? 
***** exteroception
****** under chin whiskers @ head is lowered
****** carpal whiskers     @ locomatoion w/ gait 
****** visual flow         @ movement of the head, rotation or translation
***** interoception
****** proprioception      @ muscle activation
****** motor efferent copy @ motor planning/execution
**** How is the body represented
****** muscle activation and proprioception
Only a limited number of ground body configurations are normally related to the current 
vestibular state.

*** Trajectories of movement 
**** planned movement vs experienced movement

*** Movement -> leads to new space
*** Immobility -> same space, but different focus???
*** Local Field Potential 
**** Oscillations 
***** Theta Power
***** Theta Phase 
***** Gamma Power
***** Gamma Phase


*** Memory
**** Stable versus Unstable Associations

** Symbol
** Slogan
** Surprise
*** CA1 Predictive Phase Code Lateralizes with Head-Body Angle within Head Coordinates
** Salient
*** We reformulate allo centric mapping
**** episodic memory is experienced
An episodic memory is a sequence of personally experienced events, from the
first-person perspective and formed from the evolving sensory impressions that are
driven by movements through space and/or time. The formation, consolidation, and
recollection of episodic memories is a system wide process involving most of the
brain, however, the hippocampal formation has been identified as an essential
structure to these mnemonic processes through case studies of patients with varring
degrees of bilateral damage to the hippocampal formation, as well as studies of
controlled hippocampal lesions in animal models.

The hippocampus is preserved among mammals with analogues found in other
vertebrates. The real-time activity of the hippocampus is investigated by recording
changes in electical potentials of single (spikes) or groups of neurons (LFP: Local
Field Potentials) with structured eletrodes, implanted 

As a neuron spans multiple layers where distinct patterns afferents 

QUOTE "enable compensation for sensory consequences of movement and preemptive updating of spatial representations."



INTERNAL MODEL STATES

The separation of similar sensory experiences is necessary for 
autobiographical distiction, and the generation of semantic models 
derived from environmental elements of similar category.
    Categorization process???


Incomming sensory information can be of varring complexity
    Transient behavior repetior (TBR) biases the acquisition space of sensory 
    information until novel complexity in normally unattended sensory modes 
    evoke an update in TBR.

        SCQ - contextual appedication may be desired if neutral in valance
              otherwise positive or negatvie valance lead to partially 
              orthogonallized contex and representation.

        SCQ - a change in senory information results in cortical repretation 
              mismatch.







Each trajectory through the sensory space
**** episodic memory requires a hippocampus

**** context is a model
amygdala -> context???
    Contextually dervied allocation of behavioral modes 
    and their transition probabilities.

within sequences of neural assymblies. 




Hippocampal place cells have place fields. The fields are randomly allocated 
and generally observed as 2D gaussian tunning curves. 
 
tuning curves,. As the rat traverses through a place field
the hippocampal network coordinates the place cells' firing in sequential bursts 
on a timescale of 80 to 120 milliseconds, known as theta sequences, 
trajectory.  


During exploration the hippocampus (contains, holds,) an internal representation of the
environment, establishing 


Sensorimotor information is projected onto preconfigured maps of the hippocampal CA3 
region.

The extension of of location relative to 

The hippocampal spatial representation is centered on the head, where the majority of a
rat's sensory organs are situated, and provides the means to bind sensory information to 
the specific locations, subserving the formation, retention, and recall of episodic 
memories.





The late phase of theta, where the entorhinal cortex (EC) is the dominant input to
the CA1, via the layer lacosum moleculare, contains prospective information regarding 
the current trajectory of the rat.


An egocentric query of the allocentric location of incoming sensory information.



CA3 -> CA3 => EC2 -> CA3 =>

CA3 - CA1 => EC3 -> CA1



Hippocampal place cell activity is organized by intra- and extra-hippocampal 
network dynamics. Place cells of a rat actively engaged with its environment,
are orchestrated in rhythmic bursts at the theta frequency (6-12Hz). A single
cycle contains a sequence (i.e. theta sequence) of place cells, whose temporal
order reflects the spatial order of the place field centers along the rat's
current trajectory. 

hippocampus <- input
               -> timing 
                  early: CA3->CA1 
                  late : EC3->CA1




Problems:
This analysis only considers single field. 
 - How does this representation help understand multi-field place cells?
    - Each cell would require an egocentric rate map for each field




We analyze the two dimensional phase precession in an egocentric frame of reference.
We examine the egocentric phase precession correlates of head-body orientation and movement.

*** Embodiment determines the locus of agency
An entity's embodiment directs its agency, in such that a configuration of an entity's sensory organs determines a
sensorial subspace within which attention may be directed, and thus constraining the geometry of the sensory view
in space around the agent, with which it associates the singularity, or "self", within its memories and 
current attention.

*** Sensory and Mnemonic priming 
Rememberance of an event may be limited by the current sensorimotor state, such that the current attetional
models restrict their responsiveness to any sensory memories and modes of sensation that said sensorimotor 
state is best tuned. 

*** Evolotionary Considerations
Sensorimotor states reflect a dynamic pattern of investigation that may be phasic or rhythmic but must be 
stereotypical within the entity's species (phylogenetic neighbourhood). While a specific behavior may be 
evoked, over the course of a unique event within an entity's lifetime, by a specific juxtaposition of 
external and internal configurations. The most basic of such emergent phenomena are reflexes 


* Methods
** Electrophisiolgy ( see Project BehaviorPlaceCode )
** Motion Capture   ( see Project BehaviorPlaceCode )

** Head Basis Vector 
The head basis vector represents the forward and horizontal directions relative to the head. The forward 
vector was computed as the unit vector originating at the center of the head to the front marker, and the 
horizontal vector was computed as the unit vector originating at the center of the head to the right marker.

** Head Body Angle (HBA)
The head body angle (HBA) was computed by calulating the angles of the head vector and the body vector
relative to the room and then taking their circular difference. 

** Head Forward Velocity (HVF)
The head forward velocity (HVF) was computed by smoothing the trajectory of the head with a low pass 
filter with a cut-off of 2.5 Hz and computing the head velocity with respect to the room. The velocity 
was then projected onto the head basis vector to obtain the foward and lateral speeds of the head relative
to the head.

** Unit Selection
Place cells were selected with the following criteria
 - it must express at least one place field in the arena
    - the place field must be at least 20cm from any other field in the case of a place cell with multiple fields.
    - the place field must have a maximum firing rate greater than 2 Hz.


** Allocentric rate maps ( see Project BehaviorPlaceCode )
** Egocentric rate maps
The egocentric rate maps were computed in the same manner as the allocentric rate maps, except for a change 
in reference. The head's position was substracted from the place field center at each timepoint and projected
onto head basis vector The trajectory of the place field center relative
to the head was then use to compute the occupancy within the head's frame of reference.
*** Rate map 
**** Center 
***** lateral ego-ratemap-center by phase
**** Size
**** Symmetry
**** Theta phase preference
**** Theta phase
**** Head body angle
**** Lateral head movement
**** Head angular velocity
*** The decoded egocentric position.
**** Theta phase
How does the egofield size change with theta phase?
**** Head body angle
Does the ascending phase egofield size correlate with lateralized phase precession?
**** Lateral head movement
Do the tranlsational kinematics of the head, i.e. the acceleration/jerk, motion correlate with 
greater lateralized phase precession?
**** Head angular velocityp
Do the angular kinematics of the head, i.e. the acceleration/jerk, motion correlate with greater 
lateralized phase precession?



req20191104.m 
req20191104_2d_TimeShift.m 
req20191104_ca3.m 


Compute place field size in theta partitioned ego-ratemaps tp-ego-ratemaps
Collect tp-ego-ratemaps' max rate.

The computation of a place field's ratemap is an incomplete representation of the firing characteristics.
The phase of theta at which a spike occurs is tightly coupled to the position and orientation of the subject.

In the head frame of reference the place field size is on average greater on the ascending than that of 
the descending and trough phases of theta.

The ascending phase is generally theorized to be coding the posible future locations of the rat.
If this is probabilistic in nature, what information (e.g. proprioceptive and vestibular) is driving upstream 
models of the rats trajectory is necessary? and how is this information integrated? Does it truely reflect
a probalistic model of the future trajectory?

IF not ...
    ... 


Would decoding from more narrow tuning curves, or those derived from theta-trough spikes beter
reflect the allo-centric tuning curve. 



Index Theory
Theta Sequences
Memory Consolidation
Latent States

The firing rate of a place cell given the location of o

multi place field distribution is a poisson process which maximizes the randomness of the sets of concomitant 
firing of cells and generates an orthogonal code for the update of sensory models by the simultaneous inundation 
of sensory inforamtion and an orthogonal place code in reciprocally connected cortical networks. (EC, PRC, ...)

A given set of neurons provide a representation 

What maximizes the orthogonality of assembly compososition in 2D latent space.


**** allo to ego
***** PlaceField-Allo
allocentric ratemap: spikes per second given 2D position of the rat's head relative to the environment
****** Field 
******* Size 
Size determination types 2hz threshold on ratemap
******* Rate
******** Mean
******** Max
***** PlaceField-Ego
egocentric ratemap: spikes per second given 2D position of the place field center relative to the head of the rat. 
****** Field 
******* Size
******* Rate
******** Mean
******** Max
APF-fieldSize VS EPF-fieldSize

for each moment:
    A set of EPFs are coactive representing their place preferrence. 
    





****** How does one define the spatial location of attractor basins that is separate from the allocentric representation?


**** PlaceField-Allo split by head-body-angle
Hysteresis of place fi

***** PlaceField-Allo | head-body-angle
allocentric ratemap: spikes per second given 2D position of the place field center relative to the head of the rat. 
****** Field 
******* Size
******* Rate
******** Mean
******** Max
**** PlaceField-Ego split by head-body-angle
***** PlaceField-Ego | head-body-angle
egocentric ratemap: spikes per second given 2D position of the place field center relative to the head of the rat. 
****** Field 
******* Size
******* Rate
******** Mean
******** Max



**** PlaceField-Allo | theta phase
***** field size
***** max rate

**** PlaceField-Ego | theta phase
***** field size
***** max rate


**** PlaceField-Ego | head-body-angle
***** field size
***** max rate

**** PlaceField-Ego | theta phase AND head-body-angle
***** 
**** Decoding
**** Lateral AND theta-phase | head-body-angle AND head-lateral-speed
***** Permuted head-body-angle paritions
***** Permuted head-lateral-speed partitions





**** sampling issues
The sampling in the outer perimeter is restricts the decoding to
the left or right with respect to counterclockwise and clockwise
trajectories 






* Entity ------------------------------------------------------------------------
** Class
** Variables
*** cardinality
*** domain
*** distribution (within temporal domain)
**** Empirical 
***** Parameters
******* Mean
******* Median
******* Standard Deviation
**** Modeled
***** Parameters
****** Mean
****** Standard Deviation

* Rat ---------------------------------------------------------------------------
** neuron
*** spike times
**** epoch & spike times -> average firing rate
* Anaysis -----------------------------------------------------------------------
** Single Entity
** Group of Entities
** restriction of subset ranges
*** { name: 'hba', Domains: [x, y; w, z]}
** What drives a change in the hippocampal network?
Internal dynamics 
    input   -> internal dynamics
    network -> internal dynamics
Modification
Pattern completion
Given a previously leared input patten
A previously learned input patten may be retrieved by a similar or partial
pattern.
continuous attractor network (CAN) 




*** what constitutes a change in the hippocampal network?
*** what comprises the hippocampl network?
**** Pyramidal neurons 
Excitatory neurons by and through which the integration/transormation of
information occurs.
 - Excitatory 
 - integration of information
   - oeu
**** Interneurons
 - Inhibitory: reduces the membrane potential of target neurons
 - Generation of a dynamic network state 
 - 



* Figures ----------------------------------------------------------------------
** FIG1 - Allocentric to Egocentric
*** Schematic of allo to egocentric frame of reference for an individual place cell.
**** Left, Example of an allocentric spatial rate map. Center-left, close-up of place field with example trajectory colored by the head direction. Center-right, close-up of egocentric spatial rate map, with example trajectory colored by the head direction. Right, Example of an egocentric spatial rate map.
**** Top, allocentric spatial rate maps: 
***** Top-left, Descending theta phase; 
***** Top-center, trough theta phase; 
***** Top-right, ascending theta phase. 
**** Bottom, egocentric spatial rate maps w.r.t. place field center: 
***** Bottom-left, descending theta phase; 
***** Bottom-center, trough theta phase; 
***** Bottom-right, ascending theta phase.
**** Field Position Distributions by forward and lateral displacement from the center of the head w.r.t. the direction of the head
***** Top-left, the distribution the mean field position along the anteroposterior axis of the egocentric spatial rate map for each theta phase partition. 
***** Top-right, above diagonal: differences between distribution means of anteroposterior mean field position, pairwise comparison between phase partitions and hippocampal region; 
***** below diagonal: p-values (t-test) of significantly different anteroposterior mean field position distributions between phase partitions and hippocampal regions. Bottom-left, the distribution the mean field position along the lateral axis of the egocentric spatial rate map for each theta phase partition. Bottom-right, above diagonal: differences between distribution means of lateral mean field positions, pairwise comparison between phase partitions and hippocampal region; below diagonal: p-values (t-test) of significantly different anteroposterior mean field position distributions between phase partitions and hippocampal regions.
***** Top-left, log10 peak firing rate for each theta phase partition from the egocentric rate maps for all CA1 place cells, and sorted by theta phase preference. Top-right, same as top-left for CA3 place cells. Bottom-left, log10 egocentric field size (m^2), for each theta phase partition for all CA1 place cells, and sorted by max field size by theta phase. Bottom-right, same as bottom-left for CA3 place cells.

** FIG2 - Egocentric Given Head-Body Angle
*** Titles
**** Anisotropic field structure within the head-body-angle space.
*** Ego HBA
**** Example - jg05-20120324 - unit 29
***** theta-msr place field
***** theta-msr ego field partitioned { left, center, right }
***** theta-msr ego field partitioned { L, C, R }HBA X { Asc, trough, dsc}Phase
*****
**** Lateral decoding statistics resolved by hba
**** Angle of decoding resolved by hba
***** TODO REPLOT subject means as dots along the circumference
     SCHEDULED: <2023-12-15 Fri>
**** Decoded Angle regressed by hba
** FIG3 - EgoPhzHba - Locomotion vs Pause
*** Titles
**** Egocentric Preditive Ideothetic Coding (EPI-coding / EPIC) persists between behavioral states.

*** Layout
**** Box 1 Ego-field partitioned by the theta phase and hba
****
*** todo list
**** TODO Replot figure 3
*** Ego Loc vs Pause

** FIG4 - EgoPhzHvf - Speed vs Anterioposterior pos

* scratch * --------------------------------------------------------------------
Memories contain the sequences of events. Each of which impresses various 

interaction between environment and sensory organs evokes senory information

** sesnory acquisition loops 
efficient sensory sampling involves - acquisition, expectation, comparison, and
reorganization of the sensory organs.
Reorganization may include modulation of membrane sensitivity through 

chemoreceptors - contextualization
mechanoreceptors - physical values


context <-> internal model state (body and environmental model)
luminance - dawn, day, dusk, night.


Moving sensory organs through space is useful for information gathering.

** Teleology
survey of local 
 - environment
   - topology
 - resources
 - agents 
   - conspecifics
     - competitors 
     - collaborators 
   - predators



A continueous integration of information over


The place to be and the action to take
the body is the space which divides context.
The actions are linked as a web where some loops are acyclical.
motion dictates possible motion, non-conformance is only externally enforcible.
Time and history changes transition probabilities
Information is different for the times where information is cosidered
the matching occurs in the cortex. 
The cholinergic system always waiting for change
the head leads the body 
the muscle groups work together and have many sequential/rhythmic patterns
the time is non-linear in cases of contemplation and action. 
Observation must be represented by activity
The spaces are the actions 
ordered sets when aligned  information 
temporally shifted correlation




Previous Theories
ascending theta predicts trajectory

** Random
Oh god, what am I doing with this moment in life? Am I wasting or waiting for
the right time? For what were those years? Do I just give up, move on, and
forget? Have I forgotten the good for the bad? 
