

* Motivation
** Phenomenon
*** Place Fields

*** Phase Precession
Hippocampal place cell phase precession is the phenomenon where a neuron 
fires progressively earlier phases of theta. 

Phase precession was first found in rats running through their place-cell's 
place-field. A place cell firing toward the ascending theta phases is 
associated with an approach to a place field; the trough: the center; and 
the descending phase: the exit of a place field. Most pyramidal cells of the 
hippocampus demonstrate phase precession. 

The initial discovery was made on a linear track which constrained the rat's 
movement to shuttling from end to end via a straight line. The linear track
afforded several advantages over the two dimensional areans, in which the 
primary observations of place-fields were made. First
However, in open
field arenas with unconstrained two dimensional movement place field have a
gaussian profile.

The entrance to the place field evokes spiking at the peak of theta. Spiking 
generally terminates at the exit from the place field at around 90 degrees.
** Research
*** Linear track (o'keefe probably)
The clearest circular-linear relationship is observed on a linear track, As the
rat shuttles between ends, encouraged by water rewards at the terminals, the 
running speed is uniform and the behavior regular. 
*** Open field (skaggs,huxter)
Phase precession is also observed in 2d environments, although to observe a 
circular linear relationship between space and spike theta phase a place field
centric transformation is performed to reduce the spatial dimension from 2 
dimensions to 1. Spike distance was mapped from the placefield edges onto a
domain between -1 and 1. The transform distance's sign was assigned based the
head movement direction relative to the place field center. Negative values 
represent the movements towards the place field center, and positive 
values represent the movements away from the place field center. 
*** Circular shuttle (zugaro)
Phase precession is observed on a circular track where 

* The fence which separates previous my work from previous efforts
We analyze the two dimensional phase precession in an egocentric frame of reference.
We examine the egocentric phase precession correlates of head-body orientation and movement.

An entity's embodiment directs its agency, in such that a configuration of an entity's sensory organs determines a
sensorial subspace within which attention may be directed, and thus constraining the geometry around the singular
agent, with which it associates the singularity, or "self", within its memories and current attention.

Rememberance of an event may be limited by the current sensorimotor state, such that the current attetional
models restrict their responsiveness to any sensory memories and modes of sensation that said 
sensorimotor state is best tuned. 

Modes of sensation reflect a dynamic pattern of investigation that may be phasic or rhythmic but must be 
stereotypical within the entity's species (phylogenetic neighbourhood). While a specific behavior may be 
evoked, over the course of a unique event within an entity's lifetime, by a specific juxtaposition of 
external and internal configurations. The most basic of such emergent phenomena are reflexes 


Place cells, ontologically derived from observations of high firing rates 





* Analisys
** The egocentric rate map 
*** Center
*** Size
*** Symmetry
*** Theta phase preference
*** Theta phase
*** Head body angle
*** Lateral head movement
*** Head angular velocity
** The decoded egocentric position.
*** Theta phase
How does the egofield size change with theta phase?
*** Head body angle
Does the ascending phase egofield size correlate with lateralized phase precession?
*** Lateral head movement
Do the tranlsational kinematics of the head, i.e. the acceleration/jerk, motion correlate with 
greater lateralized phase precession?
*** Head angular velocityp
Do the angular kinematics of the head, i.e. the acceleration/jerk, motion correlate with greater 
lateralized phase precession?



req20191104.m 
req20191104_2d_TimeShift.m 
req20191104_ca3.m 
