function generate_enf(path,varargin)
if isemtpy(varargin)
    pattern = 'Trial.*\.Trial\d{1,5}\.enf';
else
    pattern = varargin{1}    
end
path = 

files = dir(path)
flist = {files(~cellfun(@isempty,regexp({files.name},pattern))).name};



enf_content = [...
'[Node Information]\n'...
'TYPE=TRIAL\n'...
'Reference=\n'...
'PARENT=Session 1\n'...
'NAME=Trial001_1\n'...
'HASCHILD=FALSE\n'...
'SORTBY=1\n'...
'[TRIAL_INFO]\n'...
'CAMERACALIBRATION=\n'...
'MASK=\n'...
'[LOCK_INFO]\n'...
'CURR_USER=\n'...
];