function [data,sampleRate,label,key] = MTAHvel(Trial,varargin)

    [threshold,label,key] = DefaultArgs(varargin,{2,'vel','v'});
    
    xyz = Trial.load('xyz');
    
    xyz.filter(gtwin(.25,xyz.sampleRate));

    data = ThreshCross(xyz.vel(Trial.trackingMarker,[1,2]),threshold,round(.5*xyz.sampleRate));
    
    data = MTADepoch(Trial.spath,...
                     Trial.filebase,...
                     data,...
                     xyz.sampleRate,...
                     Trial.sync.copy,...
                     Trial.sync.data(1),...
                     label,key);
end
