function fet = fet_lgr(Trial,varargin)
%function fet = fet_lgr(Trial,sampleRate)
%


if ~isempty(varargin)
sampleRate = varargin{1};
else 
    sampleRate = Trial.xyz.sampleRate;
end

dsx = resample(Trial.load('xyz').filter(gtwin(.25,Trial.xyz.sampleRate)),sampleRate);;
dsa = create(Trial.ang.copy,Trial,dsx);
vel = dsx.vel([],[1,2]);
vel.data(vel.data<0.0001) = 0.0001;
vel.data = log10(vel.data);

w = 90;
lw = 70;
h = round(w/2);
lh = round(lw/2);
d = circshift(circ_dist(circshift(dsa(:,2,4,1),-w),dsa(:,2,4,1)),h);
d = circshift(nanmean(GetSegs(d,1:size(d,1),lw,nan))',lh);
ds = circshift(circ_dist(circshift(dsa(:,2,8,1),-w),dsa(:,2,8,1)),h);
ds = circshift(nanmean(GetSegs(ds,1:size(ds,1),lw,nan))',lh);
da = circshift(circ_dist(circshift(dsa(:,2,6,1),-w),dsa(:,2,6,1)),h);
da = circshift(nanmean(GetSegs(da,1:size(da,1),lw,nan))',lh);
dsv = max([abs(d),abs(ds),abs(da)],[],2);
bs = bhv_shake(Trial,'raw');
bs = bs(1:end-1);

fet = MTADxyz('data',[vel(:,'spine_lower')  ,...
                      vel(:,'spine_middle') ,...                    
                      vel(:,'head_front')   ,...
                      dsx(:,'spine_lower',3),...
                      dsx(:,'head_front',3)-dsx(:,'spine_lower',3),...
                      dsa(:,'spine_lower','pelvis_root',2) ,...
                      dsa(:,'spine_middle','spine_upper',2),...
                      dsa(:,'spine_lower','pelvis_root',3) ,...
                      dsa(:,'pelvis_root','spine_middle',3),...
                      dsa(:,'spine_upper','head_back',3)   ,...
                      dsa(:,'spine_lower','head_front',3)  ,...
                      dsv,...
                      bs],...
              'sampleRate', dsx.sampleRate,...
              'syncPeriods',Trial.sync.copy,...
              'syncOrigin', Trial.sync.data(1));

