function [fet,featureTitles,featureDesc] = fet_epf(Trial,varargin)

[newSampleRate,RefTrial,procOpts] = DefaultArgs(varargin,{20,[],'spline_spine'},1);

fet = MTADfet(Trial.spath,...
              [],...
              [],...
              newSampleRate,...
              Trial.sync.copy,...
              Trial.sync.data(1),...
              [],'TimeSeries',[],'all_Features','fet_all','a');                  
