function [fet,featureTitles,featureDesc,Nmean,Nstd] = fet_rear_desc(Trial,varargin)
% $$$ function [fet,featureTitles,featureDesc,Nmean,Nstd] = fet_rear_desc(Trial,varargin)
% $$$ defargs = struct('newSampleRate', [],                       ...
% $$$                  'normalize'    , false,                    ...
% $$$                  'procOpts'     , {'SPLINE_SPINE_HEAD_EQD'});



% DEFARGS ------------------------------------------------------------------------------------------
defargs = struct('newSampleRate', [],                       ...
                 'normalize'    , false,                    ...
                 'procOpts'     , {'SPLINE_SPINE_HEAD_EQD'});

[newSampleRate,normalize,procOpts] = DefaultArgs(varargin,defargs,'--struct');
%---------------------------------------------------------------------------------------------------


% MAIN ---------------------------------------------------------------------------------------------

% INIT Feature
fet = MTADfet(Trial.spath,...
              [],...
              [],...
              newSampleRate,...
              Trial.sync.copy,...
              Trial.sync.data(1),...
              [],'TimeSeries',[],'Rearing SVD Decompotion','fet_rear_desc','r');

% XYZ preprocessed 
xyz = preproc_xyz(Trial,procOpts);
%xyz.resample(newSampleRate);

ang = create(MTADang,Trial,xyz);

fet.data = [];
fet.data = [fet.data,                                            ...
            ang(:,{'spine_lower'},{'pelvis_root'},2),            ...
            ang(:,{'spine_lower'},{'spine_middle'},2),           ...
            ang(:,{'spine_lower'},{'hcom'},2),                   ...
            ang(:,{'pelvis_root'},{'spine_middle'},2),           ...
            ang(:,{'pelvis_root'},{'spine_upper'},2),            ...
            ang(:,{'spine_middle'},{'spine_upper'},2),           ...
            ang(:,{'spine_middle'},{'hcom'},2),                  ...
            ang(:,{'spine_upper'},{'hcom'},2),                   ...
            xyz(:,{'spine_lower','pelvis_root','spine_middle',   ...
                   'spine_upper','bcom','acom','hcom'},3)        ...
];
fet.data(~nniz(xyz),:) = 0;

featureTitles = cell([1,size(fet,2)]);
featureDesc   = cell([1,size(fet,2)]);

% END MAIN -----------------------------------------------------------------------------------------