function ego = fet_ego(Trial,varargin)
% function ego = fet_ego(Trial,varargin)
% 
% varargin:
%     xyz:           MTADxyz,  
%     markers:       CellARY,  ({'head_back', 'head_front'})
%     center:        NumARY,  ([0,0]) allocentric point of reference
%     theta:         double,  (0) rotation of the head vector in radians

% DEFARGS ---------------------------------------------------------------------
defargs = struct('xyz'            , [],                                     ...
                 'markers'        , {{'hcom', 'nose'}},                     ...
                 'center'         , [0,0],                                  ...
                 'theta'          , []                                      ...
);
[xyz, markers, center, theta] = DefaultArgs(varargin,defargs,'--struct');
%------------------------------------------------------------------------------

% MAIN ------------------------------------------------------------------------

if isempty(theta) && isprop(Trial,'meta')
    if isfield(Trial.meta,'correction');
        theta = Trial.meta.correction.headYaw;
    end
end


if any(contains(xyz.model.ml,'hcom'))
    hcom = sq(xyz(:,'hcom',[1,2]));
else    
    hcom = sq( mean( xyz(:,markers,[1,2]), 2));
end
hvec = transform_vector_to_rotation_matrix( xyz, markers, theta);

ego = MTADfet.encapsulate(                                                  ...
    Trial,                                                                  ...
    bsxfun(                                                                 ...
        @plus,                                                              ...
        multiprod(                                                          ...
            bsxfun(                                                         ...
                @minus,                                                     ...
                center,                                                     ...
                hcom                                                        ...
            ),                                                              ...
            hvec,2,[2,3]),                                                  ...
        0),                                                                 ...
    xyz.sampleRate,                                                         ...
    'egocentric_placefield',                                                ...
    'egopfs',                                                               ...
    'p'                                                                     ...
);

%------------------------------------------------------------------------------





