function fet = fet_lgr(Trial)

dsx = Trial.load('xyz').filter(gtwin(.5,Trial.xyz.sampleRate));
dsx.resample(30);

dsa = Trial.ang.copy;
dsa.create(Trial,dsx);

vel = dsx.vel([],[1,2]);
vel.data(vel.data<0.0001) = 0.0001;
vel.data = log10(vel.data);

dsv = [0;Filter0(ones(1,7)./7,abs(diff(circ_dist(dsa(:,'spine_lower','spine_middle',1),dsa(:,'spine_middle','head_front',1)))))];

fet = MTADxyz('data',[vel(:,'spine_lower'),...
                      vel(:,'head_front'),...
                      dsx(:,'spine_lower',3),...
                      dsa(:,'spine_lower','pelvis_root',3),...
                      dsa(:,'spine_middle','spine_upper',2),...
                      dsa(:,'pelvis_root','spine_middle',3),...
                      dsa(:,'spine_lower','pelvis_root',2),...
                      dsa(:,'spine_upper','head_back',3),...
                      dsv,...
                      dsa(:,'spine_lower','head_front',3)],...
              'sampleRate',dsx.sampleRate);
