function rotm = quat2rotm(quat)
% quat: nx4 -> rotm: nx3x3

% $$$ rotm = cat(3,...
% $$$            [1-2.*(quat(:,3).^2+quat(:,4).^2),  ...
% $$$             2.*(quat(:,2).*quat(:,3)+quat(:,4).*quat(:,1)),...
% $$$             2.*(quat(:,2).*quat(:,4)-quat(:,3).*quat(:,1))],...
% $$$            [2.*(quat(:,2).*quat(:,3)-quat(:,4).*quat(:,1)), ...
% $$$             1-2.*(quat(:,2).^2+quat(:,4).^2),...
% $$$             2.*(quat(:,3).*quat(:,4)+quat(:,2).*quat(:,1))],...
% $$$            [2.*(quat(:,2).*quat(:,4)+quat(:,3).*quat(:,1)),...
% $$$             2.*(quat(:,3).*quat(:,4)-quat(:,2).*quat(:,1)),...
% $$$             1-2.*(quat(:,2).^2+quat(:,3).^2)]);

rotm = cat(3,...
           [1-2.*(quat(:,3).^2+quat(:,4).^2),  ...
            2.*(quat(:,2).*quat(:,3)-quat(:,4).*quat(:,1)), ...
            2.*(quat(:,2).*quat(:,4)+quat(:,3).*quat(:,1))],...
           [2.*(quat(:,2).*quat(:,3)+quat(:,4).*quat(:,1)),...
            1-2.*(quat(:,2).^2+quat(:,4).^2),...
            2.*(quat(:,3).*quat(:,4)-quat(:,2).*quat(:,1))],...
           [2.*(quat(:,2).*quat(:,4)-quat(:,3).*quat(:,1)),...
            2.*(quat(:,3).*quat(:,4)+quat(:,2).*quat(:,1)),...
            1-2.*(quat(:,2).^2+quat(:,3).^2)]);


