#! /bin/bash
# tart - tar file transfer over ssh
# advantage over scp: copies relative links rather
# than following to hard copy
cwd=$(pwd)

if [ "$HOSTNAME" == "theta" -o "$HOSTNAME" == "gamma"* ]
then
    hostname=$HOST_LRZ
    user=$USERNAME_LRZ
    onClu=0
else
    hostname=$HOST_THETA
    user=$USERNAME_THETA
    onClu=1
fi

file_list="./"

while [[ $# > 0 ]]
do
    key="$1"

    case $key in
        -h|--help)     
	    echo "tart [-l login_name] [-T filelist] [-o remote_output_dir]"
	    echo "     [-p port] [-u user] [[user@]hostname]"
	    exit 1
            ;;
        -i|--remote-input-dir)
            remote_input_dir=$2
            shift
            ;;
	-l|--login-name)
	    login_name="-l $2"
	    shift
	    ;;
        -o|--remote-output-dir)
            remote_output_dir=$2
            shift
            ;;
        -p|--port)
            port="-p $2"
            shift
	    ;;
	-T|--files-from)   
            file_list="-T $2"
            shift
	    ;;
	-t|--file)   
            file_list=$2
            shift
	    ;;
	-u|--user)
	    user=$2
            shift	    
	    ;;
	-v|--verbose)  
	    v="v"
            ;;
	*)    
	    hostname=$1        
            ;;
    esac
    shift 
done


if [[ $onClu -eq 0 ]]
then
    tar c${v}fz - $file_list | ssh $port $user@$hostname $login_name  "cd $PROJECT_LRZ/$remote_output_dir;  tar x${v}fz - "
else
    echo "ssh $port $user@$hostname $login_name  \"cd $PROJECT_THETA/$remote_input_dir;  tar c${v}fz - $file_list \" | tar x${v}fz -"
    ssh $port $user@$hostname $login_name  "cd $PROJECT_THETA/$remote_input_dir;  tar c${v}fz - $file_list " | tar x${v}fz -
fi


cd $cwd
