#! /bin/bash

# tart - tar file transfer over ssh
# advantage over scp: copies relative links rather
# than following to hard copy
cwd=$(pwd)


hostname=$HOST_LRZ
file_list="./"
user=$USERNAME_LRZ


if [[ $# -eq 0 ]]
then
echo "tart [-h help] [-l login_name] [-T filelist] "
echo "     [-o remote_output_dir] [-p port] [[user@]hostname]"
fi

while [[ $# > 0 ]]
do
    key="$1"
    case $key in
        -h|--help)
	    echo "tart [-l login_name] [-T filelist] [-o remote_output_dir]"
	    echo "     [-p port] [-u user] [[user@]hostname]"
	    exit 1
            ;;
	-l|--login-name)
	    login_name="-l $2"
	    shift
	    ;;
        -o|--remote-output-dir)
            remote_output_dir=$2
            shift
            ;;
        -p|--port)
            port="-p $2"
            shift
	    ;;
	-T|--files-from)
	    if [ -d $2 ]
	    then		
		file_list="$2"
	    else
		file_list="-T $2"
	    fi
            shift
	    ;;
	-u|--user)
	    user=$2
            shift	    
	    ;;
	-v|--verbose)  
	    v="v"
            ;;
	*)
	    hostname=$1
            ;;
    esac
    shift 
done

tar c${v}fz - $file_list |  \
echo "ssh $port $user@$hostname $login_name \"cd ~/$remote_output_dir;  tar x${v}fz - \""
ssh $port $user@$hostname -l $login_name  "cd ~/$remote_output_dir;  tar x${v}fz - "

cd $cwd
