function spk = load_spk(Spk, cluster_group)
% function Spk = load_spk(Spk, cluster_group)


Par = Spk.parent.par;

EXT = 'spk';

maxChanCount = max(cellfun(@numel,Par.ElecGp));
maxSampleCount = max([Par.SpkGrps(:).nSamples]);

filepath = fullfile(Spk.parent.spath,...
                    [Spk.parent.name,'.',EXT,'.',num2str(cluster_group)]);

% >>> LOAD spike waveform file >>> -------------------------------------------
spk = bload(                                                               ...
    filepath,                                                              ...
    [numel(Par.SpkGrps(cluster_group).Channels), inf],                     ...
    0,                                                                     ...
    'short=>single'                                                        ...
);
% <<< LOAD spike waveform file <<< -------------------------------------------

% >>> RESHAPE spike waveform to (res, channel, sample) >>> --------------------
nSpikes = size(spk, 2)/Par.SpkGrps(cluster_group).nSamples;
spk = reshape(                                                              ...
    spk,                                                                    ...
    [                                                                       ...
        numel(Par.SpkGrps(cluster_group).Channels),                         ...
        Par.SpkGrps(cluster_group).nSamples,                                ...
        nSpikes]                                                            ...
);
spk = permute(spk, [3,1,2]);
% <<< RESHAPE spike waveform to (res, channel, sample) <<< --------------------

% >>> PAD Spike Waveform >>> --------------------------------------------------
if size(spk,2) ~= maxChanCount
    % >>> PAD Spike Waveform Channels >>> -------------------------------------
    spk = cat( 2,                                                           ...
                spk,                                                        ...
                zeros(                                                      ...
                    [                                                       ...
                        size(spk,1),                                        ...
                        maxChanCount-size(spk,2),                           ...
                        size(spk,3)                                         ...
                    ]                                                       ...
                )                                                           ...
            );
    % <<< PAD Spike Waveform Channels <<< -------------------------------------
end
if size(spk,3) ~= maxSampleCount
    % >>> PAD Spike Waveform Samples >>> --------------------------------------
    spk = cat( 3,                                                           ...
                spk,                                                        ...
                zeros(                                                      ...
                    [                                                       ...
                        size(spk,1),                                        ...
                        maxChanCount,                                       ...
                        maxSampleCount-size(spk,3)                          ...
                    ]                                                       ...
                )                                                           ...
            );
    % <<< PAD Spike Waveform Samples <<< --------------------------------------
end
% <<< PAD Spike Waveform <<< --------------------------------------------------


