function load_ndm_swf(Spk, cluster_group, max_channels, max_samples)
% function Spk = load_spk(Spk, cluster_group,  max_channels, max_samples)

Par = Spk.parent.par;

NDM_FILE_EXT = 'spk';
NDM_SWF_DTYPE = num2str(Par.nBits, 'int%i');

number_of_samples = Par.SpkGrps(cluster_group).nSamples;
number_of_channels = numel(Par.SpkGrps(cluster_group).Channels);
number_of_swf = numel(Spk.locs);

SWF_OFFSET = number_of_samples * number_of_channels;
BLOCK_SIZE = SWF_OFFSET;


% >>> SETUP memory map for spike file >>> -------------------------------------
filepath = fullfile(Spk.parent.spath,                                       ...
                    [Spk.parent.name,                                       ...
                     '.',NDM_FILE_EXT,'.',                                  ...
                     num2str(cluster_group)]);

MM = memmapfile(filepath);
MM.Format = NDM_SWF_DTYPE;
MM.Writable = false;
% <<< SETUP memory map for spike file <<< -------------------------------------

% >>> GENERATE index from cluster file location >>> ---------------------------
idx = reshape(                                                              ...
    bsxfun(@plus, (Spk.locs-1) * BLOCK_SIZE, [1:(BLOCK_SIZE)]) ,            ...
    [],                                                                     ...
    1);
% <<< GENERATE index from cluster file location <<< ---------------------------

% >>> LOAD and RESHAPE spike waveform to (res, channel, sample) >>> -----------
swf = reshape(                                                              ...
    MM.Data(idx),                                                           ...
    [                                                                       ...
      number_of_swf,                                                        ...      
      number_of_channels,                                                   ...
      number_of_samples                                                     ...
    ]                                                                       ...
);
% <<< LOAD and RESHAPE spike waveform to (res, channel, sample) <<< -----------

% >>> PAD Spike Waveform >>> --------------------------------------------------
if size(swf,2) ~= max_channels
    % >>> PAD Spike Waveform Channels >>> -------------------------------------
    swf = cat( 2,                                                           ...
                swf,                                                        ...
                zeros(                                                      ...
                    [                                                       ...
                        size(swf,1),                                        ...
                        max_channels - size(swf,2),                         ...
                        size(swf,3)                                         ...
                    ]                                                       ...
                )                                                           ...
            );
    % <<< PAD Spike Waveform Channels <<< -------------------------------------
end
if size(swf,3) ~= max_samples
    % >>> PAD Spike Waveform Samples >>> --------------------------------------
    swf = cat( 3,                                                           ...
                swf,                                                        ...
                zeros(                                                      ...
                    [                                                       ...
                        size(swf,1),                                        ...
                        max_channels,                                       ...
                        max_samples - size(swf,3)                           ...
                    ]                                                       ...
                )                                                           ...
            );
    % <<< PAD Spike Waveform Samples <<< --------------------------------------
end
% <<< PAD Spike Waveform <<< --------------------------------------------------

Spk.spk = cat(1, Spk.spk, double(swf));
