function A20160628(Trial,varargin)


defargs = struct('fetSet',   'fet_mis',...
                 'mode',     'display',...
                 'tag_preprocessing',      '+seh+',...
                 'tag_postprocessing',      '',...
                 'rlist',    'training_hand_labeled',...
                 'slist',   {{'hand_labeled_jg';'hand_labeled_Ed'}},...
                 'sampleRate', 12,...
                 'nNeurons',   100,...
                 'nIter',      100,...
                 'states',   {{'walk','rear','turn','pause','groom','sit'}},...
                 'rndMethod', 'WSBNT',...
                 'norm',      true,...
                 'mref',      true...
);


[fetSet, mode, tag_preprocessing, tag_postprocessing,rlist, slist, sampleRate,...
 nNeurons, nIter, states, rndMethod, norm, mref] = DefaultArgs(varargin,defargs,'--struct');



Trial = MTATrial.validate(Trial);

