% configure_default_args
clearvars('-GLOBAL','AP');
global AP;
global DELETE_CURRENT_AXES;

DELETE_CURRENT_AXES = true;

% >>> GENERAL >>> -------------------------------------------------------------
sessionListName = 'MjgER2016';
activeState     = 'theta-groom-sit';
AP.fet_HB_pitchB.referenceTrial = 'Ed05-20140529.ont.all';
% <<< GENERAL <<< -------------------------------------------------------------

% >>> compute_patch_ratemaps >>> ----------------------------------------------
AP.compute_bhv_ratemaps =                                                   ...
    struct('get_featureSet',  @fet_HB_pitchB,                               ...
           'sampleRate',      16,                                           ...
           'pfsArgs',         struct('states',           activeState,       ...
                                     'binDims',          [0.1,0.1],         ...
                                     'SmoothingWeights', [1.8,1.8],         ...
                                     'numIter',          1,                 ...
                                     'boundaryLimits',   [-2,0.8;-0.8,2],   ...
                                     'halfsample',       false),            ...
           'threshRate',     0.8,                                           ...
           'threshDist',     250                                            ...
);
% <<< compute_patch_ratemaps <<< ----------------------------------------------

% >>> compute_bhv_ratemaps >>> ------------------------------------------------
AP.compute_bhv_ratemaps =                                                   ...
    struct('get_featureSet',  @fet_HB_pitchB,                               ...
           'sampleRate',      16,                                           ...
           'pfsArgs',         struct('states',           activeState,       ...
                                     'binDims',          [0.1,0.1],         ...
                                     'SmoothingWeights', [1.8,1.8],         ...
                                     'numIter',          1,                 ...
                                     'boundaryLimits',   [-2,0.8;-0.8,2],   ...
                                     'halfsample',       false),            ...
           'threshRate',      0.8,                                          ...
           'threshDist',      250                                           ...
           );
% <<< compute_bhv_ratemaps <<< ------------------------------------------------

% >>> compute_bhv_ratemaps_shuffled >>> ---------------------------------------
AP.compute_bhv_ratemaps_shuffled =                                          ...
    struct('get_featureSet',  @fet_HB_pitchB,                               ...
           'sampleRate',      16,                                           ...
           'pfsArgs',         struct('states',           activeState,       ...
                                     'binDims',          [0.1,0.1],         ...
                                     'SmoothingWeights', [1.8,1.8],         ...
                                     'numIter',          1002,              ...
                                     'posShuffle',       true,              ...
                                     'boundaryLimits',   [-2,0.8;-0.8,2],   ...
                                     'halfsample',       false),            ...
           'threshRate',      0.8,                                          ...
           'threshDist',      250                                           ...
           );
% <<< compute_bhv_ratemaps_shuffled <<< ---------------------------------------

% >>> compute_ratemaps >>> ----------------------------------------------------
AP.compute_ratemaps =                                                       ...
    struct('get_featureSet', @fet_xy,                                       ...
           'sampleRate',     16,                                            ...
           'pfsArgs',        struct('states',           activeState,        ...
                                    'binDims',          [50,50],            ...
                                    'SmoothingWeights', [2.4,2.4],          ...
                                    'numIter',          1,                  ...
                                    'boundaryLimits',   [-500,500;-500,500],...
                                    'halfsample',       false)              ...
);
% <<< compute_ratemaps <<< ----------------------------------------------------

% >>> compute_bhv_ratemap_erpPCA >>> ------------------------------------------
AP.compute_bhv_ratemaps_erpPCA =                                            ...
    struct('numComp',                   5,                                  ...
           'range',                     [250,600]                           ...
           );
% <<< compute_bhv_ratemap_erpPCA <<< ------------------------------------------

% >>> compute_bhv_ratemap_nnmf >>> --------------------------------------------
AP.compute_bhv_ratemaps_nnmf =                                              ...
    struct('numComp',                   5,                                  ...
           'range',                     [250,600]                           ...
           );
% <<< compute_bhv_ratemap_nnmf <<< --------------------------------------------

% >>> compute_xyhb_ratemaps >>> -----------------------------------------------
AP.compute_xyhb_ratemaps =                                                  ...
    struct('get_featureSet', @fet_xyhb,                                     ...
           'sampleRate',     16,                                            ...
           'pfsArgs',        struct('states',           activeState,        ...
                                    'binDims',          [50,50,0.1,0.1],    ...
                                    'SmoothingWeights', [2.4,2.4,1.8,1.8],  ...
                                    'numIter',          1,                  ...
                                    'boundaryLimits',   [-500,500;-500,500; ...
                                                         -2,0.8;-0.8,2],    ...
                                    'halfsample',       false)              ...
);
% <<< compute_xyhb_ratemaps <<< -----------------------------------------------


