
defargs = struct('fetSet',   'fet_mis',...
                 'mode',     'display',...
                 'tag',      '',...
                 'slist',   {{'hand_labeled_jg';'hand_labeled_Ed'}},...
                 'sampleRate', 12,...
                 'nNeurons',   100,...
                 'nIter',      100,...
                 'states',   {{'walk','rear','turn','pause','groom','sit'}},...
                 'rndMethod', 'WSBNT',...
                 'norm',      true,...
                 'mref',      true...
);

varargin = {};

[fetSet, mode, tag, slist, sampleRate, nNeurons, nIter,...
 states, rndMethod, norm, mref] = DefaultArgs(varargin,defargs,'--struct');

rlist = SessionList(rlist);

% within animal / within labeler
wawl = {}
for rli = 1:numel(slist),
    SesList = SessionList(slist{rli});
    for sli = 1:numel(SesList),
        wawl{end+1,1} = [SesList(sli).sessionName '.' SesList(sli).mazeName '.' ...
                         SesList(sli).trialName   '.' SesList(sli).stcMode];
        model = ['MTAC_BATCH-' tag fetSet ...
                 '_SR_' num2str(sampleRate) ...
                 '_NORM_' num2str(norm) ...         
                 '_REF_' SesList(sli).sessionName '.' ...
                         SesList(sli).mazeName '.' ...
                         SesList(sli).trialName ...
                 '_STC_' SesList(sli).stcMode ...
                 '_NN_' num2str(nNeurons) ...
                 '_NI_' num2str(nIter) ...         
                 '_NN_multiPN_RAND_' rndMethod];
        load(fullfile(MTASession().path.data,'analysis',...
                      [slist{sli},'-',model,'-map2ref','.mat']));
        wawl{end,2} = ls{sli};
    end
end

% different animal / different labeler
dadl = {}
for rli = 1:numel(slist),
    SesList = SessionList(slist{rli});
    for sli = 1:numel(SesList),
        dadl{end+1,1} = [SesList(sli).sessionName '.' SesList(sli).mazeName '.' ...
                         SesList(sli).trialName   '.' SesList(sli).stcMode];
        model = ['MTAC_BATCH-' tag fetSet ...
                 '_SR_' num2str(sampleRate) ...
                 '_NORM_' num2str(norm) ...         
                 '_REF_' SesList(sli).sessionName '.' ...
                         SesList(sli).mazeName '.' ...
                         SesList(sli).trialName ...
                 '_STC_' SesList(sli).stcMode ...
                 '_NN_' num2str(nNeurons) ...
                 '_NI_' num2str(nIter) ...         
                 '_NN_multiPN_RAND_' rndMethod];
        load(fullfile(MTASession().path.data,'analysis',...
                      [slist{sli},'-',model,'-map2ref','.mat']));
        dadl(end,2) = ls(sli);
    end
end



sli = 2; rli = 2;
SesList = SessionList(slist{sli});
wawl{2,1} = [rlist(rli).sessionName '.' rlist(rli).mazeName '.' rlist(rli).trialName];
wawl{2,2} = [SesList(1).sessionName '.' SesList(1).mazeName '.' SesList(1).trialName];
wawl{3,1} = [rlist(rli).sessionName '.' rlist(rli).mazeName '.' rlist(rli).trialName];
wawl{3,2} = [SesList(1).sessionName '.' SesList(1).mazeName '.' SesList(1).trialName];
SesList = {SesList(:).sessionName};
model = ['MTAC_BATCH-' fetSet ...
         '_SR_' num2str(sampleRate) ...
         '_NORM_' num2str(norm) ...         
         '_REF_' rlist(rli).sessionName '.' rlist(rli).mazeName '.' rlist(rli).trialName ...
         '_STC_' rlist(rli).stcMode ...
         '_NN_' num2str(nNeurons) ...
         '_NI_' num2str(nIter) ...         
         '_NN_multiPN_RAND_' rndMethod];
load(fullfile(MTASession().path.data,'analysis',[slist{sli},'-',model,'-map2ref','.mat']));
wawl{2,3} = ls{2};
wawl{3,3} = ls{3};
%1 

