% EgoProCode2D_f1_subplot_forward_field_distrib_every_phase

[pfig, sax] = setup_figure_( mfilename() );

% PLOT distribution of forward direction of rate map centers
hold(sax,'on');
[h,L,MX,MED,bw] = violin({egoMeanRmapPos(uidsCA1,1,1), ...
                          egoMeanRmapPos(uidsCA1,2,1), ...
                          egoMeanRmapPos(uidsCA1,3,1), ...                    
                          egoMeanRmapPos(uidsCA3,1,1), ...
                          egoMeanRmapPos(uidsCA3,2,1), ...
                          egoMeanRmapPos(uidsCA3,3,1), ...                    
                   });

% FORMAT subplot
delete(L);
af(@(hndl,c) set(hndl,'FaceColor',c{1}), h, mat2cell(pclr([1:3,1:3],:),ones([6,1]))');
xlim(sax,[0.5,6.5]);
%ylim(sax,[-25,35]);    
ylim(sax,[-15,25]);    
sax.YAxisLocation = 'left';
sax.YTickLabelMode = 'Auto';
sax.YTick = [-20,-10,0,10,20,30];
%sax.YTick = [-20,-10,0,10,20,30];
sax.XTickLabel = {};
grid(sax,'on');
%ylabel(sax,{'Anteroposterior','cm'});
ylabel(sax,'cm');

% ANOTATE gray patch for CA3
patch([ 3.5, 3.5, 6.5, 6.5], ...
      [ -25,  35,  35, -25], ...
      [  -1,  -1,  -1,  -1], ...
      [0.5,0.5,0.5],...
      'FaceAlpha',0.2,...
      'EdgeAlpha',0);

title(sax,'Anteroposterior');

text(sax,...
     2,...
     20,...
     'CA1',...
     'HorizontalAlignment','center');
text(sax,...
     5,...
     20,...
     'CA3',...
     'HorizontalAlignment','center');

% $$$ text(sax,...
% $$$      2,...
% $$$      25,...
% $$$      'CA1',...
% $$$      'HorizontalAlignment','center');
% $$$ text(sax,...
% $$$      5,...
% $$$      25,...
% $$$      'CA3',...
% $$$      'HorizontalAlignment','center');



savefig(pfig, fullfile(partsPath, [sax.Tag,'.fig']));

if close_figure
    close(pfig);
end

