% EgoProCode2D_f1_subplot_lateral_field_distrib_every_phase

[pfig, sax] = setup_figure_( mfilename() );

% PLOT distribution of forward direction of rate map centers
hold(sax,'on');
[h,L,MX,MED,bw] = violin({egoMeanRmapPos(uidsCA1,1,2), ...
                          egoMeanRmapPos(uidsCA1,2,2), ...
                          egoMeanRmapPos(uidsCA1,3,2), ...                    
                          egoMeanRmapPos(uidsCA3,1,2), ...
                          egoMeanRmapPos(uidsCA3,2,2), ...
                          egoMeanRmapPos(uidsCA3,3,2), ...                    
                   });

% FORMAT subplot
delete(L);
af(@(hndl,c) set(hndl,'FaceColor',c{1}), h, mat2cell(pclr([1:3,1:3],:),ones([6,1]))');
xlim(sax,[0.5,6.5]);
%ylim(sax,[-30,30]);    
ylim(sax,[-20,20]);    
sax.YAxisLocation = 'left';
sax.YTickLabelMode = 'Auto';
sax.YTick = [-20,-10,0,10,20];
sax.XTickLabel = {};
grid(sax,'on');
ylabel(sax,'cm');

% ANOTATE gray patch for CA3
patch([ 3.5, 3.5, 6.5, 6.5], ...
      [ -30,  30,  30, -30], ...
      [  -1,  -1,  -1,  -1], ...
      [0.8,0.8,0.8],...
      'FaceAlpha',0.2);
          
text(sax,...
     2,...
     15,...
     'CA1',...
     'HorizontalAlignment','center');
text(sax,...
     5,...
     15,...
     'CA3',...
     'HorizontalAlignment','center');

title(sax,'Lateral');

% $$$ text(sax,...
% $$$      2,...
% $$$      20,...
% $$$      'CA1',...
% $$$      'HorizontalAlignment','center');
% $$$ text(sax,...
% $$$      5,...
% $$$      20,...
% $$$      'CA3',...
% $$$      'HorizontalAlignment','center');
% $$$ 
% $$$ 

savefig(pfig, fullfile(partsPath, [sax.Tag,'.fig']));

if close_figure
    close(pfig);
end

