



rectangle('Position',findobj(gcf(),'Tag','EgoProCode2D_f1_subplot_egofieldExample_descending_phase').Position, ...
          'EdgeColor',pclr(1,:), ...
          'FaceColor','None',...
          'LineWidth',3);

rectangle('Position',findobj(gcf(),'Tag','EgoProCode2D_f1_subplot_egofieldExample_trough_phase').Position, ...
          'EdgeColor',pclr(2,:), ...
          'FaceColor','None',...
          'LineWidth',3);

rectangle('Position',findobj(gcf(),'Tag','EgoProCode2D_f1_subplot_egofieldExample_ascending_phase').Position, ...
          'EdgeColor',pclr(3,:), ...
          'FaceColor','None',...
          'LineWidth',3);


rectangle('Position',findobj(gcf(),'Tag','EgoProCode2D_f1_subplot_allofieldExample_descending_phase').Position, ...
          'EdgeColor',pclr(1,:), ...
          'FaceColor','None',...
          'LineWidth',3);

rectangle('Position',findobj(gcf(),'Tag','EgoProCode2D_f1_subplot_allofieldExample_trough_phase').Position, ...
          'EdgeColor',pclr(2,:), ...
          'FaceColor','None',...
          'LineWidth',3);

rectangle('Position',findobj(gcf(),'Tag','EgoProCode2D_f1_subplot_allofieldExample_ascending_phase').Position, ...
          'EdgeColor',pclr(3,:), ...
          'FaceColor','None',...
          'LineWidth',3);


%text @ "EgoProCode2D-f1-ascending-label-CA3" : { "x" : 657.625, "y" : 756.419677734375, "width" : 17, "height" : 17},

delete(lh)
sax = findobj(gcf(), 'Tag','EgoProCode2D_f1_subplot_forward_distrib_stats');
position = sax.Position;
lh = gobjects([1,0])
for p = 1:6
lh(p,1) = line(fax,                                               ...
               [0,position(3)/6]+position(1)+position(3)/6*(p-1), ...
               [1,1].* [position(2)+position(4)]+0.002,           ...
               'LineWidth',2,                                     ...
               'Color', pclr(p+double(6/p<2)*(-3),:));

lh(p,2) = line(fax,                                                                                    ...
               [1,1].* position(1) - 0.0025,                                                           ...
               [position(2)+position(4)-position(4)/6*(p-1),position(2)+position(4)-position(4)/6*(p)],...
               'LineWidth',2,                                                                          ...
               'Color', pclr(p+double(6/p<2)*(-3),:));
end

% CA1 Horizontal black line
line(fax,...
     [position(1),position(1)+position(3)/2],...
     [1,1].* [position(2)+position(4)]+0.005,...
     'LineWidth',2,...
     'Color', 'k');
text(fax,...
     [position(1)+position(3)/2/2],...
     [position(2)+position(4)]+0.011,...
     'CA1',...
     'HorizontalAlignment','center');

% CA3 Horizontal gray line
line(fax,...
     [position(1)+position(3)/2,position(1)+position(3)],...
     [1,1].* [position(2)+position(4)]+0.005,...
     'LineWidth',2,...
     'Color', 0.5.*ones([1,3]));
text(fax,...
     [position(1)+position(3)-position(3)/4],...
     [position(2)+position(4)]+0.011,...
     'CA3',...
     'HorizontalAlignment','center');


% CA1 Vertical black line
line(fax,...
     [position(1),position(1)]-0.006,...
     position(2)+position(4).*[0.5,1],...
     'LineWidth',2,...
     'Color', 'k');
% CA3 Vertical gray line
line(fax,...
     [position(1),position(1)]-0.006,...
     position(2)+position(4).*[0,0.5],...
     'LineWidth',2,...
     'Color', 0.5.*ones([1,3]));




sax = findobj(gcf(), 'Tag','EgoProCode2D_f1_subplot_lateral_distrib_stats');
position = sax.Position;
for p = 1:6
% $$$ lh(p,1) = line(fax,...
% $$$      [0,position(3)/6]+position(1)+position(3)/6*(p-1),...
% $$$      [1,1].* [position(2)+position(4)]+0.002,...
% $$$      'LineWidth',2,...
% $$$      'Color', pclr(p+double(6/p<2)*(-3),:));
lh(p,2) = line(fax,...
     [1,1].* position(1) - 0.0025,...
     [position(2)+position(4)-position(4)/6*(p-1),position(2)+position(4)-position(4)/6*(p)],...
     'LineWidth',2,...
     'Color', pclr(p+double(6/p<2)*(-3),:));
end

% CA1 horizontal black line
% $$$ line(fax,...
% $$$      [position(1),position(1)+position(3)/2],...
% $$$      [1,1].* [position(2)+position(4)]+0.005,...
% $$$      'LineWidth',2,...
% $$$      'Color', 'k');
% CA3 horizontal gray line
% $$$ line(fax,...
% $$$      [position(1)+position(3)/2,position(1)+position(3)],...
% $$$      [1,1].* [position(2)+position(4)]+0.005,...
% $$$      'LineWidth',2,...
% $$$      'Color', 0.5.*ones([1,3]));
% CA1 Vertical black line
% $$$ line(fax,...
% $$$      [position(1),position(1)]-0.006,...
% $$$      position(2)+position(4).*[0.5,1],...
% $$$      'LineWidth',2,...
% $$$      'Color', 'k');

% CA3 Vertical gray line
% $$$ line(fax,...
% $$$      [position(1),position(1)]-0.006,...
% $$$      position(2)+position(4).*[0,0.5],...
% $$$      'LineWidth',2,...
% $$$      'Color', 0.5.*ones([1,3]));
