% EgoProCode2D_f1_subplot_traj_ego_theta_trough

[pfig, sax] = setup_figure_(mfilename());

% SUBPLOT <- ego-traj, traj, spktraj(color=thetaPhase), rat model, circle
phzInd = 2;
plot(sax, ...
     pfstrj(sper,2),...
     pfstrj(sper,1),...
     '.',...
     'MarkerFaceColor',[0.25,0.25,0.25],...
     'MarkerEdgeColor',[0.25,0.25,0.25],...
     'MarkerSize',1);
% overlay spikes    
plot(sax, ...
     pfstrj(spktemp.res(spkPhzInd==phzInd),2),...
     pfstrj(spktemp.res(spkPhzInd==phzInd),1),...
     '.',...
     'MarkerFaceColor',pclr(spkPhzInd(spkPhzInd==phzInd),:),...
     'MarkerEdgeColor',pclr(spkPhzInd(spkPhzInd==phzInd),:),...
     'MarkerSize',1);
patch(subject.body.patch.vert{:},   [0.75,0.75,0.75]);
patch(subject.head.patch.vert{:},   [0.75,0.75,0.75]);
line(subject.head.midline.vert{:}, 'Color', subject.head.midline.color,'LineWidth',2);
line(subject.body.midline.vert{:}, 'Color', subject.body.midline.color,'LineWidth',2);
circle(0,0,200,'r-');

% FORMAT subplot
xlim(sax,[-300,300]);    
ylim(sax,[-300,300]);
sax.XTickLabel =[];
sax.YTickLabel =[];

savefig(pfig, fullfile(partsPath, [sax.Tag,'.fig']));        
close(pfig);        
