function Data = wrapBS(Session,data)
Data = MTADfet(Session.spath,...
               Session.filebase,...
               data,...
               1250,...
               Session.sync.copy,...
               Session.sync.data(1),...
               [],...
               'TimeSeries',...
               [],...
               'Choline Biosensor',...
               'cbs',...
               'c');                  

